const magmar = [
  {
    id: 20111,
    name: 'Dampening Wave',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'basic',
    faction: 'magmar',
    text: 'Choose an enemy minion. It can no longer counterattack.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20112,
    name: 'Flash Reincarnation',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'rare',
    faction: 'magmar',
    text:
      'If the next card you play this turn is a minion, it costs 2 less and takes 2 damage.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20119,
    name: 'Amplification',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'magmar',
    text: 'Give a friendly damaged minion +2 Attack and +4 Health.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20115,
    name: 'Dance of Dreams',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'magmar',
    text: 'Whenever a friendly minion dies this turn, draw a card.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 30037,
    name: 'Eternal Heart',
    set: 'unearthed',
    type: 'artifact',
    race: '',
    cost: 1,
    rarity: 'legendary',
    faction: 'magmar',
    text: 'Your General cannot die.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30028,
    name: 'Godhammer',
    set: 'ancients',
    type: 'artifact',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'magmar',
    text: 'Your minions have "Grow: +1/+1."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20116,
    name: 'Greater Fortitude',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'magmar',
    text: 'Give a friendly minion +2/+2.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20203,
    name: 'Lava Lance',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'magmar',
    text:
      'Deal 2 damage to a minion. If you have an Egg, deal 4 damage instead.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30049,
    name: 'Rage Reactor',
    set: 'immortal',
    type: 'artifact',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'magmar',
    text:
      'Your General gains +1 Attack.<br/>Whenever your General destroys an enemy, summon a Ripper Egg on that space.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20202,
    name: 'Razor Skin',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'magmar',
    text:
      'Give all friendly minions +1 Attack. Put a random Battle Pet into your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 421,
    name: 'Rex',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 1,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Rebirth</b>',
    attack: 3,
    health: 1,
    spirit: null
  },
  {
    id: 451,
    name: 'Angered Okkadok',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Intensify</b>: This minion gains +1/+1.',
    attack: 1,
    health: 2,
    spirit: null
  },
  {
    id: 444,
    name: 'Biomimetic Hulk',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Build</b>: (3).',
    attack: 10,
    health: 10,
    spirit: null
  },
  {
    id: 20258,
    name: 'Cascading Rebirth',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text:
      'Destroy a friendly minion to summon a random Magmar minion that costs 1 more.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20369,
    name: 'Deep Impact',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'magmar',
    text: 'Deal damage to a minion to reduce its Health to 1.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20113,
    name: 'Diretide Frenzy',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: 'Give a friendly minion +1 Attack and <b>Frenzy</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20312,
    name: 'Embryotic Insight',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: 'If you have an Egg, draw 2 cards.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20225,
    name: 'Entropic Gaze',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: 'Deal 2 damage to the enemy General. Both players draw a card.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 420,
    name: 'Gro',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 2,
    rarity: 'rare',
    faction: 'magmar',
    text: '<b>Grow</b>: +1/+1',
    attack: 2,
    health: 4,
    spirit: null
  },
  {
    id: 20358,
    name: 'Invigoration',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Intensify</b>: Restore 3 Health to your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30013,
    name: 'Iridium Scale',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Your General gains <b>Frenzy</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 409,
    name: 'Kujata',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'magmar',
    text:
      'Your minions cost 1 less to summon and take 1 damage when summoned from your action bar.',
    attack: 2,
    health: 2,
    spirit: null
  },
  {
    id: 20382,
    name: 'Mitotic Induction',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'magmar',
    text:
      'Summon an Egg of the minion most recently summoned from your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20125,
    name: 'Natural Selection',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'magmar',
    text:
      'Destroy ANY minion with the lowest Attack or tied for the lowest Attack.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 406,
    name: 'Phalanxar',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'magmar',
    text: '',
    attack: 6,
    health: 1,
    spirit: 0
  },
  {
    id: 20268,
    name: 'Primal Ballast',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'magmar',
    text: 'Dispel a space. If there is a minion on that space, give it +2/+2.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 430,
    name: 'Rancour',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'magmar',
    text:
      'Whenever your General takes damage, this minion gains that much attack. ',
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 446,
    name: 'Seismoid',
    set: 'immortal',
    type: 'minion',
    race: 'Mech',
    cost: 2,
    rarity: 'rare',
    faction: 'magmar',
    text:
      'Whenever you summon a Mech minion from your action bar, both players draw a card.',
    attack: 3,
    health: 1,
    spirit: null
  },
  {
    id: 20114,
    name: 'Tremor',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Stun</b> enemy minions in a 2x2 area.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20288,
    name: "Vaath's Brutality",
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Stun</b> an enemy minion. Give your General +1 Attack.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 438,
    name: 'Warpup',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'magmar',
    text: '<b>Forcefield</b>, <b>Frenzy</b>',
    attack: 1,
    health: 1,
    spirit: null
  },
  {
    id: 412,
    name: 'Young Silithar',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Rebirth</b>',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 30055,
    name: 'Zoetic Charm',
    set: 'mythron',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Your General has +1 Attack.<br/>Your Eggs have <b>Forcefield</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20390,
    name: 'Bellow',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'magmar',
    text:
      'Give a friendly minion +3 Attack.<br/><b>Stun</b> enemy minions around it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 439,
    name: 'Catalyst Quillbeast',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'magmar',
    text: 'Whenever you cast a spell, deal 1 damage to ALL minions.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 402,
    name: 'Earth Walker',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'magmar',
    text: '<b>Grow</b>: +1/+1',
    attack: 3,
    health: 3,
    spirit: 0
  },
  {
    id: 20346,
    name: 'Effulgent Infusion',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'magmar',
    text: "Give a friendly minion +Attack equal to your General's Attack.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20291,
    name: 'Endure the Beastlands',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Turn a 2x2 area into <b>Primal Flourish</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 448,
    name: 'Erratic Raptyr',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'magmar',
    text:
      '<b>Rebirth</b><br/>After this minion attacks or counterattacks, turn it into an Egg.',
    attack: 5,
    health: 5,
    spirit: null
  },
  {
    id: 20162,
    name: 'Kinetic Equilibrium',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'magmar',
    text:
      'Deal 2 damage to ALL minions in a 3x3 area. Friendly minions in the area also gain +2 Attack.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 455,
    name: 'Krater',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'magmar',
    text:
      '<b>Opening Gambit</b>: Deal 1 damage to everything (including itself).',
    attack: 2,
    health: 4,
    spirit: null
  },
  {
    id: 423,
    name: 'Moloki Huntress',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'magmar',
    text:
      "<b>Grow</b>: +1/+1<br/>Friendly minions grow at the start of BOTH player's turns.",
    attack: 1,
    health: 2,
    spirit: null
  },
  {
    id: 454,
    name: 'Oropsisaur',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      '<b>Grow</b>: +1/+1.<br/>Whenever another friendly minion with <b>Grow</b> survives damage, that minion grows.',
    attack: 2,
    health: 5,
    spirit: null
  },
  {
    id: 410,
    name: 'Primordial Gazer',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'magmar',
    text: '<b>Opening Gambit</b>: Give a nearby friendly minion +2/+2.',
    attack: 2,
    health: 2,
    spirit: 0
  },
  {
    id: 432,
    name: 'Ragebinder',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 3,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Rebirth</b><br/><b>Bond</b>: Restore 3 Health to your General.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 20234,
    name: 'Tectonic Spikes',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'magmar',
    text: 'Both players draw 3 cards. Deal 3 damage to both Generals.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 437,
    name: 'Terradon',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'magmar',
    text: '',
    attack: 2,
    health: 8,
    spirit: null
  },
  {
    id: 429,
    name: 'Thraex',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'magmar',
    text:
      '<b>Blood Surge</b>: All friendly minions gain +1 Attack (including itself).',
    attack: 2,
    health: 4,
    spirit: null
  },
  {
    id: 30017,
    name: 'Twin Fang',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      'Whenever a friendly minion or your General takes damage, your General gains +2 Attack.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20338,
    name: 'Upper Hand',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'magmar',
    text:
      "Deal 1 damage to an enemy minion for each card in your opponent's action bar.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 417,
    name: 'Vindicator',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'magmar',
    text: 'Whenever your opponent draws a card, this minion gains +2/+2.',
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 30012,
    name: 'Adamantite Claws',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 4,
    rarity: 'basic',
    faction: 'magmar',
    text: 'Your General gains +4 Attack.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 453,
    name: 'Beastclad Hunter',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'magmar',
    text: 'Takes no damage from minions with less Attack.',
    attack: 3,
    health: 6,
    spirit: null
  },
  {
    id: 20297,
    name: 'Blood Rage',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'magmar',
    text:
      'Give a friendly minion +1/+1 for each time damage was dealt this turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 428,
    name: 'Drogon',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'magmar',
    text: "<b>Blood Surge</b>: Double your General's Attack this turn.",
    attack: 5,
    health: 4,
    spirit: null
  },
  {
    id: 419,
    name: 'Earth Sister Taygete',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      'Whenever this minion takes damage, deal that much damage to all nearby enemies.',
    attack: 3,
    health: 4,
    spirit: 0
  },
  {
    id: 20117,
    name: 'Earth Sphere',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'magmar',
    text: 'Restore 8 Health to your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20157,
    name: 'Egg Morph',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'magmar',
    text: 'Turn a non-Egg minion into an Egg, or hatch an Egg.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 407,
    name: 'Elucidator',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'magmar',
    text:
      '<b>Rush</b><br/><b>Opening Gambit</b>: Deal 4 damage to your General.',
    attack: 5,
    health: 4,
    spirit: null
  },
  {
    id: 20370,
    name: 'Gargantuan Growth',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'magmar',
    text: 'Give a minion, "Grow: +8/+8."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 445,
    name: 'Gigaloth',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      '<b>Build</b>: (2).<br/>Whenever this minion attacks, other friendly minions gain +3/+3.',
    attack: 7,
    health: 7,
    spirit: null
  },
  {
    id: 403,
    name: 'Grimrock',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Grow</b>: +2/+2',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 458,
    name: 'Haruspex',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'magmar',
    text: 'Whenever this minion takes damage, your opponent draws a card.',
    attack: 7,
    health: 6,
    spirit: null
  },
  {
    id: 456,
    name: 'Hatefurnace',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'mythron',
    faction: 'magmar',
    text:
      '<b>Trial</b>: Cast 5 spells that give a minion +Attack.<br/><b>Destiny</b>: Minions summoned from your action bar gain <b>Rush</b> and <b>Frenzy</b>.',
    attack: 5,
    health: 4,
    spirit: null
  },
  {
    id: 20344,
    name: 'Homeostatic Rebuke',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'magmar',
    text: 'ALL minions attack themselves.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20156,
    name: 'Mind Steal',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'magmar',
    text: "Steal a random minion from your opponent's deck and summon it.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 440,
    name: 'Omniseer',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'magmar',
    text:
      "<b>Opening Gambit</b>: Turn a nearby friendly minion's space into <b>Primal Flourish</b>.",
    attack: 4,
    health: 5,
    spirit: null
  },
  {
    id: 441,
    name: 'Progenitor',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      '<b>Opening Gambit</b>: Each of your other non-Egg minions summon an Egg of itself behind itself.',
    attack: 5,
    health: 4,
    spirit: null
  },
  {
    id: 20319,
    name: 'Pupabomb',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Destroy a friendly Egg to deal 4 damage to enemies around it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 435,
    name: 'Rizen',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'magmar',
    text:
      'Whenever your opponent summons a minion, this minion summons an Egg of itself nearby.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 20218,
    name: 'Thumping Wave',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'magmar',
    text:
      'Give a minion +5 Attack. At end of turn, transform it into a 3/3 Kin.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20245,
    name: "Valknu's Seal",
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Summon an Egg that hatches into a copy of your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20296,
    name: 'Verdant Fulmination',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'magmar',
    text:
      "Your minions on friendly <b>Primal Flourish</b> grow. Turn your other minions' spaces into <b>Primal Flourish</b>.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 413,
    name: 'Veteran Silithar',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Rebirth</b>',
    attack: 4,
    health: 3,
    spirit: null
  },
  {
    id: 422,
    name: 'Wild Inceptor',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Opening Gambit</b>: Hatch a friendly Egg.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 404,
    name: 'Kolossus',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'common',
    faction: 'magmar',
    text: '<b>Grow</b>: +4/+4',
    attack: 1,
    health: 7,
    spirit: null
  },
  {
    id: 433,
    name: 'Lavaslasher',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 5,
    rarity: 'epic',
    faction: 'magmar',
    text: '<b>Opening Gambit</b>: This minion fights a nearby enemy minion.',
    attack: 4,
    health: 7,
    spirit: null
  },
  {
    id: 30025,
    name: 'Morin-Khur',
    set: 'shimzar',
    type: 'artifact',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      'Your General gains +3 Attack. Whenever your General deals damage, hatch all friendly Eggs.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 452,
    name: 'Mortar-maw',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'magmar',
    text:
      '<b>Ranged</b><br/>Whenever this minion attacks, it also damages enemies around its target.',
    attack: 4,
    health: 4,
    spirit: null
  },
  {
    id: 20206,
    name: "Nature's Confluence",
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Summon four copies of a random Battle Pet in a 2x2 area.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20122,
    name: 'Plasma Storm',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'basic',
    faction: 'magmar',
    text: 'Destroy ALL minions with 3 or less Attack.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 415,
    name: 'Spirit Harvester',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'magmar',
    text: 'At the end of your turn, deal 1 damage to ALL other minions.',
    attack: 5,
    health: 5,
    spirit: null
  },
  {
    id: 426,
    name: 'Visionar',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Whenever ANY player draws a card, this minion gains +1/+1.',
    attack: 6,
    health: 3,
    spirit: null
  },
  {
    id: 447,
    name: 'Armada',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'magmar',
    text: '<b>Blood Surge</b>: Deal 5 damage to the closest enemy.',
    attack: 5,
    health: 6,
    spirit: null
  },
  {
    id: 20124,
    name: 'Chrysalis Burst',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'magmar',
    text: 'Summon a random Egg in 4 random spaces.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 424,
    name: 'Dreadnought',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'magmar',
    text: '<b>Rebirth</b><br/>Egg minions you summon gain +2/+2.',
    attack: 4,
    health: 6,
    spirit: null
  },
  {
    id: 20063,
    name: 'Fractal Replication',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Summon two copies of a friendly minion nearby that minion.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 405,
    name: 'Makantor Warbeast',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'magmar',
    text: '<b>Frenzy</b><br/><b>Rush</b>',
    attack: 4,
    health: 4,
    spirit: null
  },
  {
    id: 20121,
    name: 'Metamorphosis',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      "Transform all enemy minions into 1/1 Magma with no abilities until the end of your opponent's turn.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20118,
    name: 'Bounded Lifeforce',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 7,
    rarity: 'epic',
    faction: 'magmar',
    text: 'Your General becomes 10/10.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20292,
    name: 'Evolutionary Apex',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      'BOTH players put all minions in their action bars onto the battlefield nearby their General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 414,
    name: 'Silithar Elder',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      '<b>Rebirth</b><br/>At the end of your turn, summon a Silithar Elder Egg nearby.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 408,
    name: 'Unstable Leviathan',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'rare',
    faction: 'magmar',
    text:
      'At the start of your turn, deal 4 damage to a random minion or General.',
    attack: 11,
    health: 11,
    spirit: null
  },
  {
    id: 20383,
    name: 'Extinction Event',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'magmar',
    text: 'Each of your Eggs hatches into a Katastrophosaurus.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20219,
    name: 'Flaming Stampede',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'magmar',
    text: 'Deal 5 damage to ALL non-Egg minions and Generals.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 434,
    name: 'Juggernaut',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 8,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      '<b>Grow</b>: +5/+5<br/>Whenever this minion takes damage, summon that many random Golem Eggs nearby.',
    attack: 4,
    health: 10,
    spirit: null
  },
  {
    id: 20339,
    name: 'Saurian Finality',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      '<b>Stun</b> the enemy General.<br/>Your General gains +3 Attack.<br/>Both players lose 3 mana.<br/>Restore 10 Health to your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 436,
    name: 'Grandmaster Kraigon',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 9,
    rarity: 'legendary',
    faction: 'magmar',
    text:
      '<b>Forcefield</b>, <b>Frenzy</b>, <b>Grow</b>: +7/+7.<br/>Your General has:<br/><b>Forcefield</b>, <b>Frenzy</b>, <b>Grow</b>: +7/+7.',
    attack: 7,
    health: 7,
    spirit: null
  },
  {
    id: 425,
    name: 'Mandrake',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 12,
    rarity: 'rare',
    faction: 'magmar',
    text:
      "Costs 1 less for each minion summoned from ANY player's action bar this game.",
    attack: 6,
    health: 6,
    spirit: null
  }
];

module.exports = magmar;
