/* eslint-disable */
const neutral = [{
  "id": 19052,
  "name": "Bloodtear Alchemist",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 1,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Deal 1 damage to an enemy.",
  "attack": 2,
  "health": 1,
  "spirit": 0
}, {
  "id": 10001,
  "name": "Dragonlark",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 1,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Flying</b>",
  "attack": 2,
  "health": 1,
  "spirit": 0
}, {
  "id": 11022,
  "name": "Dreamgazer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 1,
  "rarity": "epic",
  "faction": "neutral",
  "text": "When you replace this card, summon it nearby.  Your General takes 2 damage.",
  "attack": 1,
  "health": 1,
  "spirit": null
}, {
  "id": 19002,
  "name": "Helm of MECHAZ0R",
  "set": "core",
  "type": "minion",
  "race": "Mech",
  "cost": 1,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Progresses MECHAZ0R build by +20%.",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 11053,
  "name": "Koi",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 1,
  "rarity": "common",
  "faction": "neutral",
  "text": "Takes no damage from Generals.",
  "attack": 3,
  "health": 1,
  "spirit": null
}, {
  "id": 10018,
  "name": "Komodo Charger",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 1,
  "rarity": "basic",
  "faction": "neutral",
  "text": "",
  "attack": 1,
  "health": 3,
  "spirit": 0
}, {
  "id": 10019,
  "name": "Planar Scout",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 1,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Airdrop</b>",
  "attack": 2,
  "health": 1,
  "spirit": 0
}, {
  "id": 11016,
  "name": "Prophet of the White Palm",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 1,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Prevent ALL spell damage until your next turn.",
  "attack": 1,
  "health": 1,
  "spirit": null
}, {
  "id": 19025,
  "name": "Swamp Entangler",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 1,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Provoke</b>",
  "attack": 0,
  "health": 3,
  "spirit": null
}, {
  "id": 11083,
  "name": "Zyx",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 1,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Summon a copy of this minion on a random nearby space.",
  "attack": 1,
  "health": 2,
  "spirit": null
}, {
  "id": 10993,
  "name": "Aethermaster",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 2,
  "rarity": "epic",
  "faction": "neutral",
  "text": "You may replace an additional card each turn.",
  "attack": 1,
  "health": 3,
  "spirit": null
}, {
  "id": 11001,
  "name": "Amu",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11017,
  "name": "Araki Headhunter",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever you summon a minion with Opening Gambit from your action bar, gain +2 Attack.",
  "attack": 1,
  "health": 3,
  "spirit": null
}, {
  "id": 11084,
  "name": "Azure Herald",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Restore 3 Health to your General.",
  "attack": 1,
  "health": 4,
  "spirit": null
}, {
  "id": 19050,
  "name": "Azure Horn Shaman",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Give +4 Health to friendly minions around it.",
  "attack": 1,
  "health": 4,
  "spirit": null
}, {
  "id": 19029,
  "name": "Bluetip Scorpion",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "Deals double damage to minions.",
  "attack": 3,
  "health": 1,
  "spirit": null
}, {
  "id": 11102,
  "name": "Carcynus",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "",
  "attack": 1,
  "health": 5,
  "spirit": null
}, {
  "id": 11098,
  "name": "Celebrant",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Golem",
  "cost": 2,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Create a mana spring tile nearby.",
  "attack": 1,
  "health": 4,
  "spirit": 0
}, {
  "id": 11088,
  "name": "Cryptographer",
  "set": "bloodbound",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Refresh your Bloodbound Spell.",
  "attack": 2,
  "health": 2,
  "spirit": 0
}, {
  "id": 10020,
  "name": "Ephemeral Shroud",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Dispel 1 nearby space.",
  "attack": 1,
  "health": 1,
  "spirit": 0
}, {
  "id": 19051,
  "name": "Flameblood Warlock",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Deal 3 damage to BOTH Generals.",
  "attack": 3,
  "health": 1,
  "spirit": null
}, {
  "id": 11009,
  "name": "Ghost Lynx",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Teleport a nearby minion to a random space.",
  "attack": 2,
  "health": 1,
  "spirit": null
}, {
  "id": 19038,
  "name": "Golem Metallurgist",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 2,
  "rarity": "rare",
  "faction": "neutral",
  "text": "The first Golem you summon each turn costs 1 less.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 10981,
  "name": "Healing Mystic",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Restore 2 Health to anything.",
  "attack": 2,
  "health": 3,
  "spirit": 0
}, {
  "id": 11014,
  "name": "Jaxi",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Summon a 1/1 Ranged Mini-Jax in a random corner.",
  "attack": 1,
  "health": 1,
  "spirit": null
}, {
  "id": 10302,
  "name": "Manaforger",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 2,
  "rarity": "rare",
  "faction": "neutral",
  "text": "The first non-Bloodbound spell you cast each turn costs 1 less.",
  "attack": 1,
  "health": 3,
  "spirit": null
}, {
  "id": 10979,
  "name": "Maw",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Deal 2 damage to a nearby enemy minion.",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 19040,
  "name": "Piercing Mantis",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Frenzy</b>",
  "attack": 2,
  "health": 2,
  "spirit": 0
}, {
  "id": 19037,
  "name": "Primus Fist",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Give a nearby friendly minion +2 Attack this turn.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 19026,
  "name": "Rock Pulverizer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Provoke</b>",
  "attack": 1,
  "health": 4,
  "spirit": 0
}, {
  "id": 10957,
  "name": "Rust Crawler",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Destroy a random enemy artifact.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 11046,
  "name": "Shiro Puppydragon",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "At the end of your turn, give each nearby friendly minion +1 Attack.",
  "attack": 1,
  "health": 4,
  "spirit": null
}, {
  "id": 11109,
  "name": "Sinister Silhouette",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Cannot be attacked.",
  "attack": 1,
  "health": 2,
  "spirit": null
}, {
  "id": 19048,
  "name": "Skyrock Golem",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 2,
  "rarity": "basic",
  "faction": "neutral",
  "text": "",
  "attack": 3,
  "health": 2,
  "spirit": 0
}, {
  "id": 11066,
  "name": "Sol",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 2,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Activate a friendly Battle Pet.",
  "attack": 1,
  "health": 1,
  "spirit": null
}, {
  "id": 10021,
  "name": "Vale Hunter",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Ranged</b>",
  "attack": 1,
  "health": 2,
  "spirit": 0
}, {
  "id": 19003,
  "name": "Wings of MECHAZ0R",
  "set": "core",
  "type": "minion",
  "race": "Mech",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Airdrop</b><br><b>Opening Gambit</b>: Progresses MECHAZ0R build by +20%.",
  "attack": 1,
  "health": 4,
  "spirit": null
}, {
  "id": 11075,
  "name": "Wood-Wen",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Provoke</b><br><b>Opening Gambit</b>: Give a nearby friendly minion <b>Provoke</b>.",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 11061,
  "name": "Z0r",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 2,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Put a random MECH minion into your action bar.",
  "attack": 2,
  "health": 1,
  "spirit": null
}, {
  "id": 11039,
  "name": "Abjudicator",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Lower the cost of all spells in your action bar by 1.",
  "attack": 3,
  "health": 1,
  "spirit": null
}, {
  "id": 10304,
  "name": "Alcuin Loremaster",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 3,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Put a copy of the most recently cast spell into your action bar.",
  "attack": 3,
  "health": 1,
  "spirit": null
}, {
  "id": 11038,
  "name": "Bastion",
  "set": "core",
  "type": "minion",
  "race": "Structure",
  "cost": 3,
  "rarity": "epic",
  "faction": "neutral",
  "text": "At the end of your turn, give other friendly minions +1 Health.",
  "attack": 0,
  "health": 5,
  "spirit": null
}, {
  "id": 10013,
  "name": "Blaze Hound",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Both players draw a card.",
  "attack": 4,
  "health": 3,
  "spirit": null
}, {
  "id": 10205,
  "name": "Bloodshard Golem",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 3,
  "rarity": "basic",
  "faction": "neutral",
  "text": "",
  "attack": 4,
  "health": 3,
  "spirit": 0
}, {
  "id": 19004,
  "name": "Cannon of MECHAZ0R",
  "set": "core",
  "type": "minion",
  "race": "Mech",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Ranged</b><br><b>Opening Gambit</b>: Progresses MECHAZ0R build by +20%.",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 10962,
  "name": "Chaos Elemental",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever this minion takes damage, it randomly teleports.",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 19030,
  "name": "Crimson Oculus",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Whenever opponent summons a minion, this minion gains +1/+1.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 10953,
  "name": "Crossbones",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Destroy an enemy minion with Ranged.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11079,
  "name": "Day Watcher",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "Whenever a friendly minion attacks, restore 1 Health to your General.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11076,
  "name": "Elkowl",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Gain two random abilities.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 11090,
  "name": "Ghoulie",
  "set": "ancient bonds",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "This minion is from every tribe.",
  "attack": 3,
  "health": 4,
  "spirit": 0
}, {
  "id": 11056,
  "name": "Golden Mantella",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Put a random Battle Pet into your action bar.",
  "attack": 4,
  "health": 2,
  "spirit": null
}, {
  "id": 19039,
  "name": "Golem Vanquisher",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 3,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Provoke</b><br>Your other Golem minions have <b>Provoke</b>.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 11052,
  "name": "Hydrax",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever a friendly Battle Pet dies, draw a card.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11051,
  "name": "Ion",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Ranged</b><br>Deals double damage to Generals.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 11103,
  "name": "Komodo Hunter",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Your opponent summons two Komodo Chargers nearby their General.",
  "attack": 5,
  "health": 6,
  "spirit": null
}, {
  "id": 10987,
  "name": "Lady Locke",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Provoke</b><br><b>Opening Gambit</b>: Other minions you summon this turn gain +1/+1 and <b>Provoke</b>.",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 19047,
  "name": "Mirkblood Devourer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Friendly minions summoned nearby this minion gain +1/+1.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 11008,
  "name": "Mogwai",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "epic",
  "faction": "neutral",
  "text": "After this moves, draw a card.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 10303,
  "name": "Prismatic Illusionist",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Whenever you cast a spell, summon a 2/1 Illusion on a random nearby space.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 19033,
  "name": "Putrid Dreadflayer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Flying</b>",
  "attack": 2,
  "health": 4,
  "spirit": 0
}, {
  "id": 10016,
  "name": "Repulsor Beast",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Push a nearby enemy minion to any space.",
  "attack": 2,
  "health": 2,
  "spirit": 0
}, {
  "id": 11108,
  "name": "Rokadoptera",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Put a Boulder Hurl into your action bar.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 10012,
  "name": "Saberspine Tiger",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Rush</b>",
  "attack": 3,
  "health": 2,
  "spirit": 0
}, {
  "id": 10014,
  "name": "Sand Burrower",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "When this minion survives damage, it returns to your action bar.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 11027,
  "name": "Sapphire Seer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Forcefield</b>",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 19045,
  "name": "Sarlac the Eternal",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Re-summon this minion on a random space.",
  "attack": 1,
  "health": 1,
  "spirit": null
}, {
  "id": 10009,
  "name": "Silvertongue Corsair",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Takes no damage from Generals.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11035,
  "name": "Skywing",
  "set": "core",
  "type": "minion",
  "race": "Warmaster",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Flying</b><br>Your other minions with <b>Flying</b> cost 1 less.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11058,
  "name": "Soboro",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever this damages a neutral minion, destroy that minion.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 19049,
  "name": "Sojourner",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Whenever this minion deals damage, draw a card.",
  "attack": 1,
  "health": 5,
  "spirit": null
}, {
  "id": 10992,
  "name": "Songweaver",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Give a nearby friendly minion +1/+1.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 10301,
  "name": "Sun Seer",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "Whenever this minion deals damage, restore 2 Health to your General.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 19005,
  "name": "Sword of MECHAZ0R",
  "set": "core",
  "type": "minion",
  "race": "Mech",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Frenzy</b><br><b>Opening Gambit</b>: Progresses MECHAZ0R build by +20%.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 10954,
  "name": "Sworn Avenger",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Ranged</b><br>Whenever your General takes damage, this minion gains +1 Attack.",
  "attack": 1,
  "health": 3,
  "spirit": null
}, {
  "id": 10974,
  "name": "Syvrel the Exile",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Ranged</b><br>Minions damaged by Syvrel are pulled in front of him.",
  "attack": 1,
  "health": 4,
  "spirit": null
}, {
  "id": 10960,
  "name": "Venom Toth",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever your opponent summons a minion, deal 1 damage to the enemy General.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 10982,
  "name": "Void Hunter",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Draw a card.",
  "attack": 4,
  "health": 2,
  "spirit": null
}, {
  "id": 11105,
  "name": "Wild Tahr",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Frenzy</b><br/>Whenever an enemy attacks, this minion gains +3 Attack until the end of your turn.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 11007,
  "name": "Wind Runner",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "neutral",
  "text": "After this minion moves, give all friendly minions around it +1/+1.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 19010,
  "name": "Wind Stopper",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "Ranged attackers must attack this minion first.",
  "attack": 1,
  "health": 7,
  "spirit": null
}, {
  "id": 11020,
  "name": "Wings of Paradise",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Flying</b><br>Whenever you replace a card, this minion gains +2 Attack this turn.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11004,
  "name": "Yun",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 3,
  "rarity": "common",
  "faction": "neutral",
  "text": "",
  "attack": 5,
  "health": 4,
  "spirit": null
}, {
  "id": 11059,
  "name": "Zukong",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "You control your Battle Pets.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 11033,
  "name": "Arrow Whistler",
  "set": "core",
  "type": "minion",
  "race": "Warmaster",
  "cost": 4,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Ranged</b><br>Your other minions with <b>Ranged</b> have +1 Attack.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 10961,
  "name": "Artifact Hunter",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Draw a random artifact from your deck.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11006,
  "name": "Black Locust",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Flying</b><br>After this minion moves, summon a Black Locust nearby.",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 11043,
  "name": "Blistering Skorn",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Deal 1 damage to everything (including itself).",
  "attack": 4,
  "health": 5,
  "spirit": null
}, {
  "id": 11122,
  "name": "Bloodsworn Gambler",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Ranged</b><br/>Each time this minion attacks, it has a 50% chance to attack again, attacking a random enemy.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 10989,
  "name": "Captain Hank Hart",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Ranged</b><br>Whenever this deals damage, restore that much Health to it.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 19006,
  "name": "Chassis of MECHAZ0R",
  "set": "core",
  "type": "minion",
  "race": "Mech",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Progresses MECHAZ0R build by +20%.<br>Cannot be targeted by ANY spells.",
  "attack": 5,
  "health": 4,
  "spirit": null
}, {
  "id": 11086,
  "name": "Decimus",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever your opponent draws a card, deal 2 damage to the enemy General.",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 10976,
  "name": "Dioltas",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Summon a 0/10 Tombstone minion with Provoke nearby your General.",
  "attack": 5,
  "health": 3,
  "spirit": null
}, {
  "id": 10995,
  "name": "Emerald Rejuvenator",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Restore 4 Health to BOTH Generals.",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 11091,
  "name": "Feralu",
  "set": "ancient bonds",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Friendly minions from any tribe have +1/+1.",
  "attack": 4,
  "health": 3,
  "spirit": 0
}, {
  "id": 10017,
  "name": "Fire Spitter",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Ranged</b>",
  "attack": 3,
  "health": 2,
  "spirit": 0
}, {
  "id": 19042,
  "name": "Frostbone Naga",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Deal 2 damage to everything around it.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11057,
  "name": "Gnasher",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: This minion deals 3 damage to all enemies around it.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 10978,
  "name": "Hailstone Golem",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 4,
  "rarity": "basic",
  "faction": "neutral",
  "text": "",
  "attack": 4,
  "health": 6,
  "spirit": 0
}, {
  "id": 10306,
  "name": "Lightbender",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Dispel ALL spaces around it.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11096,
  "name": "Loreweaver",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Whenever you draw a spell, put a copy of it into your action bar.",
  "attack": 2,
  "health": 5,
  "spirit": 0
}, {
  "id": 11110,
  "name": "Matter Shaper",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Destroy an enemy artifact to put a random artifact from your faction into your action bar.",
  "attack": 5,
  "health": 4,
  "spirit": null
}, {
  "id": 10965,
  "name": "Mindwarper",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Gain a copy of a random spell from your opponent's action bar.",
  "attack": 4,
  "health": 3,
  "spirit": null
}, {
  "id": 10988,
  "name": "Moebius",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "At the start of your turn, fully heal this minion and switch its Attack and Health.",
  "attack": 3,
  "health": 5,
  "spirit": null
}, {
  "id": 11080,
  "name": "Night Watcher",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Forcefield</b><br>Whenever ANY player summons a minion with <b>Rush</b>, exhaust it.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 10305,
  "name": "Owlbeast Sage",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Whenever you cast a spell, your Arcanyst minions gain +2 Health.",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 19027,
  "name": "Primus Shieldmaster",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Provoke</b>",
  "attack": 3,
  "health": 6,
  "spirit": 0
}, {
  "id": 10991,
  "name": "Purgatos, The Realmkeeper",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever this minion deals damage, either deal 3 damage to the enemy General OR restore 3 Health to your General.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 11106,
  "name": "Razorcrag Golem",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "Golem",
  "cost": 4,
  "rarity": "common",
  "faction": "neutral",
  "text": "",
  "attack": 10,
  "health": 3,
  "spirit": null
}, {
  "id": 11087,
  "name": "Sanguinar",
  "set": "bloodbound",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Your Bloodbound Spell costs 1 less to activate.",
  "attack": 5,
  "health": 4,
  "spirit": 0
}, {
  "id": 19044,
  "name": "Silhouette Tracer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Teleport your General up to 3 spaces.",
  "attack": 2,
  "health": 6,
  "spirit": null
}, {
  "id": 10975,
  "name": "Spelljammer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Each player draws an additional card at the end of their turns.",
  "attack": 3,
  "health": 5,
  "spirit": null
}, {
  "id": 11078,
  "name": "Sphynx",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Put a Riddle in your opponent's action bar.",
  "attack": 5,
  "health": 4,
  "spirit": null
}, {
  "id": 11015,
  "name": "Sun Elemental",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Give two random friendly minions +2 Health.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 11028,
  "name": "Sunsteel Defender",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Forcefield</b>",
  "attack": 4,
  "health": 3,
  "spirit": null
}, {
  "id": 11041,
  "name": "Sworn Sister L'Kian",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Add 2 random cards from your Faction to your action bar.",
  "attack": 2,
  "health": 4,
  "spirit": 0
}, {
  "id": 11025,
  "name": "Tethermancer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Provoke</b><br>Dispel any minion that deals damage to this one.",
  "attack": 1,
  "health": 6,
  "spirit": null
}, {
  "id": 19031,
  "name": "Thorn Needler",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "basic",
  "faction": "neutral",
  "text": "",
  "attack": 6,
  "health": 4,
  "spirit": 0
}, {
  "id": 11115,
  "name": "Thunderhorn",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever this minion damages an enemy, it also damages all joined enemies.",
  "attack": 4,
  "health": 5,
  "spirit": null
}, {
  "id": 11036,
  "name": "Unseven",
  "set": "core",
  "type": "minion",
  "race": "Warmaster",
  "cost": 4,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Summon a minion with <b>Dying Wish</b> from your action bar.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 11019,
  "name": "White Widow",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Whenever you replace a card, deal 2 damage to a random enemy.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 19034,
  "name": "Young Flamewing",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Flying</b>",
  "attack": 5,
  "health": 4,
  "spirit": 0
}, {
  "id": 11040,
  "name": "Alter Rexx",
  "set": "core",
  "type": "minion",
  "race": "Mech",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever you summon MECHAZ0R, put a MECHAZ0R in your action bar.",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 10983,
  "name": "Ash Mephyt",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Summon two copies of this minion on random spaces.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 11054,
  "name": "Beastbound Savage",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Frenzy</b>, <b>Celerity</b>",
  "attack": 2,
  "health": 5,
  "spirit": null
}, {
  "id": 11094,
  "name": "Blue Conjurer",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 5,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Whenever you cast a spell, put a random Arcanyst into your action bar.",
  "attack": 4,
  "health": 6,
  "spirit": 0
}, {
  "id": 11092,
  "name": "Boulder Breacher",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Golem",
  "cost": 5,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Bond</b>: Enemies can't counterattack this turn.",
  "attack": 5,
  "health": 5,
  "spirit": 0
}, {
  "id": 10204,
  "name": "Brightmoss Golem",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 5,
  "rarity": "basic",
  "faction": "neutral",
  "text": "",
  "attack": 4,
  "health": 9,
  "spirit": 0
}, {
  "id": 11063,
  "name": "Calculator",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Gain the combined Attack and Health of all Battle Pets in your action bar.",
  "attack": 1,
  "health": 1,
  "spirit": null
}, {
  "id": 11042,
  "name": "Chakkram",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Costs 2 less if your General took damage on your opponent's last turn.",
  "attack": 5,
  "health": 5,
  "spirit": null
}, {
  "id": 10958,
  "name": "Dagger Kiri",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Celerity</b>",
  "attack": 2,
  "health": 8,
  "spirit": null
}, {
  "id": 10959,
  "name": "Dancing Blades",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Deal 3 damage to ANY minion in front of this.",
  "attack": 4,
  "health": 6,
  "spirit": null
}, {
  "id": 11048,
  "name": "Envybaer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever this minion damages an enemy, teleport that enemy to a random corner.",
  "attack": 3,
  "health": 7,
  "spirit": null
}, {
  "id": 19028,
  "name": "Fireblazer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Provoke</b>",
  "attack": 5,
  "health": 5,
  "spirit": null
}, {
  "id": 11011,
  "name": "Firestarter",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 5,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Whenever you cast a spell, summon a 1/1 Spellspark with <b>Rush</b> on a random nearby space.",
  "attack": 3,
  "health": 5,
  "spirit": null
}, {
  "id": 11034,
  "name": "Golden Justicar",
  "set": "core",
  "type": "minion",
  "race": "Warmaster",
  "cost": 5,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Provoke</b><br>Your other minions with <b>Provoke</b> can move two additional spaces.",
  "attack": 4,
  "health": 6,
  "spirit": null
}, {
  "id": 11049,
  "name": "Grincher",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Put a random artifact into your action bar. It costs 2 less.",
  "attack": 5,
  "health": 4,
  "spirit": null
}, {
  "id": 11024,
  "name": "Hollow Grovekeeper",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Destroy ANY nearby minion with Provoke or Frenzy. If you do, this minion gains Provoke and Frenzy.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 11064,
  "name": "Inquisitor Kron",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Provoke</b><br>Whenever you replace a card, summon a 2/2 Prisoner with a random ability nearby.",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 11085,
  "name": "Ironclad",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Dispel all enemy minions.",
  "attack": 4,
  "health": 3,
  "spirit": null
}, {
  "id": 11018,
  "name": "Keeper of the Vale",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Summon a friendly non-token minion destroyed this game nearby.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 11112,
  "name": "Letigress",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Ranged</b><br/>Whenever your General attacks, a cub joins the pack.",
  "attack": 2,
  "health": 6,
  "spirit": null
}, {
  "id": 10973,
  "name": "Lux Ignis",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Ranged</b><br>At the end of your turn, restore 2 Health to all nearby friendly minions.",
  "attack": 2,
  "health": 5,
  "spirit": null
}, {
  "id": 11031,
  "name": "Necroseer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "basic",
  "faction": "neutral",
  "text": "<b>Dying Wish</b>: Draw a card.",
  "attack": 5,
  "health": 4,
  "spirit": 0
}, {
  "id": 11111,
  "name": "Quahog",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "rare",
  "faction": "neutral",
  "text": "Enemy minions destroyed by this are returned to their action bar.",
  "attack": 7,
  "health": 7,
  "spirit": null
}, {
  "id": 11060,
  "name": "Rawr",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever this minion takes damage, summon a random Battle Pet nearby.",
  "attack": 3,
  "health": 7,
  "spirit": null
}, {
  "id": 19032,
  "name": "Rogue Warden",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Ranged</b>",
  "attack": 4,
  "health": 3,
  "spirit": null
}, {
  "id": 11030,
  "name": "Sunset Paragon",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: ALL nearby minions deal damage to themselves equal to their Attack.",
  "attack": 3,
  "health": 2,
  "spirit": null
}, {
  "id": 10955,
  "name": "Sworn Defender",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever your General takes damage, fully heal this minion.",
  "attack": 4,
  "health": 7,
  "spirit": null
}, {
  "id": 10985,
  "name": "The High Hand",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Gains +1/+1 for each card in your opponent's action bar.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 11114,
  "name": "Theobule",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Replace each card in your action bar.",
  "attack": 5,
  "health": 6,
  "spirit": null
}, {
  "id": 11097,
  "name": "Trinity Wing",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 5,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Flying</b><br/><b>Bond</b>: Put the three Teachings of the Dragon into your action bar.",
  "attack": 4,
  "health": 4,
  "spirit": 0
}, {
  "id": 10022,
  "name": "Twilight Sorcerer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Put a copy of a random spell you cast this game into your action bar.",
  "attack": 3,
  "health": 6,
  "spirit": null
}, {
  "id": 19043,
  "name": "Archon Spellbinder",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 6,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Your opponent's non-Bloodbound spells cost 1 more to cast.",
  "attack": 7,
  "health": 7,
  "spirit": null
}, {
  "id": 11023,
  "name": "Bonereaper",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Provoke</b><br>At the end of your turn, deal 2 damage to all nearby enemy minions.",
  "attack": 2,
  "health": 9,
  "spirit": null
}, {
  "id": 10980,
  "name": "Deathblighter",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Deal 3 damage to all enemy minions around it.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 11037,
  "name": "Diamond Golem",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 6,
  "rarity": "common",
  "faction": "neutral",
  "text": "",
  "attack": 5,
  "health": 11,
  "spirit": null
}, {
  "id": 11082,
  "name": "Dust Wailer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Flying</b><br><b>Opening Gambit</b>: Deal 3 damage to all enemies in front of this.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 10986,
  "name": "Eclipse",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 6,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever this minion takes damage, it deals that much damage to the enemy General.",
  "attack": 3,
  "health": 7,
  "spirit": null
}, {
  "id": 11032,
  "name": "Facestriker",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "basic",
  "faction": "neutral",
  "text": "Deals double damage to Generals.",
  "attack": 4,
  "health": 6,
  "spirit": 0
}, {
  "id": 10984,
  "name": "First Sword of Akrane",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "common",
  "faction": "neutral",
  "text": "Your other minions have +1 Attack.",
  "attack": 7,
  "health": 7,
  "spirit": null
}, {
  "id": 11095,
  "name": "Grimes",
  "set": "ancient bonds",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b> and <b>Dying Wish</b>: Summon a random minion from any tribe nearby.",
  "attack": 3,
  "health": 3,
  "spirit": 0
}, {
  "id": 11077,
  "name": "Grove Lion",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "epic",
  "faction": "neutral",
  "text": "While this minion is on the battlefield, your General has <b>Forcefield</b>.",
  "attack": 5,
  "health": 5,
  "spirit": null
}, {
  "id": 10963,
  "name": "Jax Truesight",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Ranged</b><br><b>Opening Gambit</b>: Summon a 1/1 <b>Ranged</b> Mini-Jax in each corner.",
  "attack": 1,
  "health": 1,
  "spirit": null
}, {
  "id": 11107,
  "name": "Magesworn",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 6,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "BOTH players cannot cast spells that cost 2 or less.",
  "attack": 3,
  "health": 8,
  "spirit": null
}, {
  "id": 11081,
  "name": "Quartermaster Gauj",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Takes no damage from minions or Generals.",
  "attack": 5,
  "health": 2,
  "spirit": null
}, {
  "id": 11045,
  "name": "Ruby Rifter",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever your General takes damage, give this minion +2 Attack and draw a card.",
  "attack": 4,
  "health": 6,
  "spirit": null
}, {
  "id": 10307,
  "name": "Serpenti",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Frenzy</b>",
  "attack": 7,
  "health": 4,
  "spirit": null
}, {
  "id": 11055,
  "name": "Silverbeak",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "common",
  "faction": "neutral",
  "text": "",
  "attack": 6,
  "health": 9,
  "spirit": null
}, {
  "id": 11116,
  "name": "Spriggin",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Provoke</b><br/><b>Opening Gambit</b>: Each player summons three Spriggin Kin nearby their General.",
  "attack": 6,
  "health": 6,
  "spirit": null
}, {
  "id": 19035,
  "name": "Storm Aratha",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Flying</b>",
  "attack": 6,
  "health": 5,
  "spirit": null
}, {
  "id": 10207,
  "name": "Stormmetal Golem",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 6,
  "rarity": "basic",
  "faction": "neutral",
  "text": "",
  "attack": 8,
  "health": 8,
  "spirit": 0
}, {
  "id": 11047,
  "name": "The Scientist",
  "set": "core",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 6,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever you cast a spell that targets a friendly minion, draw a card.",
  "attack": 6,
  "health": 6,
  "spirit": null
}, {
  "id": 10994,
  "name": "Zen'Rui, The BlightSpawned",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Take control of a nearby enemy minion with 2 or less Attack.",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 11021,
  "name": "Astral Crusader",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever you replace this card, it costs 1 less and gains +1/+1.",
  "attack": 7,
  "health": 6,
  "spirit": null
}, {
  "id": 19046,
  "name": "Dark Nemesis",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "At the start of your turn, deal 4 damage to the enemy General and this minion gains +4 Attack.",
  "attack": 4,
  "health": 10,
  "spirit": null
}, {
  "id": 10206,
  "name": "Drybone Golem",
  "set": "core",
  "type": "minion",
  "race": "Golem",
  "cost": 7,
  "rarity": "basic",
  "faction": "neutral",
  "text": "",
  "attack": 10,
  "health": 10,
  "spirit": 0
}, {
  "id": 11029,
  "name": "E'Xun",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Forcefield</b><br>Whenever this minion attacks or is attacked, draw a card.",
  "attack": 5,
  "health": 5,
  "spirit": null
}, {
  "id": 11104,
  "name": "Emberwyrm",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Flying</b>",
  "attack": 10,
  "health": 7,
  "spirit": null
}, {
  "id": 11093,
  "name": "EMP",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Golem",
  "cost": 7,
  "rarity": "rare",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Dispel ALL minions and Generals, and destroy ALL artifacts.",
  "attack": 9,
  "health": 9,
  "spirit": 0
}, {
  "id": 11010,
  "name": "Grailmaster",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "epic",
  "faction": "neutral",
  "text": "Whenever you summon a minion, this minion gains a random keyword ability.",
  "attack": 6,
  "health": 6,
  "spirit": null
}, {
  "id": 10997,
  "name": "Paddo",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Airdrop</b><br><b>Opening Gambit</b>:  Push ALL nearby minions and Generals to random spaces.",
  "attack": 12,
  "health": 6,
  "spirit": null
}, {
  "id": 10966,
  "name": "Pandora",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "At the end of your turn, summon a 3/3 Spirit Wolf with a random ability into a nearby space.",
  "attack": 3,
  "health": 10,
  "spirit": null
}, {
  "id": 10956,
  "name": "Red Synja",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever your General takes damage, deal 7 damage to a random nearby enemy minion.",
  "attack": 7,
  "health": 7,
  "spirit": null
}, {
  "id": 10990,
  "name": "Rook",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "At the end of your turn, this minion gains a random Faction ability.",
  "attack": 5,
  "health": 5,
  "spirit": null
}, {
  "id": 11026,
  "name": "War Talon",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Frenzy</b>, <b>Provoke</b>",
  "attack": 4,
  "health": 9,
  "spirit": null
}, {
  "id": 19036,
  "name": "Whistling Blade",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "common",
  "faction": "neutral",
  "text": "<b>Provoke</b>",
  "attack": 2,
  "health": 15,
  "spirit": null
}, {
  "id": 10996,
  "name": "Zurael, the Lifegiver",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Summon all friendly non-token minions destroyed on your opponent's last turn on random spaces.",
  "attack": 4,
  "health": 7,
  "spirit": null
}, {
  "id": 11121,
  "name": "Dagona",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 8,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Opening Gambit</b>: Devour ANY minion, anywhere.<br/><b>Dying Wish</b>: Spit out the devoured minion on this space.",
  "attack": 8,
  "health": 8,
  "spirit": null
}, {
  "id": 11013,
  "name": "Khymera",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 8,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "Whenever this minion takes damage, summon a random token minion nearby.",
  "attack": 5,
  "health": 12,
  "spirit": null
}, {
  "id": 11089,
  "name": "Meltdown",
  "set": "bloodbound",
  "type": "minion",
  "race": "",
  "cost": 8,
  "rarity": "legendary",
  "faction": "neutral",
  "text": "<b>Blood Surge</b>: Deal 6 damage to a random enemy.",
  "attack": 6,
  "health": 6,
  "spirit": 0
}, {
  "id": 11044,
  "name": "Blood Taura",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 25,
  "rarity": "epic",
  "faction": "neutral",
  "text": "<b>Provoke</b><br>This minion's cost is equal to your General's Health.",
  "attack": 12,
  "health": 12,
  "spirit": null
}];

module.exports = neutral;