const songhai = [
  {
    id: 154,
    name: 'Hideatsu the Ebon Ox',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 0,
    rarity: 'mythron',
    faction: 'songhai',
    text:
      '<b>Trial</b>: Summon 7 minions from your action bar with different costs.<br/><b>Destiny</b>: Summon friendly minions to deal their cost as damage to an enemy.',
    attack: 5,
    health: 5,
    spirit: null
  },
  {
    id: 20129,
    name: 'Juxtaposition',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Switch positions between ANY two minions.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20085,
    name: 'Mana Vortex',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'rare',
    faction: 'songhai',
    text: 'The next spell you cast this turn costs 1 less.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20355,
    name: 'Meditate',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'rare',
    faction: 'songhai',
    text:
      'Shuffle five copies of the spell you cast most recently into your deck.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 126,
    name: 'Ace',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text: '<b>Ranged</b>',
    attack: 1,
    health: 2,
    spirit: null
  },
  {
    id: 20323,
    name: 'Assassination Protocol',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text:
      'Reactivate an exhausted friendly minion. It cannot damage or attack Generals this turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30023,
    name: 'Crescent Spear',
    set: 'shimzar',
    type: 'artifact',
    race: '',
    cost: 1,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      'Your General gains +1 Attack. Spells you cast that deal damage deal +1 damage.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20088,
    name: 'Ghost Lightning',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'songhai',
    text: 'Deal 1 damage to all enemy minions.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20275,
    name: 'Gotatsu',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text: 'Deal 1 damage to a minion. Draw a card at end of turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 108,
    name: 'Heartseeker',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text: '<b>Ranged</b>',
    attack: 1,
    health: 1,
    spirit: null
  },
  {
    id: 30052,
    name: 'Horned Mask',
    set: 'mythron',
    type: 'artifact',
    race: '',
    cost: 1,
    rarity: 'epic',
    faction: 'songhai',
    text:
      'Your General gains +1 Attack.<br/>After a friendly minion with <b>Backstab</b> attacks, it gains +1/+1.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20086,
    name: 'Inner Focus',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'songhai',
    text: 'Reactivate an exhausted friendly minion with 3 or less Attack.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20256,
    name: 'Joseki',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text: "Each player steals a random card from their opponent's deck.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 129,
    name: 'Katara',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text: '<b>Backstab</b>: (3).',
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 20354,
    name: 'Knucklestorm',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text: '<b>Intensify</b>: Deal 1 damage to an enemy.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20168,
    name: 'Mist Dragon Seal',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text: 'Give a friendly minion +1/+1 and teleport it anywhere.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20167,
    name: 'Mist Walking',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Teleport your General up to 2 spaces.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20241,
    name: 'Obscuring Blow',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Give a friendly minion or General <b>Backstab</b> (2).',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20192,
    name: 'Shadow Waltz',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text:
      'Lower the cost of all minions with <b>Backstab</b> in your action bar by 1 and give them +1/+1.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20294,
    name: 'Spiral Counter',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'songhai',
    text: 'Deal 8 damage to an enemy minion that attacked last turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20106,
    name: 'Artifact Defiler',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'songhai',
    text: 'Destroy all artifacts on the enemy General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30010,
    name: 'Bloodrage Mask',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'songhai',
    text: 'Whenever you cast a spell, deal 1 damage to the enemy General.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 115,
    name: 'Chakri Avatar',
    set: 'core',
    type: 'minion',
    race: 'Arcanyst',
    cost: 2,
    rarity: 'basic',
    faction: 'songhai',
    text: 'Whenever you cast a spell, this minion gains +1/+1',
    attack: 1,
    health: 2,
    spirit: 0
  },
  {
    id: 20191,
    name: 'Crimson Coil',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'songhai',
    text: 'Deal 2 damage to a minion. Activate your Battle Pets.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20094,
    name: 'Deathstrike Seal',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'songhai',
    text:
      'Give a friendly minion, "Destroy any minion damaged by this minion."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20143,
    name: 'Eight Gates',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'legendary',
    faction: 'songhai',
    text: 'Spells you cast this turn that deal damage deal +2 damage.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20231,
    name: 'Ethereal Blades',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'songhai',
    text: 'Give a friendly minion AND your General +2 Attack this turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 110,
    name: 'Kaido Assassin',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'songhai',
    text: '<b>Backstab</b>: (1).',
    attack: 2,
    health: 3,
    spirit: 0
  },
  {
    id: 30007,
    name: 'Mask of Shadows',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'legendary',
    faction: 'songhai',
    text: 'Your General gains <b>Backstab</b> (4).',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20341,
    name: 'Mass Flight',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Give all friendly minions Flying this turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20194,
    name: 'Mirror Meld',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Summon a copy of a friendly minion that costs 2 or less nearby.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20081,
    name: 'Phoenix Fire',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'songhai',
    text: 'Deal 3 damage to anything.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20080,
    name: 'Saberspine Seal',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'songhai',
    text: 'Give a minion or General +3 Attack this turn.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 140,
    name: 'Scroll Bandit',
    set: 'unearthed',
    type: 'minion',
    race: 'Arcanyst',
    cost: 2,
    rarity: 'epic',
    faction: 'songhai',
    text:
      "<b>Backstab</b>: (1).<br/>Whenever this backstabs, steal a spell from your opponent's deck.",
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 20365,
    name: 'Second Self',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Put an EXACT copy of a friendly minion into your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 145,
    name: 'Suzumebachi',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'songhai',
    text:
      'Whenever you cast a spell, this minion gains +1 Attack until your next turn.',
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 121,
    name: 'Tusk Boar',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      '<b>Rush</b><br/>Return this minion to your action bar at the beginning of your turn.',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 125,
    name: 'Xho',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 2,
    rarity: 'rare',
    faction: 'songhai',
    text:
      '<b>Dying Wish</b>: Put a random Songhai spell into your action bar. It costs 1 less.',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 20327,
    name: 'Bamboozle',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'songhai',
    text:
      'Transform a nearby enemy minion into a 0/2 Panddo. If it is already a Panddo, instead destroy it and draw to fill your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30027,
    name: 'Bangle of Blinding Strike',
    set: 'ancients',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Your General has <b>Celerity</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 130,
    name: 'Battle Panddo',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Whenever this minion takes damage, deal 1 damage to all enemies.',
    attack: 2,
    health: 4,
    spirit: null
  },
  {
    id: 117,
    name: 'Celestial Phantom',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Destroy any minion damaged by this minion.',
    attack: 1,
    health: 5,
    spirit: null
  },
  {
    id: 30009,
    name: 'Cyclone Mask',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Your General gains <b>Ranged</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 151,
    name: 'Dusk Rigger',
    set: 'immortal',
    type: 'minion',
    race: 'Mech',
    cost: 3,
    rarity: 'rare',
    faction: 'songhai',
    text:
      '<b>Backstab</b>: (2).<br/>Whenever this backstabs, put a MECHAZ0R Progression into your action bar.',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 20283,
    name: 'Flicker',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Teleport your General to a space behind an enemy.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 112,
    name: 'Gore Horn',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'songhai',
    text: '<b>Backstab</b>: (2)<br/>After this minion attacks, it gains +1/+1.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 142,
    name: 'Hundred-Handed Rakushi',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'songhai',
    text:
      '<b>Sentinel</b>: Minion summoned.<br/>Deal 2 damage to the minion that transformed this.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 114,
    name: 'Jade Monk',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'songhai',
    text:
      'Whenever this minion takes damage, deal 1 damage to a random enemy minion.',
    attack: 4,
    health: 3,
    spirit: null
  },
  {
    id: 156,
    name: 'Kaido Expert',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'songhai',
    text:
      '<b>Backstab</b>: (1).<br/>Whenever this minion backstabs, summon a minion with <b>Backstab</b> that costs 2 or less from your deck nearby.',
    attack: 2,
    health: 2,
    spirit: null
  },
  {
    id: 128,
    name: 'Ki Beholder',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'songhai',
    text:
      '<b>Ranged</b><br/><b>Opening Gambit</b>: An enemy minion cannot move next turn.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 20102,
    name: 'Killing Edge',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'songhai',
    text:
      'Give a friendly minion +4/+2. If that minion has <b>Backstab</b>, draw a card at end of turn.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 122,
    name: 'Lantern Fox',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'songhai',
    text:
      'Whenever this minion takes damage, put a Phoenix Fire into your action bar.',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 144,
    name: 'Mind-Cage Oni',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'songhai',
    text:
      '<b>Sentinel</b>: Spell cast.<br/>Whenever your opponent casts a spell, put a copy of that spell into your action bar.',
    attack: 4,
    health: 3,
    spirit: null
  },
  {
    id: 143,
    name: 'Mizuchi',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'songhai',
    text:
      '<b>Sentinel</b>: General attacks.<br/><b>Flying</b><br/><b>Backstab</b>: (2).',
    attack: 2,
    health: 5,
    spirit: null
  },
  {
    id: 20087,
    name: 'Onyx Bear Seal',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'songhai',
    text:
      'Transform an enemy minion into a 0/2 Panddo that cannot be attacked.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 158,
    name: 'Orizuru',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'songhai',
    text: '<b>Flying</b>',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 20385,
    name: 'Pandatentiary',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'songhai',
    text:
      'Surround the enemy General with friendly Panddo that disappear at the start of your next turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 149,
    name: 'Penumbraxx',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      '<b>Build</b>: (2).<br/><b>Backstab</b>: (2).<br/>Whenever this backstabs, transform it into a building with <b>Build</b> (1).',
    attack: 3,
    health: 1,
    spirit: null
  },
  {
    id: 135,
    name: 'Sparrowhawk',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 3,
    rarity: 'common',
    faction: 'songhai',
    text: '<b>Bond</b>: Put a Mist Dragon Seal into your action bar.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 20328,
    name: 'Substitution',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Switch positions between a friendly minion and your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20314,
    name: 'Thunderbomb',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'songhai',
    text: 'Deal 3 damage to an enemy and 1 damage to all enemies around it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 132,
    name: 'Twilight Fox',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      '<b>Blood Surge</b>: Teleport a random enemy to the space behind your General.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 20082,
    name: 'Twin Strike',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'songhai',
    text:
      'Deal 2 damage to exactly two random enemy minions. Draw a card at end of turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30033,
    name: 'Unbounded Energy Amulet',
    set: 'unearthed',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      'Your General gains +1 Attack.<br/>Your General may move an additional space.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 134,
    name: 'Whiplash',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'songhai',
    text: '<b>Blood Surge</b>: Deal 2 damage to the enemy General.',
    attack: 4,
    health: 3,
    spirit: null
  },
  {
    id: 109,
    name: 'Widowmaker',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'songhai',
    text: '<b>Ranged</b>',
    attack: 2,
    health: 3,
    spirit: 0
  },
  {
    id: 20100,
    name: 'Ancestral Divination',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'songhai',
    text: 'Draw a card for each friendly minion.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 155,
    name: 'Bakezori',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Whenever this minion is moved for any reason, draw a card.',
    attack: 2,
    health: 6,
    spirit: null
  },
  {
    id: 160,
    name: 'Coalfist',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'songhai',
    text:
      '<b>Intensify</b>: Give a random nearby friendly minion +2 Attack this turn.',
    attack: 4,
    health: 4,
    spirit: null
  },
  {
    id: 20240,
    name: 'Cobra Strike',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Deal 3 damage to an enemy minion AND the enemy General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 138,
    name: 'Flamewreath',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'songhai',
    text:
      'Whenever this minion is moved for any reason, it deals 2 damage to all enemies around it.',
    attack: 2,
    health: 4,
    spirit: null
  },
  {
    id: 116,
    name: 'Four Winds Magi',
    set: 'core',
    type: 'minion',
    race: 'Arcanyst',
    cost: 4,
    rarity: 'rare',
    faction: 'songhai',
    text:
      'Whenever you cast a spell, deal 1 damage to enemy General and restore 1 Health to your General',
    attack: 4,
    health: 4,
    spirit: null
  },
  {
    id: 120,
    name: 'Keshrai Fanblade',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'songhai',
    text:
      "<b>Opening Gambit</b>: Next turn, opponent's spells cost 2 more to cast",
    attack: 5,
    health: 3,
    spirit: null
  },
  {
    id: 136,
    name: 'Kindling',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 4,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Whenever you cast a spell, your Arcanyst minions gain +1 Attack.',
    attack: 3,
    health: 5,
    spirit: null
  },
  {
    id: 148,
    name: 'Manakite Drifter',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'songhai',
    text:
      '<b>Build</b>: (2).<br/>When this minion is built, gain +2 mana this turn.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 157,
    name: 'Massacre Artist',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      '<b>Backstab</b>: (2).<br/>After this minion attacks and backstabs, all attacks are backstabs this turn.',
    attack: 2,
    health: 5,
    spirit: null
  },
  {
    id: 20193,
    name: 'Pandamonium',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'songhai',
    text:
      'Transform ALL minions into 0/2 Panddo that cannot be attacked until end of turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 124,
    name: 'Storm Sister Alkyone',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'songhai',
    text: 'Spells you cast that deal damage deal +1 damage.',
    attack: 3,
    health: 5,
    spirit: 0
  },
  {
    id: 150,
    name: 'Wildfire Tenketsu',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'songhai',
    text: '<b>Blood Surge</b>: Put an Eight Gates into your action bar.',
    attack: 3,
    health: 5,
    spirit: null
  },
  {
    id: 133,
    name: 'Geomancer',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'songhai',
    text: '<b>Opening Gambit</b>: Your Bloodbound Spell is Phoenix Fire.',
    attack: 5,
    health: 4,
    spirit: null
  },
  {
    id: 119,
    name: 'Hamon Bladeseeker',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'songhai',
    text: 'At the start of your turn, deal 2 damage to your General.',
    attack: 8,
    health: 8,
    spirit: null
  },
  {
    id: 20155,
    name: "Heaven's Eclipse",
    set: 'core',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'songhai',
    text: 'Draw 3 spell cards from your deck.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 127,
    name: 'Onyx Jaguar',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Whenever a friendly unit is moved for any reason, it gains +1/+1.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 20389,
    name: 'Phoenix Barrage',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'common',
    faction: 'songhai',
    text:
      'Deal 3 damage to anything.<br/>Put a Phoenix Fire into your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 111,
    name: 'Scarlet Viper',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'common',
    faction: 'songhai',
    text: '<b>Flying</b><br/><b>Backstab</b>: (4).',
    attack: 2,
    health: 5,
    spirit: null
  },
  {
    id: 20326,
    name: 'Seeker Squad',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      'Summon a Heartseeker in each nearby space diagonal from your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20267,
    name: 'Twilight Reiki',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      'Put 3 random Songhai minions into your action bar. They cost 1 less.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 159,
    name: 'Xenkai Cannoneer',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      '<b>Ranged</b><br/>Whenever you summon a minion with <b>Ranged</b>, that minion gains <b>Rush</b>.',
    attack: 4,
    health: 4,
    spirit: null
  },
  {
    id: 20279,
    name: 'Bombard',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Reactivate your minions with <b>Ranged</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 139,
    name: 'Eternity Painter',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      'At the end of your turn, transform all nearby enemy minions into 0/2 Panddos that cannot be attacked.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 20290,
    name: 'Firestorm Mantra',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'songhai',
    text:
      'Steal Health from the enemy General equal to twice the number of spells cast this turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 131,
    name: 'Grandmaster Zendo',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'songhai',
    text: 'The enemy General moves and attacks automatically.',
    attack: 4,
    health: 6,
    spirit: null
  },
  {
    id: 30038,
    name: 'Ornate Hiogi',
    set: 'immortal',
    type: 'artifact',
    race: '',
    cost: 6,
    rarity: 'rare',
    faction: 'songhai',
    text: 'Whenever you cast a spell, draw a card.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 137,
    name: 'Calligrapher',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 7,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      '<b>Rush</b><br/>Whenever this minion attacks, put three Songhai spells into your action bar at end of turn.',
    attack: 3,
    health: 7,
    spirit: null
  },
  {
    id: 146,
    name: 'Second-sword Sarugi',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'songhai',
    text: 'Your spells cost 2 less.',
    attack: 4,
    health: 7,
    spirit: null
  },
  {
    id: 118,
    name: 'Storm Kage',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      'Whenever one of your spells deals damage, put a Kage Lightning in your action bar.',
    attack: 5,
    health: 10,
    spirit: null
  },
  {
    id: 20217,
    name: 'Koan of Horns',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      'Transform all minions in your action bar and deck into 0-cost Gore Horns. Draw 3 cards.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20084,
    name: 'Spiral Technique',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'epic',
    faction: 'songhai',
    text: 'Deal 8 damage to anything.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20377,
    name: 'Kensho Vortex',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 11,
    rarity: 'legendary',
    faction: 'songhai',
    text:
      'Costs 1 less for each spell you cast this game. Whenever you cast a spell this turn, summon a minion that costs up to 2 more nearby your General.',
    attack: null,
    health: null,
    spirit: null
  }
];

module.exports = songhai;
