const vetruvian = [
  {
    id: 20335,
    name: 'Burden of Knowledge',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'common',
    faction: 'vetruvian',
    text: 'Deal 3 damage to your General to draw a card.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 227,
    name: 'Rae',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 0,
    rarity: 'common',
    faction: 'vetruvian',
    text: '<b>Dying Wish</b>: Dispel the nearest enemy minion.',
    attack: 1,
    health: 1,
    spirit: null,
  },
  {
    id: 20073,
    name: 'Siphon Energy',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'common',
    faction: 'vetruvian',
    text: 'Dispel an enemy minion nearby your General.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20255,
    name: 'Arid Unmaking',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      'Destroy a friendly minion to turn its space into <b>Exhuming Sand</b>.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20132,
    name: 'Auroras Tears',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      'This turn, your General gains +2 Attack for every equipped artifact.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20286,
    name: 'Azure Summoning',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      'Whenever you summon a minion with <b>Flying</b> from your action bar this turn, draw a minion with <b>Flying</b> from your deck.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20075,
    name: 'Blindscorch',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'vetruvian',
    text: "Lower a minion's Attack to 0 until your next turn.",
    attack: null,
    health: null,
    spirit: 0,
  },
  {
    id: 20300,
    name: 'Droplift',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'Steal a random artifact from the enemy General and equip it.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20313,
    name: 'Kinematic Projection',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'Give a minion Blast. It can no longer move.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 30036,
    name: 'Oblivion Sickle',
    set: 'unearthed',
    type: 'artifact',
    race: '',
    cost: 1,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      'Whenever your General destroys an enemy, turn that space into <b>Exhuming Sand</b>.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20095,
    name: "Scion's First Wish",
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'vetruvian',
    text: 'Give a friendly minion +1/+1. Draw a card.',
    attack: null,
    health: null,
    spirit: 0,
  },
  {
    id: 20246,
    name: 'Stone to Spears',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'vetruvian',
    text:
      'A friendly Obelysk gains +3 Attack and may move and attack this turn if able.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20151,
    name: 'Bone Swarm',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      'Deal 2 damage to the enemy General and all enemy minions around them.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20074,
    name: 'Cosmic Flesh',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'vetruvian',
    text: 'Give a friendly minion +1/+3 and <b>Provoke</b>.',
    attack: null,
    health: null,
    spirit: 0,
  },
  {
    id: 238,
    name: 'Dreamshaper',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 2,
    rarity: 'common',
    faction: 'vetruvian',
    text: '<b>Bond</b>: Draw two cards.',
    attack: 2,
    health: 2,
    spirit: null,
  },
  {
    id: 211,
    name: 'Dunecaster',
    set: 'core',
    type: 'minion',
    race: 'Dervish',
    cost: 2,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      '<b>Opening Gambit</b>: Give +2/+2 to a friendly Dervish. If it is a Wind Dervish, it no longer disappears.',
    attack: 2,
    health: 1,
    spirit: null,
  },
  {
    id: 241,
    name: 'Duskweaver',
    set: 'unearthed',
    type: 'minion',
    race: 'Dervish',
    cost: 2,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      "<b>Dying Wish</b>: Put a random Scion's Wish spell into your action bar.",
    attack: 1,
    health: 1,
    spirit: null,
  },
  {
    id: 20336,
    name: 'Equality Constraint',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vetruvian',
    text: "ANY minion's Health becomes equal to its Attack.",
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 214,
    name: 'Ethereal Obelysk',
    set: 'core',
    type: 'minion',
    race: 'Structure',
    cost: 2,
    rarity: 'basic',
    faction: 'vetruvian',
    text: '<b>Summon Dervish</b>',
    attack: 0,
    health: 6,
    spirit: 0,
  },
  {
    id: 20152,
    name: 'Fountain of Youth',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'Fully heal all friendly minions.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 30050,
    name: 'Iris Barrier',
    set: 'immortal',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'Your General takes no damage during your turn.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 243,
    name: 'Lavastorm Obelysk',
    set: 'unearthed',
    type: 'minion',
    race: 'Structure',
    cost: 2,
    rarity: 'rare',
    faction: 'vetruvian',
    text:
      '<b>Summon Dervish</b><br/>At the start of your turn, deal 6 damage to all enemy minions in this row.',
    attack: 0,
    health: 4,
    spirit: null,
  },
  {
    id: 20350,
    name: 'Neurolink',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'vetruvian',
    text: 'Your General gains all keywords of friendly minions this turn.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 228,
    name: 'Pax',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 2,
    rarity: 'rare',
    faction: 'vetruvian',
    text: '<b>Dying Wish</b>: Summon two 2/2 Iron Dervishes nearby.',
    attack: 2,
    health: 1,
    spirit: null,
  },
  {
    id: 213,
    name: 'Pyromancer',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'vetruvian',
    text: '<b>Blast</b>',
    attack: 2,
    health: 1,
    spirit: 0,
  },
  {
    id: 20099,
    name: "Rasha's Curse",
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      'Destroy a random artifact on the enemy General. Summon a Wind Dervish with <b>Rush</b> near them.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20265,
    name: 'Reassemble',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      'Return a friendly Obelysk to your action bar and reduce its cost to 0. Draw a card.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20093,
    name: 'Sand Trap',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vetruvian',
    text: 'Choose an enemy minion.  It can no longer move.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20096,
    name: "Scion's Second Wish",
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'vetruvian',
    text: 'Give a friendly minion +2/+2. It takes no damage from Generals.',
    attack: null,
    health: null,
    spirit: 0,
  },
  {
    id: 30006,
    name: "Staff Of Y'Kir",
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'vetruvian',
    text: 'Your General gains +2 Attack.',
    attack: null,
    health: null,
    spirit: 0,
  },
  {
    id: 20196,
    name: 'Whisper of the Sands',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vetruvian',
    text: 'Summon a Wind Dervish nearby each friendly Obelysk. Draw a card.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 229,
    name: 'Wind Slicer',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'vetruvian',
    text:
      '<b>Opening Gambit</b>: Lower the cost of all Structure minions in your action bar by 1.',
    attack: 2,
    health: 3,
    spirit: null,
  },
  {
    id: 20195,
    name: 'Astral Flood',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text: 'Put 3 random Battle Pets into your action bar.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20076,
    name: 'Astral Phasing',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text: 'Give a friendly minion +5 Health and <b>Flying</b>.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20242,
    name: 'Divine Spark',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text: 'Draw two cards.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 226,
    name: 'Falcius',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      '<b>Opening Gambit</b>: Your General gains +2 Attack and takes no damage this turn.',
    attack: 3,
    health: 3,
    spirit: null,
  },
  {
    id: 245,
    name: 'Fate Watcher',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      'Whenever your opponent draws a card, this minion gains a random keyword ability.',
    attack: 2,
    health: 3,
    spirit: null,
  },
  {
    id: 215,
    name: 'Fireblaze Obelysk',
    set: 'core',
    type: 'minion',
    race: 'Structure',
    cost: 3,
    rarity: 'rare',
    faction: 'vetruvian',
    text: '<b>Summon Dervish</b><br/>Your dervishes have +1 Attack.',
    attack: 0,
    health: 6,
    spirit: null,
  },
  {
    id: 218,
    name: 'Imperial Mechanyst',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'vetruvian',
    text:
      '<b>Opening Gambit</b>: Repair all of your artifacts to full durability.',
    attack: 2,
    health: 5,
    spirit: null,
  },
  {
    id: 20153,
    name: 'Inner Oasis',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'Give all friendly minions +3 Health. Draw a card.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 212,
    name: 'Orb Weaver',
    set: 'core',
    type: 'minion',
    race: 'Dervish',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      '<b>Opening Gambit</b>: Summon a copy of this minion on a nearby space.',
    attack: 2,
    health: 2,
    spirit: null,
  },
  {
    id: 221,
    name: 'Portal Guardian',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      '<b>Frenzy</b><br/>Whenever you summon a minion, this minion gains +1 Attack.',
    attack: 0,
    health: 6,
    spirit: null,
  },
  {
    id: 20197,
    name: 'Psychic Conduit',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'vetruvian',
    text:
      'Reactivate and take control of an enemy minion with 2 or less Attack until end of turn.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 210,
    name: 'Sand Howler',
    set: 'core',
    type: 'minion',
    race: 'Dervish',
    cost: 3,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'Cannot be targeted by enemy spells.',
    attack: 3,
    health: 3,
    spirit: null,
  },
  {
    id: 20097,
    name: "Scion's Third Wish",
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'vetruvian',
    text: 'Give a friendly Dervish minion +3/+3 and <b>Flying</b>.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 253,
    name: 'Simulacra Obelysk',
    set: 'immortal',
    type: 'minion',
    race: 'Structure',
    cost: 3,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      '<b>Build</b>: (2).<br/><b>Summon Dervish</b><br/>When this minion is built, start building another on a nearby space.',
    attack: 0,
    health: 7,
    spirit: null,
  },
  {
    id: 251,
    name: 'Skyppy',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text:
      "<b>Dying Wish</b>: Put a random legendary artifact from your opponent's Faction into your action bar.",
    attack: 3,
    health: 3,
    spirit: null,
  },
  {
    id: 20078,
    name: 'Time Maelstrom',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'vetruvian',
    text: 'Reactivate your General.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 30008,
    name: 'Wildfire Ankh',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'vetruvian',
    text: 'Your General gains <b>Blast</b>.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 216,
    name: 'Windstorm Obelysk',
    set: 'core',
    type: 'minion',
    race: 'Structure',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text: '<b>Summon Dervish</b><br/>Your dervishes have +1 Health.',
    attack: 0,
    health: 6,
    spirit: null,
  },
  {
    id: 235,
    name: 'Zephyr',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vetruvian',
    text: '<b>Blood Surge</b>: Your General gains <b>Frenzy</b> this turn.',
    attack: 3,
    health: 3,
    spirit: null,
  },
  {
    id: 231,
    name: 'Allomancer',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'vetruvian',
    text: '<b>Dying Wish</b>: Summon a random Obelysk on this space.',
    attack: 4,
    health: 3,
    spirit: null,
  },
  {
    id: 249,
    name: 'Barren Shrike',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'vetruvian',
    text: '<b>Build</b>: (2).<br/><b>Blast</b>',
    attack: 5,
    health: 5,
    spirit: null,
  },
  {
    id: 20077,
    name: 'Entropic Decay',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'basic',
    faction: 'vetruvian',
    text: 'Destroy an enemy minion nearby your General.',
    attack: null,
    health: null,
    spirit: 0,
  },
  {
    id: 30011,
    name: 'Hexblade',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      'Your General gains +3 Attack. Whenever your General damages an enemy minion, its Attack becomes 1.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20342,
    name: 'Lost in the Desert',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'vetruvian',
    text: 'Deal 6 damage to enemies that are not nearby another enemy.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 219,
    name: 'Mirage Master',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      '<b>Opening Gambit</b>: This minion transforms into a copy of an enemy minion.',
    attack: 1,
    health: 1,
    spirit: null,
  },
  {
    id: 224,
    name: 'Sand Sister Saon',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'vetruvian',
    text: 'Your General has +1 Attack.',
    attack: 3,
    health: 4,
    spirit: 0,
  },
  {
    id: 30029,
    name: 'Thunderclap',
    set: 'ancients',
    type: 'artifact',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'When your General destroys a minion, summon a copy of it nearby.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 242,
    name: 'Trygon Obelysk',
    set: 'unearthed',
    type: 'minion',
    race: 'Structure',
    cost: 4,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      '<b>Summon Dervish</b><br/><b>Summon Dervish</b><br/><b>Summon Dervish</b>',
    attack: 0,
    health: 9,
    spirit: null,
  },
  {
    id: 244,
    name: 'Wasteland Wraith',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'vetruvian',
    text: 'At the start of your turn, destroy this and all enemy minions.',
    attack: 1,
    health: 5,
    spirit: null,
  },
  {
    id: 208,
    name: 'Wind Shrike',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'basic',
    faction: 'vetruvian',
    text: '<b>Flying</b>. <b>Dying Wish</b>: Draw a card.',
    attack: 4,
    health: 3,
    spirit: 0,
  },
  {
    id: 239,
    name: 'Wind Striker',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 4,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      "<b>Flying</b><br/><b>Opening Gambit</b>: Equip a Staff of Y'kir to your General.",
    attack: 1,
    health: 4,
    spirit: null,
  },
  {
    id: 20254,
    name: 'Blood of Air',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'common',
    faction: 'vetruvian',
    text: 'Transform an enemy minion into a friendly Wind Dervish.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20198,
    name: 'Corpse Combustion',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      'Summon all friendly minions with Dying Wish destroyed since your last turn on random spaces.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 247,
    name: 'Gust',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'vetruvian',
    text: '<b>Blood Surge</b>: Summon two Wind Dervishes nearby.',
    attack: 3,
    health: 5,
    spirit: null,
  },
  {
    id: 236,
    name: 'Incinera',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'Your General may move 2 additional spaces.',
    attack: 5,
    health: 6,
    spirit: null,
  },
  {
    id: 232,
    name: 'Nimbus',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      'Whenever this minion takes damage, summon a 0/4 Soulburn Obelysk nearby.',
    attack: 3,
    health: 8,
    spirit: null,
  },
  {
    id: 246,
    name: 'Sandswirl Reader',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'vetruvian',
    text:
      '<b>Opening Gambit</b>: Return a nearby minion to its action bar. Turn that space into <b>Exhuming Sand</b>.',
    attack: 3,
    health: 4,
    spirit: null,
  },
  {
    id: 250,
    name: 'Silica Weaver',
    set: 'immortal',
    type: 'minion',
    race: 'Mech',
    cost: 5,
    rarity: 'rare',
    faction: 'vetruvian',
    text: '<b>Opening Gambit</b>: Progresses MECHAZ0R build by +40%.',
    attack: 4,
    health: 4,
    spirit: null,
  },
  {
    id: 240,
    name: 'Sirocco',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 5,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      "<b>Opening Gambit</b>: Summon a Skyrock Golem on random spaces for each other Golem you've summoned this game.",
    attack: 4,
    health: 3,
    spirit: null,
  },
  {
    id: 30022,
    name: 'Spinecleaver',
    set: 'shimzar',
    type: 'artifact',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      'Your General gains +1 Attack. Enemy minions destroyed by your General summon a Bloodfire Totem on that space.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20105,
    name: "Star's Fury",
    set: 'core',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      'Summon a Wind Dervish with <b>Rush</b> in front of each enemy minion and General.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 209,
    name: 'Starfire Scarab',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'common',
    faction: 'vetruvian',
    text: '<b>Blast</b>',
    attack: 4,
    health: 6,
    spirit: null,
  },
  {
    id: 20299,
    name: 'Superior Mirage',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'vetruvian',
    text:
      'Summon three copies of an enemy minion nearby it. They disappear when attacked.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 20244,
    name: "Autarch's Gifts",
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'vetruvian',
    text: 'Equip 2 random Vetruvian artifacts.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 220,
    name: 'Aymara Healer',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      '<b>Provoke</b><br/><b>Dying Wish</b>: Deal 5 damage to the enemy General. Restore 5 Health to your General.',
    attack: 5,
    health: 5,
    spirit: null,
  },
  {
    id: 20262,
    name: 'Cataclysmic Fault',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'vetruvian',
    text: 'Turn the entire center column into <b>Exhuming Sand</b>.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 252,
    name: 'Grapnel Paradigm',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      '<b>Opening Gambit</b>: Take control of enemy minions with 2 or less Attack on this row.',
    attack: 5,
    health: 5,
    spirit: null,
  },
  {
    id: 233,
    name: 'Pantheran',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'vetruvian',
    text: "Costs 0 if you've cast all three Scion's Wish spells this game.",
    attack: 6,
    health: 6,
    spirit: null,
  },
  {
    id: 20028,
    name: 'Dominate Will',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 7,
    rarity: 'rare',
    faction: 'vetruvian',
    text: 'Take control of an enemy minion nearby your General.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 222,
    name: 'Oserix',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      '<b>Flying</b><br/><b>Dying Wish</b>: Equip 2 random artifacts from your deck.',
    attack: 8,
    health: 6,
    spirit: null,
  },
  {
    id: 20216,
    name: 'Circle of Desiccation',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'vetruvian',
    text: 'Destroy ALL non-Structure minions.',
    attack: null,
    health: null,
    spirit: null,
  },
  {
    id: 237,
    name: 'Grandmaster Nosh-Rak',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      '<b>Blast</b><br/><b>Flying</b><br/>The enemy General takes double damage.',
    attack: 4,
    health: 8,
    spirit: null,
  },
  {
    id: 20322,
    name: 'Monolithic Vision',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 9,
    rarity: 'legendary',
    faction: 'vetruvian',
    text:
      'Transform your action bar into six random Vetruvian cards that cost 4 less.',
    attack: null,
    health: null,
    spirit: null,
  },
];

module.exports = vetruvian;
