const vetruvian = [
  { id: 20059, name: 'Darkfire Sacrifice', type: 'spell', cost: 0, rarity: 'rare', faction: 'abyssian', text: 'Destroy a friendly minion. Your next minion costs 2 less.' },
  { id: 308, name: 'Abyssal Crawler', type: 'minion', cost: 1, rarity: 'core', attack: 2, health: 1, faction: 'abyssian', text: 'At the end of your turn, turn a nearby space into <b>Shadow Creep</b>.' },
  { id: 20070, name: 'Grasp of Agony', type: 'spell', cost: 1, rarity: 'common', faction: 'abyssian', text: 'Choose an enemy minion. When it dies, it deals 3 damage to enemies around it.' },
  { id: 30005, name: 'Horn of the Forsaken', type: 'artifact', cost: 1, rarity: 'core', faction: 'abyssian', text: 'Whenever your General deals damage, summon a 1/1 Wraithling nearby your General.' },
  { id: 20201, name: 'Sphere of Darkness', type: 'spell', cost: 1, rarity: 'common', faction: 'abyssian', text: 'Turn a space into <b>Shadow Creep</b>. Draw a card.' },
  { id: 20052, name: 'Void Pulse', type: 'spell', cost: 1, rarity: 'common', faction: 'abyssian', text: 'Deal 2 damage to an enemy General. Restore 3 Health to your General.' },
  { id: 313, name: 'Blood Siren', type: 'minion', cost: 2, rarity: 'common', attack: 3, health: 2, faction: 'abyssian', text: '<b>Opening Gambit</b>: Give a nearby enemy minion or General -2 Attack this turn.' },
  { id: 20166, name: 'Consuming Rebirth', type: 'spell', cost: 2, rarity: 'epic', faction: 'abyssian', text: 'Destroy a friendly minion. At the end of your turn, re-summon it on the same space and give it +1/+1.' },
  { id: 20049, name: 'Daemonic Lure', type: 'spell', cost: 2, rarity: 'core', faction: 'abyssian', text: 'Deal 1 damage to an enemy minion and teleport it to any space on the battlefield.' },
  { id: 316, name: 'Darkspine Elemental', type: 'minion', cost: 2, rarity: 'rare', attack: 1, health: 4, faction: 'abyssian', text: 'Double the damage dealt by friendly Shadow Creep.' },
  { id: 20204, name: 'Echoing Shriek', type: 'spell', cost: 2, rarity: 'epic', faction: 'abyssian', text: 'Transform ALL minions that cost 2 or less into 1/1 Wraithlins.' },
  { id: 317, name: 'Gloomchaser', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 2, faction: 'abyssian', text: '<b>Opening Gambit</b>: Summon a 1/1 Wraithling in a random nearby space.' },
  { id: 326, name: 'Gor', type: 'battle pet', cost: 2, rarity: 'common', attack: 1, health: 1, faction: 'abyssian', text: '<b>Dying Wish</b>: Summon a copy of this minion in a random unoccupied corner.' },
  { id: 20200, name: 'Inkhorn Gaze', type: 'spell', cost: 2, rarity: 'common', faction: 'abyssian', text: 'Deal 2 damage to a minion. If it dies this turn, put a random Battle Pet into your action bar.' },
  { id: 20199, name: 'Lurking Fear', type: 'spell', cost: 2, rarity: 'epic', faction: 'abyssian', text: 'Lower the cost of all minions with <b>Dying Wish</b> in your action bar and deck by 1.' },
  { id: 327, name: 'Ooz', type: 'battle pet', cost: 2, rarity: 'rare', attack: 3, health: 3, faction: 'abyssian', text: 'Whenever this minion takes damage, turn a space occupied by an enemy into <b>Shadow Creep</b>.' },
  { id: 20071, name: 'Soulshatter Pact', type: 'spell', cost: 2, rarity: 'core', faction: 'abyssian', text: 'Give all friendly minions +2 Attack this turn.' },
  { id: 30014, name: 'Spectral Blade', type: 'artifact', cost: 2, rarity: 'epic', faction: 'abyssian', text: 'Your General gains +2 Attack. Whenever your General destroys an enemy minion, restore 2 Health to your General.' },
  { id: 328, name: 'Blood Baronette', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'abyssian', text: '<b>Opening Gambit</b>: Double a nearby Wraithling\'s Attack and Health.' },
  { id: 20133, name: 'Deathfire Crescendo', type: 'spell', cost: 3, rarity: 'legendary', faction: 'abyssian', text: 'Give a friendly minion, "<b>Deathwatch</b>: Gains +2/+2."' },
  { id: 319, name: 'Nightsorrow Assassin', type: 'minion', cost: 3, rarity: 'common', attack: 2, health: 1, faction: 'abyssian', text: '<b>Opening Gambit</b>: Destroy a nearby enemy minion with 2 or less Attack.' },
  { id: 20057, name: 'Ritual Banishing', type: 'spell', cost: 3, rarity: 'rare', faction: 'abyssian', text: 'Destroy a friendly minion to destroy an enemy minion.' },
  { id: 20065, name: 'Shadow Reflection', type: 'spell', cost: 3, rarity: 'common', faction: 'abyssian', text: 'Give a friendly minion +5 Attack.' },
  { id: 311, name: 'Shadow Watcher', type: 'minion', cost: 3, rarity: 'core', attack: 2, health: 2, faction: 'abyssian', text: '<b>Deathwatch</b>: Gains +1/+1.' },
  { id: 30002, name: 'Soul Grimwar', type: 'artifact', cost: 3, rarity: 'legendary', faction: 'abyssian', text: 'Your General gains, "<b>Deathwatch</b>: Gains +2 Attack."' },
  { id: 20205, name: 'Void Steal', type: 'spell', cost: 3, rarity: 'rare', faction: 'abyssian', text: 'Give an enemy minion +3 Attack. Nearby friendly minions gain +3 Attack.' },
  { id: 20089, name: 'Wraithling Fury', type: 'spell', cost: 3, rarity: 'epic', faction: 'abyssian', text: 'Give a friendly Wraithling minion +4/+4.' },
  { id: 20072, name: 'Wraithling Swarm', type: 'spell', cost: 3, rarity: 'core', faction: 'abyssian', text: 'Summon three 1/1 Wraithlings nearby each other.' },
  { id: 309, name: 'Abyssal Juggernaut', type: 'minion', cost: 4, rarity: 'common', attack: 3, health: 3, faction: 'abyssian', text: 'This minion has +1/+1 for each friendly <b>Shadow Creep</b>.' },
  { id: 310, name: 'Bloodmoon Priestess', type: 'minion', cost: 4, rarity: 'rare', attack: 3, health: 3, faction: 'abyssian', text: '<b>Deathwatch</b>: Summon a Wraithling on a random nearby space.' },
  { id: 20131, name: 'Breath Of The Unborn', type: 'spell', cost: 4, rarity: 'common', faction: 'abyssian', text: 'Deal 2 damage to all enemy minions. Restore all friendly minions to full Health.' },
  { id: 20069, name: 'Dark Seed', type: 'spell', cost: 4, rarity: 'rare', faction: 'abyssian', text: `Deal 1 damage to the enemy General for each card in the opponent's action bar.` },
  { id: 312, name: 'Deepfire Devourer', type: 'minion', cost: 4, rarity: 'common', attack: 4, health: 4, faction: 'abyssian', text: '<b>Frenzy</b><br> <b>Opening Gambit</b>: Destroy friendly minions around it and gain +2/+2 for each minion.' },
  { id: 30020, name: 'Ghost Azalea', type: 'artifact', cost: 4, rarity: 'legendary', faction: 'abyssian', text: 'Your General gains +1 Attack for each friendly <b>Shadow Creep</b>.' },
  { id: 20051, name: 'Shadow Nova', type: 'spell', cost: 4, rarity: 'core', faction: 'abyssian', text: 'Turn a 2x2 area into <b>Shadow Creep</b>.' },
  { id: 324, name: 'Shadow Sister Kelaino', type: 'minion', cost: 4, rarity: 'legendary', attack: 2, health: 5, faction: 'abyssian', text: 'Whenever an enemy minion or General takes damage, restore 1 Health to your General.' },
  { id: 321, name: 'Black Solus', type: 'minion', cost: 5, rarity: 'epic', attack: 4, health: 7, faction: 'abyssian', text: 'Whenever you summon a Wraithling, this gains +2 Attack.' },
  { id: 20061, name: 'Dark Transformation', type: 'spell', cost: 5, rarity: 'core', faction: 'abyssian', text: 'Destroy an enemy minion and summon a 1/1 Wraithling on that space.' },
  { id: 20050, name: 'Nether Summoning', type: 'spell', cost: 5, rarity: 'artifact', faction: 'abyssian', text: 'Summon 2 non-token minions destroyed since the end of your last turn nearby.' },
  { id: 325, name: 'Night Fiend', type: 'minion', cost: 5, rarity: 'common', attack: 3, health: 3, faction: 'abyssian', text: '<b>Opening Gambit</b>: Deal 2 damage to each enemy on or near friendly <b>Shadow Creep</b>.' },
  { id: 322, name: 'Reaper of the Nine Moons', type: 'minion', cost: 5, rarity: 'epic', attack: 5, health: 3, faction: 'abyssian', text: '<b>Flying</b><br> <b>Dying Wish</b>: Summon a random minion from the opponent\'s deck on this space.' },
  { id: 20154, name: 'Rite Of The Undervault', type: 'spell', cost: 5, rarity: 'epic', faction: 'abyssian', text: 'Draw to fill your action bar.' },
  { id: 318, name: 'Shadowdancer', type: 'minion', cost: 5, rarity: 'rare', attack: 4, health: 4, faction: 'abyssian', text: '<b>Deathwatch</b>: Deal 1 damage to the enemy General, and restore 1 Health to your General.' },
  { id: 330, name: 'Klaxon', type: 'minion', cost: 6, rarity: 'legendary', attack: 6, health: 6, faction: 'abyssian', text: '<b>Provoke</b><br> <b>Dying Wish</b>: Turn six random spaces into <b>Shadow Creep</b>.' },
  { id: 314, name: 'Vorpal Reaver', type: 'minion', cost: 6, rarity: 'legendary', attack: 6, health: 6, faction: 'abyssian', text: '<b>Celerity</b><br> <b>Dying Wish</b>: Summon six Wraithlings on random spaces.' },
  { id: 329, name: 'Arcane Devourer', type: 'minion', cost: 7, rarity: 'epic', attack: 8, health: 7, faction: 'abyssian', text: '<b>Opening Gambit</b>: The next minion you summon this turn costs 1.' },
  { id: 320, name: 'Spectral Revenant', type: 'minion', cost: 7, rarity: 'legendary', attack: 6, health: 6, faction: 'abyssian', text: '<b>Rush</b><br> Whenever this deals damage to an enemy minion, deal 4 damage to the enemy General.' },
  { id: 20213, name: 'Obliterate', type: 'spell', cost: 8, rarity: 'legendary', faction: 'abyssian', text: 'Destroy all friendly <b>Shadow Creep</b> to deal that much damage to all enemies.' },
]

export default vetruvian
