const abyssian = [
  {
    id: 20059,
    name: 'Darkfire Sacrifice',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'rare',
    faction: 'abyssian',
    text: 'Destroy a friendly minion. Your next minion costs 2 less.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 308,
    name: 'Abyssal Crawler',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'abyssian',
    text:
      'At the end of your turn, turn a nearby space into <b>Shadow Creep</b>.',
    attack: 2,
    health: 1,
    spirit: 0
  },
  {
    id: 20376,
    name: 'Demonic Conversion',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'abyssian',
    text: "Draw a minion from your opponent's deck. It gains +1/+1.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 331,
    name: 'Furiosa',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'abyssian',
    text: '<b>Blood Surge</b>: Friendly Wraithlings gain +1/+1.',
    attack: 1,
    health: 2,
    spirit: null
  },
  {
    id: 20070,
    name: 'Grasp of Agony',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'abyssian',
    text:
      'Choose an enemy minion. When it dies, it deals 3 damage to enemies around it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30005,
    name: 'Horn of the Forsaken',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'abyssian',
    text:
      'Whenever your General deals damage, summon a 1/1 Wraithling nearby your General.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20272,
    name: 'Inkling Surge',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'abyssian',
    text:
      'Summon a 1/1 Wraithling. If you have another Wraithling, draw a card.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20269,
    name: 'Nethermeld',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'Teleport ANY minion to friendly <b>Shadow Creep</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20356,
    name: 'Painful Pluck',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'abyssian',
    text:
      '<b>Intensify</b>: Turn 1 random space into <b>Shadow Creep</b>, prioritizing spaces under enemy minions.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20201,
    name: 'Sphere of Darkness',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'abyssian',
    text: 'Turn a space into <b>Shadow Creep</b>. Draw a card.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20052,
    name: 'Void Pulse',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'abyssian',
    text: 'Deal 2 damage to enemy General. Restore 3 Health to your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20226,
    name: 'Aphotic Drain',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'abyssian',
    text: 'Destroy a friendly minion to restore 5 Health to your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 313,
    name: 'Blood Siren',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'abyssian',
    text: '<b>Opening Gambit</b>: Give a nearby enemy -2 attack this turn.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 359,
    name: 'Carrion Collector',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      '<b>Dying Wish</b>: Lower the cost of all minions with <b>Dying Wish</b> in your deck and action bar by 1.',
    attack: 1,
    health: 1,
    spirit: null
  },
  {
    id: 20271,
    name: 'Choking Tendrils',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'abyssian',
    text: 'Destroy an enemy minion on friendly <b>Shadow Creep</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20166,
    name: 'Consuming Rebirth',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      'Destroy a friendly minion. At the end of your turn, re-summon it on the same space and give it +1/+1.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20049,
    name: 'Daemonic Lure',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'abyssian',
    text: 'Deal 1 damage to an enemy minion and teleport it anywhere.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 316,
    name: 'Darkspine Elemental',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'abyssian',
    text: 'Double the damage dealt by friendly <b>Shadow Creep</b>.',
    attack: 1,
    health: 4,
    spirit: null
  },
  {
    id: 20333,
    name: 'Deathmark',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      'Deal 1 damage to an enemy minion. After it is attacked this turn, destroy it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20204,
    name: 'Echoing Shriek',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'Transform ALL minions that cost 2 or less into 1/1 Wraithlings.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 363,
    name: 'Gibbet',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      'Whenever this attacks an enemy minion, destroy that minion and summon a Gibbet on that space.',
    attack: 1,
    health: 2,
    spirit: null
  },
  {
    id: 317,
    name: 'Gloomchaser',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'abyssian',
    text:
      '<b>Opening Gambit</b>: Summon a 1/1 Wraithling in a random nearby space.',
    attack: 2,
    health: 2,
    spirit: 0
  },
  {
    id: 326,
    name: 'Gor',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 2,
    rarity: 'common',
    faction: 'abyssian',
    text: '<b>Dying Wish</b>: Re-summon this minion in a random corner.',
    attack: 1,
    health: 1,
    spirit: null
  },
  {
    id: 20200,
    name: 'Inkhorn Gaze',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'abyssian',
    text:
      'Deal 2 damage to a minion. If it dies this turn, put a random Battle Pet into your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20199,
    name: 'Lurking Fear',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      'Lower the cost of all minions with <b>Dying Wish</b> in your action bar and deck by 1.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 351,
    name: 'Nightmare Operant',
    set: 'immortal',
    type: 'minion',
    race: 'Mech',
    cost: 2,
    rarity: 'rare',
    faction: 'abyssian',
    text: '<b>Dying Wish</b>: Shuffle a MECHAZ0R into your deck.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 337,
    name: 'Nocturne',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 2,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'Whenever you make Shadow Creep or a Wraithling, instead make both.',
    attack: 2,
    health: 2,
    spirit: null
  },
  {
    id: 327,
    name: 'Ooz',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 2,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      'Whenever this minion takes damage, turn a space occupied by an enemy into <b>Shadow Creep</b>.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 339,
    name: 'Phantasm',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'abyssian',
    text:
      'Whenever your opponent summons a minion, give a minion in your action bar +1 Attack.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 20243,
    name: 'Punish',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'abyssian',
    text: 'Destroy a damaged minion.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20273,
    name: 'Shadowstalk',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'abyssian',
    text: 'Summon a Wraithling behind each enemy.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20071,
    name: 'Soulshatter Pact',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'abyssian',
    text: 'Give all friendly minions +2 Attack this turn.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 30014,
    name: 'Spectral Blade',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      'Your General gains +2 Attack.<br/>Whenever your General destroys an enemy, restore 2 Health to your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20367,
    name: 'Yielding Depths',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'abyssian',
    text: 'If you have three or more <b>Shadow Creep</b>, draw 2 cards.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20348,
    name: 'Abhorrent Unbirth',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      'Destroy all friendly minions to summon a 1/1 Abomination that gains their Attack, Health, and keywords.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 328,
    name: 'Blood Baronette',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'abyssian',
    text: "Opening Gambit: Double a nearby Wraithling's Attack and Health.",
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 20257,
    name: 'Blood Echoes',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'abyssian',
    text:
      'Destroy all friendly minions and resummon them on random spaces at end of turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 361,
    name: 'Bonecrusher',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'abyssian',
    text: '<b>Intensify</b>: This minion gains +5 Attack.',
    attack: 0,
    health: 3,
    spirit: null
  },
  {
    id: 344,
    name: 'Bound Tormentor',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'abyssian',
    text:
      '<b>Sentinel</b>: Minion summoned.<br/>Put a copy of the minion that transformed this into your action bar. It costs 2 less.',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 362,
    name: 'Chittering Tiller',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'abyssian',
    text:
      '<b>Frenzy</b><br/><b>Opening Gambit</b>: Teleport the enemy General one space forward.',
    attack: 4,
    health: 3,
    spirit: null
  },
  {
    id: 20133,
    name: 'Deathfire Crescendo',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'abyssian',
    text: 'Give a friendly minion, "<b>Deathwatch</b>: Gains +2/+2."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20340,
    name: 'Horrific Visage',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'abyssian',
    text: 'Give all enemy minions -3 Attack until your next turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 334,
    name: 'Horror Burster',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      '<b>Dying Wish</b>: Transform a random friendly minion into a 6/6 Horror.',
    attack: 4,
    health: 1,
    spirit: null
  },
  {
    id: 20321,
    name: 'Infest',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      'Choose an enemy minion. When it dies, give this effect to all nearby enemy minions and deal 2 damage to the enemy General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30034,
    name: 'Mindlathe',
    set: 'unearthed',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      'After your General damages a minion, reactivate and take control of it until the end of your turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20374,
    name: 'Munch',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      'Steal Health from an enemy minion for each friendly Shadow Creep (but not more than its Health).',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 319,
    name: 'Nightsorrow Assassin',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'abyssian',
    text:
      '<b>Opening Gambit</b>: Destroy a nearby enemy minion with 2 or less attack.',
    attack: 2,
    health: 1,
    spirit: null
  },
  {
    id: 20057,
    name: 'Ritual Banishing',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'abyssian',
    text: 'Destroy a friendly minion to destroy an enemy minion.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20065,
    name: 'Shadow Reflection',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'abyssian',
    text: 'Give a friendly minion +5 Attack.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 311,
    name: 'Shadow Watcher',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'abyssian',
    text: '<b>Deathwatch</b>: Gains +1/+1.',
    attack: 2,
    health: 2,
    spirit: 0
  },
  {
    id: 343,
    name: 'Skullprophet',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      '<b>Sentinel</b>: General attacks.<br/>The enemy General has -1 Attack.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 30002,
    name: 'Soul Grimwar',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'abyssian',
    text: 'Your General gains, "<b>Deathwatch</b>: Gains +2 Attack."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30030,
    name: 'The Releaser',
    set: 'ancients',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      'When this artifact breaks, summon a random friendly non-token minion destroyed this game nearby.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20205,
    name: 'Void Steal',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      'Give an enemy minion -3 Attack. Nearby friendly minions gain +3 Attack.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 350,
    name: 'Void Talon',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'abyssian',
    text: '<b>Build</b>: (1).',
    attack: 6,
    health: 1,
    spirit: null
  },
  {
    id: 20089,
    name: 'Wraithling Fury',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'Give a friendly Wraithling minion +4/+4.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20072,
    name: 'Wraithling Swarm',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'abyssian',
    text: 'Summon three 1/1 Wraithlings nearby each other.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 345,
    name: 'Xerroloth',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      '<b>Sentinel</b>: Spell cast.<br/>Whenever your opponent casts a spell, put a 4/4 Fiend into your action bar.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 309,
    name: 'Abyssal Juggernaut',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'abyssian',
    text: 'This minion has +1/+1 for each friendly <b>Shadow Creep</b>.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 310,
    name: 'Bloodtide Priestess',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'abyssian',
    text: '<b>Deathwatch</b>: Summon a Wraithling on a random nearby space.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 20131,
    name: 'Breath Of The Unborn',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'abyssian',
    text:
      'Deal 2 damage to all enemy minions. Fully heal all friendly minions.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 348,
    name: 'Cacophynos',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'abyssian',
    text: '<b>Dying Wish</b>: Destroy a random nearby enemy minion.',
    attack: 6,
    health: 3,
    spirit: null
  },
  {
    id: 20069,
    name: 'Dark Seed',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      "Deal 1 damage to the enemy General for each card in the opponent's action bar.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 312,
    name: 'Deepfire Devourer',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'abyssian',
    text:
      '<b>Frenzy</b><br/><b>Opening Gambit</b>: Destroy friendly minions around it and gain +2/+2 for each minion.',
    attack: 4,
    health: 4,
    spirit: null
  },
  {
    id: 341,
    name: 'Desolator',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Opening Gambit</b>: Steal 2 Health from the enemy General.<br/><b>Dying Wish</b>: Return Desolator to your action bar.',
    attack: 3,
    health: 1,
    spirit: null
  },
  {
    id: 353,
    name: 'Gate to the Undervault',
    set: 'immortal',
    type: 'minion',
    race: 'Structure',
    cost: 4,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Build</b>: (3).<br/><b>Invulnerable</b><br/><b>Deathwatch</b>: Summon a random Demon nearby.',
    attack: 0,
    health: 0,
    spirit: null
  },
  {
    id: 30020,
    name: 'Ghost Azalea',
    set: 'shimzar',
    type: 'artifact',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'abyssian',
    text: 'Your General gains +1 Attack for each friendly <b>Shadow Creep</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 340,
    name: 'Nekomata',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      '<b>Dying Wish</b>: Draw two minions with <b>Dying Wish</b> from your deck.',
    attack: 4,
    health: 2,
    spirit: null
  },
  {
    id: 336,
    name: 'Nightshroud',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 4,
    rarity: 'common',
    faction: 'abyssian',
    text:
      '<b>Bond</b>: Your General steals 1 Health from the enemy General for each other friendly Arcanyst.',
    attack: 5,
    health: 1,
    spirit: null
  },
  {
    id: 20051,
    name: 'Shadow Nova',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'basic',
    faction: 'abyssian',
    text: 'Turn a 2x2 area into <b>Shadow Creep</b>.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 324,
    name: 'Shadow Sister Kelaino',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'abyssian',
    text: 'Whenever an enemy takes damage, restore 1 Health to your General.',
    attack: 3,
    health: 3,
    spirit: 0
  },
  {
    id: 20334,
    name: 'Vellumscry',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'abyssian',
    text: 'Destroy a friendly minion to draw three cards.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30051,
    name: 'Wraithcrown',
    set: 'mythron',
    type: 'artifact',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'Friendly Wraithlings have +2/+2.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 321,
    name: 'Black Solus',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'When you summon a Wraithling, this minion gains +2 Attack.',
    attack: 4,
    health: 7,
    spirit: null
  },
  {
    id: 20284,
    name: 'Corporeal Cadence',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'Destroy a friendly minion to deal its Attack to the enemy General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20061,
    name: 'Dark Transformation',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'basic',
    faction: 'abyssian',
    text: 'Destroy an enemy minion and summon a 1/1 Wraithling on that space.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 30039,
    name: 'Furor Chakram',
    set: 'immortal',
    type: 'artifact',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'abyssian',
    text: 'Friendly minions gain +2 Attack and <b>Frenzy</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 358,
    name: 'Hexclaw',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Dying Wish</b>: The enemy General gains, "At the start of your turn, take 1 damage."',
    attack: 7,
    health: 2,
    spirit: null
  },
  {
    id: 20050,
    name: 'Nether Summoning',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      'Summon 2 non-token minions destroyed since the end of your last turn nearby.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 325,
    name: 'Night Fiend',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'common',
    faction: 'abyssian',
    text:
      '<b>Opening Gambit</b>: Deal 2 damage to each enemy on or near friendly <b>Shadow Creep</b>.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 322,
    name: 'Reaper of the Nine Moons',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      "<b>Flying</b><br/><b>Dying Wish</b>: Summon a random minion from the opponent's deck on this space.",
    attack: 5,
    health: 3,
    spirit: null
  },
  {
    id: 318,
    name: 'Shadowdancer',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'abyssian',
    text:
      '<b>Deathwatch</b>: Deal 1 damage to the enemy General, and restore 1 Health to your General.',
    attack: 4,
    health: 4,
    spirit: null
  },
  {
    id: 360,
    name: 'Abyssal Tormentor',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Provoke</b><br/>Your <b>Shadow Creep</b> deals damage equal to the number of friendly <b>Shadow Creep</b>.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 20331,
    name: 'Betrayal',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'Enemy minions nearby their General attack their General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 330,
    name: 'Klaxon',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Provoke</b><br/><b>Dying Wish</b>: Turn six random spaces into <b>Shadow Creep</b>.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 352,
    name: 'Moonrider',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'abyssian',
    text: '<b>Blood Surge</b>: Summon a 4/4 Fiend on a nearby space.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 20227,
    name: 'Necrotic Sphere',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      'Destroy ALL minions nearby your General and summon Wraithlings in their place.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20154,
    name: 'Rite Of The Undervault',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'abyssian',
    text: 'Draw to fill your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 357,
    name: "Underlord Xor'Xuul",
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'mythron',
    faction: 'abyssian',
    text:
      '<b>Trial</b>: Cast 6 spells that destroy a friendly minion.<br/><b>Destiny</b>: Whenever a friendly minion dies, re-summon it on a random space.',
    attack: 6,
    health: 1,
    spirit: null
  },
  {
    id: 20373,
    name: 'Unfathomable Rite',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'abyssian',
    text: "Draw cards from your opponent's deck to fill your action bar.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 314,
    name: 'Vorpal Reaver',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Celerity</b><br/><b>Dying Wish</b>: Summon six Wraithlings on random spaces.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 329,
    name: 'Arcane Devourer',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'epic',
    faction: 'abyssian',
    text:
      '<b>Opening Gambit</b>: The next minion you summon this turn costs 1.',
    attack: 8,
    health: 4,
    spirit: null
  },
  {
    id: 347,
    name: 'Stygian Observer',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'abyssian',
    text: '<b>Deathwatch</b>: Give minions in your action bar +2/+2.',
    attack: 7,
    health: 7,
    spirit: null
  },
  {
    id: 338,
    name: 'Death Knell',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 8,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Opening Gambit</b>: Summon all friendly non-token Arcanysts destroyed this game nearby.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 333,
    name: 'Grandmaster Variax',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Opening Gambit</b>: Your Bloodbound Spell costs 3 and is now AWESOME.',
    attack: 8,
    health: 8,
    spirit: null
  },
  {
    id: 20213,
    name: 'Obliterate',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      'Destroy all friendly <b>Shadow Creep</b> to deal that much damage to all enemies.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 320,
    name: 'Spectral Revenant',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      '<b>Rush</b><br/>Whenever this damages an enemy minion, deal 4 damage to the enemy General.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 20380,
    name: 'Unleash the Evil',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'abyssian',
    text:
      'Summon a copy of the minion your opponent most recently summoned from their action bar. It gains <b>Rush</b> and <b>Flying</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20264,
    name: 'Doom',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 9,
    rarity: 'legendary',
    faction: 'abyssian',
    text: 'The enemy General is DOOMED and will die after three turns.',
    attack: null,
    health: null,
    spirit: null
  }
];

export default abyssian;
