/* eslint-disable */
const generals = [{
  "id": 1,
  "name": "Argeon Highmayne",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "lyonar",
  "text": "<b>Bloodbound Spell:</b> Give a friendly minion nearby your General +2 Attack.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 323,
  "name": "Cassyva Soulreaper",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "abyssian",
  "text": "<b>Bloodbound Spell:</b> Deal 1 damage to a minion. If it dies this turn, the space turns into Shadow Creep.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 501,
  "name": "Faie Bloodwing",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "vanar",
  "text": "<b>Bloodbound Spell:</b> Deal 2 damage to all enemies in the enemy General's Column.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 101,
  "name": "Kaleos Xaan",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "songhai",
  "text": "<b>Bloodbound Spell:</b> Teleport a friendly minion up to 2 spaces.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 527,
  "name": "Kara Winterblade",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "vanar",
  "text": "<b>Bloodbound Spell:</b> Friendly minions summoned this turn gain +1/+1.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 301,
  "name": "Lilithe Blightchaser",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "abyssian",
  "text": "<b>Bloodbound Spell:</b> Summon 2 Wraithlings nearby your General.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 123,
  "name": "Reva Eventide",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "songhai",
  "text": "<b>Bloodbound Spell:</b> Summon a Heartseeker nearby your General.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 223,
  "name": "Scioness Sajj",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "vetruvian",
  "text": "<b>Bloodbound Spell:</b> Your General deals double damage to minions this turn.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 418,
  "name": "Starhorn the Seeker",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "magmar",
  "text": "<b>Bloodbound Spell:</b> Both players draw a card.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 401,
  "name": "Vaath the Immortal",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "magmar",
  "text": "<b>Bloodbound Spell:</b> Give your General +1 Attack.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 23,
  "name": "Zir'An Sunforge",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "lyonar",
  "text": "<b>Bloodbound Spell:</b> Restore 3 Health to any Minion.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}, {
  "id": 201,
  "name": "Zirix Starstrider",
  "set": "core",
  "type": "general",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "vetruvian",
  "text": "<b>Bloodbound Spell:</b> Summon a 2/2 Iron Dervish on a random space nearby your General.",
  "attack": 2,
  "health": 25,
  "spirit": 0
}];

export default generals
