const lyonar = [
  { name: 'Beam Shock', type: 'spell', cost: 0, rarity: 'common', faction: 'lyonar', text: 'Stun an enemy minion or General.' },
  { name: 'Slo', type: 'battle pet', cost: 0, rarity: 'common', attack: 1, health: 4, faction: 'lyonar', text: 'Provoke' },
  { name: 'Sunstone Bracers', type: 'artifact', cost: 0, rarity: 'core', faction: 'lyonar', text: 'Your General gains +1 Attack.' },
  { name: 'Aegis Barrier', type: 'spell', cost: 1, rarity: 'legendary', faction: 'lyonar', text: 'Choose a friendly minion. It can\'t be targeted by enemy spells. Draw a card.' },
  { name: 'Aerial Rift', type: 'spell', cost: 1, rarity: 'rare', faction: 'lyonar', text: 'Give your minions Airdrop this turn. Draw a card.' },
  { name: 'Auryn Nexus', type: 'spell', cost: 1, rarity: 'common', faction: 'lyonar', text: 'Give a friendly minion +3 Health' },
  { name: 'Fighting Spirit', type: 'spell', cost: 1, rarity: 'epic', faction: 'lyonar', text: 'Give all friendly minions +1 Health. Put a random Battle Pet into your action bar.' },
  { name: 'Lionheart Blessing', type: 'spell', cost: 1, rarity: 'rare', faction: 'lyonar', text: 'Give a friendly minion, "Zeal: Whenever this minion deals damage, draw a card."' },
  { name: 'Magnetize', type: 'spell', cost: 1, rarity: 'rare', faction: 'lyonar', text: 'Pull ANY minion to the space in front of your General.' },
  { name: 'Silverguard Squire', type: 'minion', cost: 1, rarity: 'common', faction: 'lyonar', text: '' },
  { name: 'Sundrop Elixer', type: 'spell', cost: 1, rarity: 'common', faction: 'lyonar', text: 'Restore 5 Health to a minion or General.' },
  { name: 'True Strike', type: 'spell', cost: 1, rarity: 'core', faction: 'lyonar', text: 'Deal 2 damage to a minion.' },
  { name: 'Azurite Lion', type: 'minion', cost: 2, rarity: 'common', faction: 'lyonar', text: 'Celerity' },
  { name: 'Fiz', type: 'battle pet', cost: 2, rarity: 'rare', faction: 'lyonar', text: 'Opening Gambit: Restore 2 Health to a minion or General.' },
  { name: 'Lasting Judgement', type: 'spell', cost: 2, rarity: 'rare', faction: 'lyonar', text: 'Give ANY minion +3 Attack, but -3 Health.' },
  { name: 'Lightchaser', type: 'minion', cost: 2, rarity: 'common', attack: 3, health: 2, faction: 'lyonar', text: 'Whenever ANY minion or General is healed, this minion gains +1/+1' },
  { name: 'Lucent Beam', type: 'spell', cost: 2, rarity: 'common', faction: 'lyonar', text: 'Deal 2 damage to an enemy. If a minion or General was healed this turn, deal 4 damage instead.' },
  { name: 'Sun Bloom', type: 'spell', cost: 2, rarity: 'common', faction: 'lyonar', text: 'Dispel a 2x2 area on the battlefield.' },
  { name: 'Sun Wisp', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 1, faction: 'lyonar', text: 'Opening Gambit: Draw a card.' },
  { name: 'Sunstone Templar', type: 'minion', cost: 2, rarity: 'epic', attack: 1, health: 4, faction: 'lyonar', text: 'Whenever this attacks or counterattacks, it dispels that enemy.' },
  { name: 'Tempest', type: 'spell', cost: 2, rarity: 'core', faction: 'lyonar', text: 'Deal 2 damage to ALL minions and Generals.' },
  { name: 'War Surge', type: 'spell', cost: 2, rarity: 'core', faction: 'lyonar', text: 'Give all friendly minions +1/+1' },
  { name: 'Windblade Adept', type: 'minon', cost: 2, rarity: 'core', attack: 2, health: 3, faction: 'lyonar', text: 'Zeal: Gain +2 Attack.' },
  { name: 'Afterblaze', type: 'spell', cost: 3, rarity: 'common', faction: 'lyonar', text: 'Give a friendly minion +2/+4. If that minion has Zeal, draw a card.' },
  { name: 'Arclyte Sentinel', type: 'minion', cost: 3, rarity: 'rare', attack: 2, health: 4, faction: 'lyonar', text: 'Opening Gambit: Give ANY nearby minion +2 Attack, but -2 Health.' },
  { name: 'Divine Bond', type: 'spell', cost: 3, rarity: 'core', faction: 'lyonar', text: 'Give a minion +Attack equal to its Health.' },
  { name: 'Martyrdom', type: 'spell', cost: 3, rarity: 'core', faction: 'lyonar', text: 'Destroy ANY minion. Restore that minion\'s Health to its General' },
  { name: 'Radiant Dragoon', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 4, faction: 'lyonar', text: 'At the end of your turn, give a friendly minion +1 Health.' },
  { name: 'Silverguard Knight', type: 'minion', cost: 3, rarity: 'core', attack: 1, health: 5, faction: 'lyonar', text: 'Provoke Zeal: Grains +2 Attack.' },
  { name: 'Sky Burial', type: 'spell', cost: 3, rarity: 'rare', faction: 'lyonar', text: 'Destroy a minion that is not nearby any General.' },
  { name: 'Skywind Glaives', type: 'artifact', cost: 3, rarity: 'epic', faction: 'lyonar', text: 'Friendly minions nearby your General gain +2 Attack.' },
  { name: 'Sunforge Lancer', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 4, faction: 'lyonar', text: 'Whenever ANY minion or General is healed, give your General +1 Attack.' },
  { name: 'Arclyte Regalia', type: 'artifact', cost: 4, rarity: 'legendary', faction: 'lyonar', text: 'Your General gains +2 Attack. The first time your General takes damage each turn, prevent 2 of it.' },
  { name: 'Decimate', type: 'spell', cost: 4, rarity: 'legendary', faction: 'lyonar', text: 'Destroy ALL minions that are not nearby any General.' },
  { name: 'Holy Immolation', type: 'spell', cost: 4, rarity: 'epic', faction: 'lyonar', text: 'Restore 4 Health to a friendly minon. Deal 4 damage to enemy minions and Generals around it.' },
  { name: 'Ironcliffe Heart', type: 'spell', cost: 4, rarity: 'ecpi', faction: 'lyonar', text: 'Transform a friendly minion into an Ironcliffe Guardian' },
  { name: 'Lysian Brawler', type: 'minion', cost: 4, rarity: 'core', attack: 4, health: 4, faction: 'lyonar', text: 'Celerity' },
  { name: 'Sun Sister Sterope', type: 'minion', cost: 4, rarity: 'legendary', attack: 4, health: 4, faction: 'lyonar', text: 'Whenever ANY minion or General is healed, put a True Strike into your action bar.' },
  { name: 'Sunriser', type: 'minion', cost: 4, rarity: 'epic', attack: 3, health: 4, faction: 'lyonar', text: 'Whenever ANY minion or General is healed, deal 2 damage to all nearby enemies.' },
  { name: 'Suntide Maiden', type: 'minion', cost: 4, rarity: 'common', attack: 3, health: 6, faction: 'lyonar', text: 'Zeal: At the end of your turn, restore this minion to full Health.' },
  { name: 'Circle of Life', type: 'spell', cost: 5, rarity: 'epic', faction: 'lyonar', text: 'Deal 5 damage to any enemy minion. Restore 5 Health to your General.' },
  { name: 'Ironcliffe Guardian', type: 'minion', cost: 5, rarity: 'rare', attack: 3, Health: 10, faction: 'lyonar', text: 'Airdrop, Provoke' },
  { name: 'Second Sun', type: 'minion', cost: 5, rarity: 'rare', attack: 0, health: 8, faction: 'lyonar', text: 'Zeal: Gains +8 Attack.' },
  { name: 'Dawn\'s Eye', type: 'artifact', cost: 6, rarity: 'legendary', faction: 'lyonar', text: 'Your General gains +4 Attack. At the end of your turn, repair all of your artifacts to full durability.' },
  { name: 'Elyx Stormblade', type: 'minion', cost: 6, rarity: 'legendary', attack: 7, health: 7, faction: 'lyonar', text: 'Provoke Your minions and General may move an additional space.' },
  { name: 'Solarius', type: 'minion', cost: 6, rarity: 'legendary', attack: 3, health: 3, faction: 'lyonar', text: 'Zeal: Draw 2 additional cards at the end of your turn.' },
  { name: 'Grandmaster Z\'ir', type: 'minion', cost: 7, rarity: 'legendary', attack: 5, health: 12, faction: 'lyonar', text: 'Whenever your General dies, Grandmaster Z\'ir becomes your General.' },
  { name: 'Sky Phalanx', type: 'spell', cost: 8, rarity: 'legendary', faction: 'lyonar', text: 'Summon three Silverguard Knights nearby your General.' },
]

export default lyonar
