const lyonar = [
  {
    id: 20109,
    name: 'Beam Shock',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'common',
    faction: 'lyonar',
    text: '<b>Stun</b> an enemy.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20316,
    name: 'Steadfast Formation',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'common',
    faction: 'lyonar',
    text: 'Give friendly minions in a 2x2 area <b>Provoke</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30004,
    name: 'Sunstone Bracers',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 0,
    rarity: 'basic',
    faction: 'lyonar',
    text: 'Your General gains +1 Attack.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20120,
    name: 'Aegis Barrier',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      "Choose a friendly minion. It can't be targeted by enemy spells. Draw a card.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20158,
    name: 'Aerial Rift',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Give your minions <b>Airdrop</b> this turn.  Draw a card.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20045,
    name: 'Auryn Nexus',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'lyonar',
    text: 'Give a friendly minion +3 Health.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20233,
    name: 'Draining Wave',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'lyonar',
    text: 'Deal 4 damage to a minion AND your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20189,
    name: 'Fighting Spirit',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      'Give all friendly minions +1 Health. Put a random Battle Pet into your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20287,
    name: 'Fortified Assault',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'lyonar',
    text:
      "Turn an enemy minion's space into <b>Hallowed Ground</b>. Deal it 1 damage for each friendly <b>Hallowed Ground</b>.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20361,
    name: 'Lifestream',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'lyonar',
    text:
      'Fully heal a friendly minion, then draw a copy of it from your deck.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20062,
    name: 'Lionheart Blessing',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'lyonar',
    text:
      'Give a friendly minion, "Zeal: Whenever this minion deals damage, draw a card."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20161,
    name: 'Magnetize',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'Pull ANY minion to the space in front of your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20280,
    name: 'Sanctify',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'lyonar',
    text:
      'Give a friendly minion +1/+1 and turn its space into <b>Hallowed Ground</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 14,
    name: 'Silverguard Squire',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'lyonar',
    text: '',
    attack: 1,
    health: 4,
    spirit: null
  },
  {
    id: 26,
    name: 'Slo',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 1,
    rarity: 'common',
    faction: 'lyonar',
    text: '<b>Provoke</b>',
    attack: 1,
    health: 4,
    spirit: null
  },
  {
    id: 20043,
    name: 'Sundrop Elixir',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'lyonar',
    text: 'Restore 5 Health to anything.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 38,
    name: 'Sunrise Cleric',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'lyonar',
    text:
      '<b>Opening Gambit</b>: Turn a nearby space into <b>Hallowed Ground</b>.',
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 20066,
    name: 'True Strike',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'basic',
    faction: 'lyonar',
    text: 'Deal 2 damage to a minion.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 21,
    name: 'Azurite Lion',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text: '<b>Celerity</b>',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 20315,
    name: 'Bolster',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text: '<b>Intensify</b>: Give friendly minions +2 Health.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20281,
    name: 'Channeled Breath',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text: 'Restore 2 Health to your General for each friendly minion.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20332,
    name: 'Dauntless Advance',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text:
      'Your General and nearby friendly minions gain, "Takes no damage this turn."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 25,
    name: 'Fiz',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 2,
    rarity: 'rare',
    faction: 'lyonar',
    text: '<b>Opening Gambit</b>: Restore 2 Health to anything.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 30026,
    name: 'Gold Vitriol',
    set: 'ancients',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'Whenever anything is healed, deal 2 damage to a random enemy.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20046,
    name: 'Lasting Judgement',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'Give ANY minion +3 Attack, but -3 Health.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 15,
    name: 'Lightchaser',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text: 'Whenever anything is healed, this minion gains +1/+1.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 20190,
    name: 'Lucent Beam',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text:
      'Deal 2 damage to an enemy. If anything was healed this turn, deal 4 damage instead.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20366,
    name: 'Marching Orders',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'lyonar',
    text:
      'Give friendly minions directly in front of and behind your General +2/+2.  If they have <b>Zeal</b>, they cannot be targeted by enemy spells.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20235,
    name: 'Prism Barrier',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'Give a friendly minion <b>Forcefield</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 37,
    name: 'Pureblade Enforcer',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text: 'Whenever your opponent casts a spell, this minion gains +1/+1.',
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 20064,
    name: 'Sun Bloom',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text: 'Dispel a 2x2 area.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 27,
    name: 'Sun Wisp',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text: '<b>Opening Gambit</b>: Draw a card.',
    attack: 2,
    health: 1,
    spirit: null
  },
  {
    id: 30048,
    name: 'Sunbond Pavise',
    set: 'immortal',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'lyonar',
    text:
      'Friendly minions directly above and below your General gain +2 Attack and <b>Provoke</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 10,
    name: 'Sunstone Templar',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Whenever this attacks or counterattacks, it dispels that enemy',
    attack: 1,
    health: 4,
    spirit: null
  },
  {
    id: 20044,
    name: 'Tempest',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'lyonar',
    text: 'Deal 2 damage to everything.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20285,
    name: 'Vale Ascension',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      'Summon a friendly non-token minion destroyed this game onto friendly <b>Hallowed Ground</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20047,
    name: 'War Surge',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'lyonar',
    text: 'Give all friendly minions +1/+1.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 34,
    name: 'Warblade',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 2,
    rarity: 'common',
    faction: 'lyonar',
    text: '<b>Bond</b>: Other friendly minions gain +1/+1.',
    attack: 1,
    health: 4,
    spirit: null
  },
  {
    id: 9,
    name: 'Windblade Adept',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'lyonar',
    text: '<b>Zeal</b>: Gains +1 Attack',
    attack: 2,
    health: 3,
    spirit: 0
  },
  {
    id: 20188,
    name: 'Afterblaze',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'lyonar',
    text:
      'Give a friendly minion +2/+4. If that minion has <b>Zeal</b>, draw a card.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 12,
    name: 'Arclyte Sentinel',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'lyonar',
    text:
      '<b>Opening Gambit</b>: Give ANY nearby minion +2 Attack, but -2 Health',
    attack: 2,
    health: 4,
    spirit: null
  },
  {
    id: 40,
    name: 'Auroara',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      'Whenever you summon a minion with 2 or less Attack, this minion gains +2 Attack.',
    attack: 1,
    health: 5,
    spirit: null
  },
  {
    id: 50,
    name: 'Decorated Enlistee',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'lyonar',
    text: 'While at full Health, this minion has +3 Attack.',
    attack: 1,
    health: 5,
    spirit: null
  },
  {
    id: 20068,
    name: 'Divine Bond',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'lyonar',
    text: 'Give a minion +Attack equal to its Health.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20274,
    name: 'Empyreal Congregation',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Give friendly minions in a 2x2 area +2/+2.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20317,
    name: 'Fealty',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'Draw a card for each friendly minion nearby your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 54,
    name: 'Gryphon Fledgling',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'lyonar',
    text: '<b>Zeal</b>: <b>Flying</b>',
    attack: 5,
    health: 3,
    spirit: null
  },
  {
    id: 53,
    name: 'Legion',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'lyonar',
    text:
      '<b>Intensify</b>: Put 1 Crestfallen into your action bar. Shuffle a copy of this minion into your deck.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 20249,
    name: 'Life Coil',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'lyonar',
    text: "Double a minion's Health.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20090,
    name: 'Martyrdom',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'lyonar',
    text: "Destroy ANY minion. Restore that minion's Health to its General.",
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 28,
    name: 'Radiant Dragoon',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'At the end of your turn, give a friendly minion +1 Health.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 32,
    name: 'Scintilla',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'lyonar',
    text: '<b>Blood Surge</b>: Restore 3 Health to your General.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 11,
    name: 'Silverguard Knight',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'lyonar',
    text: '<b>Provoke</b><br/><b>Zeal</b>: Gains +2 Attack',
    attack: 1,
    health: 5,
    spirit: 0
  },
  {
    id: 20187,
    name: 'Sky Burial',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'Destroy a minion that is not nearby any General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30001,
    name: 'Skywind Glaives',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Friendly minions nearby your General gain +2 Attack.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 35,
    name: 'Sol Pontiff',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 3,
    rarity: 'epic',
    faction: 'lyonar',
    text: '<b>Zeal</b>: Your Golems have +2 Attack.',
    attack: 1,
    health: 4,
    spirit: null
  },
  {
    id: 29,
    name: 'Sunforge Lancer',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Whenever anything is healed, give your General +1 Attack.',
    attack: 2,
    health: 4,
    spirit: null
  },
  {
    id: 48,
    name: 'Surgeforger',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      'Whenever you summon a minion nearby this minion, give them both +1/+1.',
    attack: 2,
    health: 2,
    spirit: null
  },
  {
    id: 47,
    name: 'Vigilator',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'lyonar',
    text:
      '<b>Build</b>: (1).<br/>When this minion is built, give nearby friendly minions +3 Health.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 30018,
    name: 'Arclyte Regalia',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      'Your General gains +2 Attack. The first time your General takes damage each turn, prevent 2 of it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20128,
    name: 'Decimate',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'lyonar',
    text: 'Destroy ALL minions that are not nearby any General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20067,
    name: 'Holy Immolation',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      'Restore 4 Health to a friendly minion. Deal 4 damage to enemies around it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20325,
    name: 'Invincible',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Give a friendly minion with full Health +4/+4.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20186,
    name: 'Ironcliffe Heart',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Transform a friendly minion into an Ironcliffe Guardian.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 49,
    name: 'Ironcliffe Monument',
    set: 'immortal',
    type: 'minion',
    race: 'Structure',
    cost: 4,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      '<b>Build</b>: (2).<br/>Whenever you summon a minion nearby this, transform that minion into an Ironcliffe Guardian.',
    attack: 0,
    health: 10,
    spirit: null
  },
  {
    id: 8,
    name: 'Lysian Brawler',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'basic',
    faction: 'lyonar',
    text: '<b>Celerity</b>',
    attack: 4,
    health: 4,
    spirit: 0
  },
  {
    id: 39,
    name: 'Solpiercer',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'lyonar',
    text: '<b>Zeal</b>: <b>Ranged</b>',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 24,
    name: 'Sun Sister Sterope',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      'Whenever anything is healed, put a True Strike into your action bar.',
    attack: 4,
    health: 4,
    spirit: 0
  },
  {
    id: 31,
    name: 'Sunbreaker',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'lyonar',
    text: '<b>Forcefield</b>. Your Bloodbound Spell is Tempest.',
    attack: 2,
    health: 4,
    spirit: null
  },
  {
    id: 22,
    name: 'Sunriser',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Whenever anything is healed, deal 2 damage to all nearby enemies.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 20320,
    name: 'Sunstrike',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      'Deal 3 damage to enemies and restore 3 Health to friendly minions and Generals in a row.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 16,
    name: 'Suntide Maiden',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'lyonar',
    text: '<b>Zeal</b>: At the end of your turn, fully heal this minion.',
    attack: 3,
    health: 6,
    spirit: null
  },
  {
    id: 20232,
    name: 'Trinity Oath',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Draw 3 cards and restore 3 Health to your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 41,
    name: 'War Judicator',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'Nearby friendly minions cannot be targeted by enemy spells.',
    attack: 4,
    health: 5,
    spirit: null
  },
  {
    id: 56,
    name: 'Windcliffe Alarmist',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'lyonar',
    text:
      '<b>Opening Gambit</b>: Summon a 5/5 Windcliffe Protector with <b>Provoke</b> from your deck.',
    attack: 2,
    health: 2,
    spirit: null
  },
  {
    id: 20104,
    name: 'Circle of Life',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'lyonar',
    text: 'Deal 5 damage to an enemy minion. Restore 5 Health to your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 57,
    name: 'Grand Strategos',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'mythron',
    faction: 'lyonar',
    text:
      '<b>Trial</b>: Summon 10 minions with 1 or less Attack.<br/><b>Destiny</b>: Promote other friendly minions at the end of your turn.',
    attack: 5,
    health: 5,
    spirit: null
  },
  {
    id: 30032,
    name: 'Halo Bulwark',
    set: 'unearthed',
    type: 'artifact',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'lyonar',
    text: 'Friendly minions nearby your General have <b>Forcefield</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 17,
    name: 'Ironcliffe Guardian',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'lyonar',
    text: '<b>Airdrop</b><br/><b>Provoke</b>',
    attack: 3,
    health: 10,
    spirit: null
  },
  {
    id: 20384,
    name: 'Lionize',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      'Give <b>Celerity</b> to a friendly minion directly behind your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 44,
    name: 'Oakenheart',
    set: 'immortal',
    type: 'minion',
    race: 'Mech',
    cost: 5,
    rarity: 'rare',
    faction: 'lyonar',
    text:
      '<b>Opening Gambit</b>: Progresses MECHAZ0R build by +20%.<br/>Your other Mech minions have +1/+1.',
    attack: 4,
    health: 5,
    spirit: null
  },
  {
    id: 13,
    name: 'Second Sun',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'lyonar',
    text: '<b>Zeal</b>: Gains +8 Attack',
    attack: 0,
    health: 8,
    spirit: null
  },
  {
    id: 59,
    name: 'War Exorcist',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      '<b>Provoke</b><br/>At the start of your turn, Holy Immolation your damaged minions.',
    attack: 3,
    health: 8,
    spirit: null
  },
  {
    id: 55,
    name: 'Windcliffe Protector',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      '<b>Provoke</b><br/>When a friendly Windcliffe Alarmist dies, transform this minion into a Windcliffe Alarmist.',
    attack: 5,
    health: 5,
    spirit: null
  },
  {
    id: 30024,
    name: "Dawn's Eye",
    set: 'shimzar',
    type: 'artifact',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      'Your General gains +4 Attack. At the end of your turn, repair all of your artifacts to full durability.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20360,
    name: 'Divine Liturgy',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'rare',
    faction: 'lyonar',
    text: 'Give all friendly minions +Attack equal to their Health.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 18,
    name: 'Elyx Stormblade',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      '<b>Provoke</b><br/>Your minions and General may move an additional space',
    attack: 7,
    health: 7,
    spirit: null
  },
  {
    id: 45,
    name: 'Prominence',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      '<b>Blood Surge</b>: Summon a Silverguard Knight nearby your General.',
    attack: 4,
    health: 7,
    spirit: null
  },
  {
    id: 30053,
    name: 'Radiant Standard',
    set: 'mythron',
    type: 'artifact',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'lyonar',
    text:
      'Your General has +3 Attack.<br/>When your General attacks, summon a minion that costs 3 from your deck nearby.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30,
    name: 'Solarius',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'lyonar',
    text: '<b>Zeal</b>: Draw 2 additional cards at the end of your turn.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 42,
    name: 'Alabaster Titan',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      '<b>Opening Gambit</b>: If you have no spells in your deck, equip a full set of equipment.',
    attack: 5,
    health: 7,
    spirit: null
  },
  {
    id: 20282,
    name: "Aperion's Claim",
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      'Destroy ALL minions in a 3x3 area and turn their spaces into <b>Hallowed Ground</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20318,
    name: 'Call to Arms',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'lyonar',
    text: 'Your General gains, "Minions you summon nearby gain +3/+3."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20,
    name: "Grandmaster Z'ir",
    set: 'core',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'lyonar',
    text: "When your General dies, Grandmaster Z'ir becomes your General.",
    attack: 5,
    health: 12,
    spirit: null
  },
  {
    id: 58,
    name: 'Indominus',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'lyonar',
    text: 'Your General is <b>Invulnerable</b> BUT cannot move or attack.',
    attack: 7,
    health: 9,
    spirit: null
  },
  {
    id: 36,
    name: 'Peacekeeper',
    set: 'ancients',
    type: 'minion',
    race: 'Golem',
    cost: 7,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      '<b>Airdrop</b>, <b>Forcefield</b>, <b>Frenzy</b>, <b>Provoke</b>, <b>Celerity</b>',
    attack: 5,
    health: 5,
    spirit: null
  },
  {
    id: 33,
    name: 'Excelsious',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      '<b>Provoke</b><br/><b>Celerity</b><br/>This minion gains +1/+1 for each time you healed anything this game.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 20220,
    name: 'Sky Phalanx',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'lyonar',
    text: 'Summon three Silverguard Knights nearby your General.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20392,
    name: 'Amaranthine Vow',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 9,
    rarity: 'legendary',
    faction: 'lyonar',
    text:
      'Summon around your General all friendly minions with <b>Provoke</b> that died this game.',
    attack: null,
    health: null,
    spirit: null
  }
];

export default lyonar;
