const magmar = [{
  "id": 20111,
  "name": "Dampening Wave",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "magmar",
  "text": "Choose an enemy minion. It can no longer counterattack.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20112,
  "name": "Flash Reincarnation",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 0,
  "rarity": "rare",
  "faction": "magmar",
  "text": "The next minion you summon this turn costs 2 less and takes 2 damage.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20119,
  "name": "Amplification",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "common",
  "faction": "magmar",
  "text": "Give a friendly damaged minion +2 Attack and +4 Health.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20115,
  "name": "Dance of Dreams",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "basic",
  "faction": "magmar",
  "text": "Whenever a friendly minion dies this turn, draw a card.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 30028,
  "name": "Godhammer",
  "set": "ancient bonds",
  "type": "artifact",
  "race": "",
  "cost": 1,
  "rarity": "rare",
  "faction": "magmar",
  "text": "Your minions have \"Grow: +1/+1.\"",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20116,
  "name": "Greater Fortitude",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "basic",
  "faction": "magmar",
  "text": "Give a friendly minion +2/+2.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20203,
  "name": "Lava Lance",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "common",
  "faction": "magmar",
  "text": " Deal 2 damage to a minion. If you have an Egg, deal 4 damage instead.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20202,
  "name": "Razor Skin",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "common",
  "faction": "magmar",
  "text": "Give all friendly minions +1 Attack. Put a random Battle Pet into your action bar.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 421,
  "name": "Rex",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 1,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Rebirth</b>",
  "attack": 3,
  "health": 1,
  "spirit": null
}, {
  "id": 20258,
  "name": "Cascading Rebirth",
  "set": "ancient bonds",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "magmar",
  "text": "Destroy a friendly minion to summon a random Magmar minion that costs 1 more.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20113,
  "name": "Diretide Frenzy",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "magmar",
  "text": "Give a friendly minion +1 Attack and <b>Frenzy</b>.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20225,
  "name": "Entropic Gaze",
  "set": "bloodborn",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "magmar",
  "text": "Deal 2 damage to the enemy General. Both players draw a card.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 420,
  "name": "Gro",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 2,
  "rarity": "rare",
  "faction": "magmar",
  "text": "<b>Grow</b>: +1/+1.",
  "attack": 2,
  "health": 4,
  "spirit": null
}, {
  "id": 30013,
  "name": "Iridium Scale",
  "set": "core",
  "type": "artifact",
  "race": "",
  "cost": 2,
  "rarity": "epic",
  "faction": "magmar",
  "text": "Your General gains <b>Frenzy</b>.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 409,
  "name": "Kujata",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "epic",
  "faction": "magmar",
  "text": "Your minions cost 1 less to summon and take 1 damage when summoned from your action bar.",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 20125,
  "name": "Natural Selection",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "magmar",
  "text": "Destroy ANY minion with the lowest Attack or tied for the lowest Attack.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 406,
  "name": "Phalanxar",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "magmar",
  "text": "",
  "attack": 6,
  "health": 1,
  "spirit": 0
}, {
  "id": 430,
  "name": "Rancour",
  "set": "bloodborn",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "rare",
  "faction": "magmar",
  "text": "Whenever your General takes damage, this minion gains that much Attack.",
  "attack": 1,
  "health": 3,
  "spirit": 0
}, {
  "id": 20114,
  "name": "Tremor",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Stun</b> enemy minions in a 2x2 area.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 412,
  "name": "Young Silithar",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Rebirth</b>",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 402,
  "name": "Earth Walker",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "basic",
  "faction": "magmar",
  "text": "<b>Grow</b>: +1/+1.",
  "attack": 3,
  "health": 3,
  "spirit": 0
}, {
  "id": 20162,
  "name": "Kinetic Equilibrium",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "magmar",
  "text": "Deal 2 damage to ALL minions in a 3x3 area. Friendly minions in the area also gain +2 Attack.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 423,
  "name": "Moloki Huntress",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "epic",
  "faction": "magmar",
  "text": "<b>Grow</b>: +1/+1.<br>Friendly minions grow at the start of BOTH player's turns.",
  "attack": 1,
  "health": 2,
  "spirit": null
}, {
  "id": 410,
  "name": "Primordial Gazer",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "basic",
  "faction": "magmar",
  "text": "<b>Opening Gambit</b>: Give a nearby friendly minion +2/+2.",
  "attack": 2,
  "health": 2,
  "spirit": 0
}, {
  "id": 432,
  "name": "Ragebinder",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Golem",
  "cost": 3,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Rebirth</b><br/><b>Bond</b>: Restore 3 Health to your General.",
  "attack": 3,
  "health": 4,
  "spirit": 0
}, {
  "id": 20234,
  "name": "Tectonic Spikes",
  "set": "bloodborn",
  "type": "spell",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "magmar",
  "text": "Both players draw 3 cards. Deal 3 damage to both Generals.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 429,
  "name": "Thraex",
  "set": "bloodborn",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Blood Surge</b>: All friendly minions gain +1 Attack (including itself).",
  "attack": 2,
  "health": 4,
  "spirit": 0
}, {
  "id": 20218,
  "name": "Thumping Wave",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "magmar",
  "text": "Give a minion +5 Attack. At end of turn, transform it into a 3/3 Kin.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 30017,
  "name": "Twin Fang",
  "set": "core",
  "type": "artifact",
  "race": "",
  "cost": 3,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "Whenever a friendly minion or your General takes damage, your General gains +2 Attack.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 417,
  "name": "Vindicator",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "Whenever your opponent draws a card, this minion gains +2/+2.",
  "attack": 1,
  "health": 3,
  "spirit": null
}, {
  "id": 30012,
  "name": "Adamantite Claws",
  "set": "core",
  "type": "artifact",
  "race": "",
  "cost": 4,
  "rarity": "basic",
  "faction": "magmar",
  "text": "Your General gains +4 Attack.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20124,
  "name": "Chrysalis Burst",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "Summon a random Egg in 4 random spaces.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 428,
  "name": "Drogon",
  "set": "bloodborn",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "<b>Blood Surge</b>: Double your General's Attack this turn.",
  "attack": 5,
  "health": 4,
  "spirit": 0
}, {
  "id": 419,
  "name": "Earth Sister Taygete",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "Whenever this minion takes damage, deal that much damage to all nearby enemies.",
  "attack": 3,
  "health": 4,
  "spirit": 0
}, {
  "id": 20117,
  "name": "Earth Sphere",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "magmar",
  "text": "Restore 8 Health to your General.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20157,
  "name": "Egg Morph",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "magmar",
  "text": "Turn a non-Egg minion into an Egg, or hatch an Egg.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 407,
  "name": "Elucidator",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "magmar",
  "text": "<b>Rush</b><br><b>Opening Gambit</b>: Deal 4 damage to your General.",
  "attack": 5,
  "health": 4,
  "spirit": null
}, {
  "id": 403,
  "name": "Grimrock",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Grow</b>: +2/+2.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 20156,
  "name": "Mind Steal",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "magmar",
  "text": "Steal a random minion from your opponent's deck and summon it.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20245,
  "name": "Valknu's Seal",
  "set": "bloodborn",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "magmar",
  "text": "Summon an Egg that hatches into a copy of your General.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 413,
  "name": "Veteran Silithar",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Rebirth</b>",
  "attack": 4,
  "health": 3,
  "spirit": null
}, {
  "id": 422,
  "name": "Wild Inceptor",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Opening Gambit</b>: Hatch a friendly Egg.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 404,
  "name": "Kolossus",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "common",
  "faction": "magmar",
  "text": "<b>Grow</b>: +4/+4.",
  "attack": 1,
  "health": 7,
  "spirit": null
}, {
  "id": 433,
  "name": "Lavaslasher",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Golem",
  "cost": 5,
  "rarity": "epic",
  "faction": "magmar",
  "text": "<b>Opening Gambit</b>: This minion fights a nearby enemy minion.",
  "attack": 4,
  "health": 9,
  "spirit": 0
}, {
  "id": 30025,
  "name": "Morin-Khur",
  "set": "shimzar",
  "type": "artifact",
  "race": "",
  "cost": 5,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "Your General gains +3 Attack. Whenever your General deals damage, hatch all friendly Eggs.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20206,
  "name": "Nature's Confluence",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "magmar",
  "text": "Summon four copies of a random Battle Pet in a 2x2 area.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20122,
  "name": "Plasma Storm",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 5,
  "rarity": "basic",
  "faction": "magmar",
  "text": "Destroy ALL minions with 3 or less Attack.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 415,
  "name": "Spirit Harvester",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "rare",
  "faction": "magmar",
  "text": "At the end of your turn, deal 1 damage to ALL other minions.",
  "attack": 5,
  "health": 5,
  "spirit": null
}, {
  "id": 426,
  "name": "Visionar",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "magmar",
  "text": "Whenever ANY player draws a card, this minion gains +1/+1.",
  "attack": 6,
  "health": 3,
  "spirit": null
}, {
  "id": 424,
  "name": "Dreadnought",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "<b>Rebirth</b><br>Egg minions you summon gain +2/+2.",
  "attack": 4,
  "health": 6,
  "spirit": null
}, {
  "id": 20063,
  "name": "Fractal Replication",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 6,
  "rarity": "epic",
  "faction": "magmar",
  "text": "Summon two copies of a friendly minion nearby that minion.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 405,
  "name": "Makantor Warbeast",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 6,
  "rarity": "epic",
  "faction": "magmar",
  "text": "<b>Frenzy</b>, <b>Rush</b>",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 20121,
  "name": "Metamorphosis",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 6,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "Transform all enemy minions into 1/1 Magma with no abilities until the end of your opponent's turn.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20118,
  "name": "Bounded Lifeforce",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 7,
  "rarity": "epic",
  "faction": "magmar",
  "text": "Your General becomes 10/10.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 414,
  "name": "Silithar Elder",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "<b>Rebirth</b><br>At the end of your turn, summon a Silithar Elder Egg nearby.",
  "attack": 6,
  "health": 6,
  "spirit": null
}, {
  "id": 408,
  "name": "Unstable Leviathan",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 7,
  "rarity": "rare",
  "faction": "magmar",
  "text": "At the start of your turn, deal 4 damage to a random minion or General.",
  "attack": 11,
  "health": 11,
  "spirit": null
}, {
  "id": 20219,
  "name": "Flaming Stampede",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 8,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "Deal 5 damage to ALL non-Egg minions and Generals.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 434,
  "name": "Juggernaut",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Golem",
  "cost": 8,
  "rarity": "legendary",
  "faction": "magmar",
  "text": "<b>Grow</b>: +5/+5<br/>Whenever this minion takes damage, summon that many random Golem eggs nearby.",
  "attack": 4,
  "health": 10,
  "spirit": 0
}, {
  "id": 425,
  "name": "Mandrake",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 12,
  "rarity": "rare",
  "faction": "magmar",
  "text": "Costs 1 less for each minion summoned from ANY player's action bar this game.",
  "attack": 6,
  "health": 6,
  "spirit": null
}];

export default magmar
