const neutral = [
  { name: 'Bloodtear Alchemist', type: 'minion', cost: 1, rarity: 'core', attack: 2, health: 1, faction: 'neutral', text: 'Opening Gambit: Deal 1 damage to an enemy minion or General.' },
  { name: 'Dragonlark', type: 'minion', cost: 1, rarity: 'core', attack: 2, health: 1, faction: 'neutral', text: 'Flying' },
  { name: 'Dreamgazer', type: 'minion', cost: 1, rarity: 'epic', attack: 1, health: 1, faction: 'neutral', text: 'When you replace this card, summon it nearby. Your General takes 2 damage.' },
  { name: 'Helm of Mechazor', type: 'mech', cost: 1, rarity: 'common', attack: 2, health: 2, faction: 'neutral', text: 'Opening Gambit: Progresses MECHAZOR build by +20%.' },
  { name: 'Koi', type: 'battle pet', cost: 1, rarity: 'common', attack: 3, health: 1, faction: 'neutral', text: 'Takes no damage from Generals.' },
  { name: 'Komodo Charger', type: 'minion', cost: 1, rarity: 'core', attack: 1, health: 3, faction: 'neutral', text: '' },
  { name: 'Planar Scout', type: 'minion', cost: 1, rarity: 'core', attack: 2, health: 1, faction: 'neutral', text: 'Airdrop' },
  { name: 'Prophet of the White Palm', type: 'minion', cost: 1, rarity: 'rare', attack: 1, health: 1, faction: 'neutral', text: 'Opening Gambit: Prevent ALL spell damage until your next turn.' },
  { name: 'Swamp Entangler', type: 'minion', cost: 1, rarity: 'common', attack: 0, health: 3, faction: 'neutral', text: 'Provoke' },
  { name: 'Aethermaster', type: 'arcanyst', cost: 2, rarity: 'epic', attack: 1, health: 3, faction: 'neutral', text: 'You may replace an additional card each turn.' },
  { name: 'Amu', type: 'battle pet', cost: 2, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: '' },
  { name: 'Araki Headhunter', type: 'minion', cost: 2, rarity: 'epic', attack: 1, health: 3, faction: 'neutral', text: 'Whenever you summon a minion with Opening Gambit from your action bar, gain +2 Attack.' },
  { name: 'Azure Horn Shaman', type: 'minion', cost: 2, rarity: 'rare', attack: 1, health: 4, faction: 'neutral', text: 'Dying Wish: Give +4 Health to friendly minions around it.' },
  { name: 'Bluetip Scorpion', type: 'minion', cost: 2, rarity: 'common', attack: 3, health: 1, faction: 'neutral', text: 'Deals double damage to minions.' },
  { name: 'Ephemeral Shroud', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 2, faction: 'neutral', text: 'Opening Gambit: Dispel 1 nearby space.' },
  { name: 'Flameblood Warlock', type: 'minion', cost: 2, rarity: 'rare', attack: 3, health: 1, faction: 'neutral', text: 'Opening Gambit: Deal 3 damage to BOTH Generals.' },
  { name: 'Ghost Lynx', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 1, faction: 'neutral', text: 'Opening Gambit: Teleport a nearby minion to a random space.' },
  { name: 'Golem Metallurgist', type: 'golem', cost: 2, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: 'The first Golem you summon each turn costs 1 less.' },
  { name: 'Healing Mystic', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 3, faction: 'neutral', text: 'Opening Gambit: Restore 2 Health to a minion or General.' },
  { name: 'Jaxi', type: 'minion', cost: 2, rarity: 'common', attack: 1, health: 1, faction: 'neutral', text: 'Dying Wish: Summon a 1/1 Ranged Mini-Jax in a random unoccupied corner.' },
  { name: 'Manaforger', type: 'arcanyst', cost: 2, rarity: 'rare', attack: 1, health: 3, faction: 'neutral', text: 'The first non-Bloodborn spell you cast each turn costs 1 less.' },
  { name: 'Maw', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 2, faction: 'neutral', text: 'Opening Gambit: Deal 2 damage to a nearby enemy minion.' },
  { name: 'Piercing Mantis', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 2, faction: 'neutral', text: 'Frenzy' },
  { name: 'Primus Fist', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 3, faction: 'neutral', text: 'Opening Gambit: Give a nearby friendly minion +2 Attack this turn.' },
  { name: 'Rock Pulverizer', type: 'minion', cost: 2, rarity: 'core', attack: 1, health: 4, faction: 'neutral', text: 'Provoke' },
  { name: 'Rust Crawler', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 3, faction: 'neutral', text: 'Opening Gambit: Destroy a random enemy artifact.' },
  { name: 'Shiro Puppydragon', type: 'minion', cost: 2, rarity: 'common', attack: 1, health: 4, faction: 'neutral', text: 'At the end of your turn, give each nearby friendly minion +1 Attack.' },
  { name: 'Skyrock Golem', type: 'golem', cost: 2, rarity: 'core', attack: 3, health: 2, faction: 'neutral', text: '' },
  { name: 'Sol', type: 'battle pet', cost: 2, rarity: 'rare', attack: 1, health: 1, faction: 'neutral', text: 'Opening Gambit: Activate a friendly Battle Pet.' },
  { name: 'Vale Hunter', type: 'minion', cost: 2, rarity: 'core', attack: 1, health: 2, faction: 'neutral', text: 'Ranged' },
  { name: 'Wings of Mechazor', type: 'mech', cost: 2, rarity: 'common', attack: 1, health: 4, faction: 'neutral', text: 'Airdrop Opening Gambit: Progresses MECHAZOR build by +20%.' },
  { name: 'Wood-Wen', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 2, faction: 'neutral', text: 'Provoke Opening Gambit: Give a nearby friendly minion Provoke.' },
  { name: 'Z0R', type: 'battle pet', cost: 2, rarity: 'epic', attack: 2, health: 1, faction: 'neutral', text: 'Dying Wish: Put a random MECH minion into your action bar.' },
  { name: 'Abjudicator', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 1, faction: 'neutral', text: 'Opening Gambit: Lower the cost of all spells in your action bar by 1.' },
  { name: 'Alcuin Loremaster', type: 'arcanyst', cost: 3, rarity: 'epic', attack: 3, health: 1, faction: 'neutral', text: 'Opening Gambit: Put a copy of the most recently cast spell into your action bar.' },
  { name: 'Bastion', type: 'structure', cost: 3, rarity: 'epic', attack: 0, health: 5, faction: 'neutral', text: 'At the end of your turn, give other friendly minions +1 Health.' },
  { name: 'Blaze Hound', type: 'minion', cost: 3, rarity: 'common', attack: 4, health: 3, faction: 'neutral', text: 'Opening Gambit: Both players drop a card.' },
  { name: 'Blistering Skorn', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 4, faction: 'neutral', text: 'Opening Gambit: Deal 1 damage to ALL minions and Generals (including itself).' },
  { name: 'Bloodshard Golem', type: 'golem', cost: 3, rarity: 'core', attack: 4, health: 3, faction: 'neutral', text: '' },
  { name: 'Cannon of Mechazor', type: 'mech', cost: 3, rarity: 'rare', attack: 2, health: 2, faction: 'neutral', text: 'Ranged Opening Gambit: Progresses MECHAZOR build by +20%.' },
  { name: 'Chaos Elemental', type: 'minion', cost: 3, rarity: 'epic', attack: 4, health: 4, faction: 'neutral', text: 'Whenever this minion takes damage, it randomly teleports.' },
  { name: 'Crimson Oculus', type: 'minion', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: 'Whenever opponent summons a minion, this minion gains +1/+1.' },
  { name: 'Crossbones', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: 'Opening Gambit: Destroy an enemy minion with Ranged.' },
  { name: 'Elkowl', type: 'minion', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: 'Opening Gambit: Gain two random abilities.' },
  { name: 'Golden Mantella', type: 'minion', cost: 3, rarity: 'common', attack: 4, health: 2, faction: 'neutral', text: 'Opening Gambit: Put a random Battle Pet into your action bar.' },
  { name: 'Golem Vanquisher', type: 'golem', cost: 3, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: 'Provoke Your other Golem minions have Provoke.' },
  { name: 'Hydrax', type: 'minion', cost: 3, rarity: 'legendary', attack: 3, health: 3, faction: 'neutral', text: 'Whenever a friendly Battle Pet dies, draw a card.' },
  { name: 'Ion', type: 'battle pet', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: 'Ranged Deals double damage to Generals.' },
  { name: 'Lady Locke', type: 'minion', cost: 3, rarity: 'legendary', attack: 2, health: 2, faction: 'neutral', text: 'Provoke Opening Gambit: Other minions you summon this turn gain +1/+1 and Provoke.' },
  { name: 'Mirkblood Devourer', type: 'minion', cost: 3, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: 'Friendly minions summoned nearby this minion gain +1/+1.' },
  { name: 'Mogwai', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 3, faction: 'neutral', text: 'After this moves, draw a card.' },
  { name: 'Prismatic Illusionist', type: 'arcanyst', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: 'Whenever you cast a spell, summon a 2/1 Illusion on a random nearby space.' },
  { name: 'Putrid Dreadflayer', type: 'minion', cost: 3, rarity: 'core', attack: 2, health: 4, faction: 'neutral', text: 'Flying' },
  { name: 'Repulsor Beast', type: 'minion', cost: 3, rarity: 'core', attack: 2, health: 2, faction: 'neutral', text: 'Opening Gambit: Push a nearby enemy minion to any space.' },
  { name: 'Saberspine Tiger', type: 'minion', cost: 3, rarity: 'core', attack: 3, health: 2, faction: 'neutral', text: 'Rush' },
  { name: 'Sand Burrower', type: 'minion', cost: 3, rarity: 'common', attack: 2, health: 4, faction: 'neutral', text: 'When this minion survives damage, it returns to your action bar.' },
  { name: 'Sapphire Seer', type: 'minion', cost: 3, rarity: 'common', attack: 2, health: 2, faction: 'neutral', text: 'Forcefield' },
  { name: 'Sarlac the Eternal', type: 'minion', cost: 3, rarity: 'legendary', attack: 1, health: 1, faction: 'neutral', text: 'Dying Wish: Re-summon this minion on a random space.' },
  { name: 'Silvertongue Corsair', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: 'Takes no damage from Generals.' },
  { name: 'Skywing', type: 'warmaster', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: 'Flying Your other minions with Flying cost 1 less.' },
  { name: 'Soboro', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 4, faction: 'neutral', text: 'Whenever this damages a neutral minion, destroy that minion.' },
  { name: 'Sojourner', type: 'minion', cost: 3, rarity: 'rare', attack: 1, health: 5, faction: 'neutral', text: 'Whenever this minion deals damage, draw a card.' },
  { name: 'Songwaver', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: 'Opening Gambit: Give a nearby friendly minion +1/+1.' },
  { name: 'Spelljammer', type: 'minion', cost: 3, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: 'Each player draws an additional card at the end of their turns.' },
  { name: 'Sun Seer', type: 'arcanyst', cost: 3, rarity: 'common', attack: 2, health: 4, faction: 'neutral', text: 'Whenever this minion deals damage, restore 2 Health to your General.' },
  { name: 'Sword of Mechazor', type: 'mech', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: 'Frenzy Opening Gambit: Progresses MECHAZOR build by +20%.' },
  { name: 'Sworn Avenger', type: 'minion', cost: 3, rarity: 'epic', attack: 1, health: 3, faction: 'neutral', text: 'Ranged Whenever your General takes damage, this minion gains +1 Attack.' },
  { name: 'Syvrel the Exile', type: 'minion', cost: 3, rarity: 'epic', attack: 1, health: 4, faction: 'neutral', text: 'Ranged Minions damaged by Syvrel are pulled in front of him.' },
  { name: 'Venom Toth', type: 'minion', cost: 3, rarity: 'epic', attack: 3, health: 3, faction: 'neutral', text: 'Whenever your opponent summons a minion, deal 1 damage to the enemy General.' },
  { name: 'Void Hunter', type: 'minion', cost: 3, rarity: 'common', attack: 4, health: 2, faction: 'neutral', text: 'Dying Wish: Draw a card.' },
  { name: 'Wind Runner', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: 'After this minion moves, give all friendly minions around it +1/+1.' },
  { name: 'Wind Stopper', type: 'minion', cost: 3, rarity: 'common', attack: 1, health: 7, faction: 'neutral', text: 'Ranged attackers must attack this minion first.' },
  { name: 'Wings of Paradise', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: 'Flying Whenever you replace a card, this minion gains +2 Attack this turn.' },
  { name: 'Yun', type: 'battle pet', cost: 3, rarity: 'common', attack: 5, health: 4, faction: 'neutral', text: '' },
  { name: 'Zukong', type: 'minion', cost: 3, rarity: 'legendary', attack: 3, health: 4, faction: 'neutral', text: 'You control your Battle Pets.' },
  { name: 'Arrow Whistler', type: 'warmaster', cost: 4, rarity: 'common', attack: 2, health: 4, faction: 'neutral', text: 'Ranged Your other minions with Ranged have +1 Attack.' },
  { name: 'Artifact Hunter', type: 'minion', cost: 4, rarity: 'epic', attack: 3, health: 3, faction: 'neutral', text: 'Opening Gambit: Draw a random artifact from your deck.' },
  { name: 'Black Locust', type: 'minion', cost: 4, rarity: 'legendary', attack: 2, health: 2, faction: 'neutral', text: 'Flying After this minion moves, summon a Black Locust nearby.' },
  { name: 'Captain Hank Hart', type: 'minion', cost: 4, rarity: 'epic', attack: 2, health: 4, faction: 'neutral', text: 'Ranged Whenever this minion deals damage, restore that much Health to it.' },
  { name: 'Chassis of Mechazor', type: 'mech', cost: 4, rarity: 'epic', attack: 5, health: 4, faction: 'neutral', text: 'Opening Gambit: Progresses MECHAZOR build by +20%. Cannot be targeted by ANY spells.' },
  { name: 'Dioltas', type: 'minion', cost: 4, rarity: 'epic', attack: 5, health: 3, faction: 'neutral', text: 'Dying Wish: Summon a 0/10 Tombstone minion with Provoke nearby your General.' },
  { name: 'Emerald Rejuvenator', type: 'minion', cost: 4, rarity: 'rare', attack: 4, health: 4, faction: 'neutral', text: 'Opening Gambit: Restore 4 Health to BOTH Generals.' },
  { name: 'Fire Spitter', type: 'minion', cost: 4, rarity: 'core', attack: 3, health: 2, faction: 'neutral', text: 'Ranged' },
  { name: 'Frostbone Naga', type: 'minion', cost: 4, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: 'Opening Gambit: Deal 2 damage to ALL minions and Generals around it.' },
  { name: 'Gnasher', type: 'minion', cost: 4, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: 'Dying Wish: This minion deals 3 damage to all enemies around it.' },
  { name: 'Hailstone Golem', type: 'golem', cost: 4, rarity: 'core', attack: 4, health: 6, faction: 'neutral', text: '' },
  { name: 'Lightbender', type: 'arcanyst', cost: 4, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: 'Opening Gambit: Dispel ALL spaces around it.' },
  { name: 'Mindwarper', type: 'arcanyst', cost: 4, rarity: 'rare', attack: 4, health: 3, faction: 'neutral', text: 'Opening Gambit: Gain a copy of a random spell from your opponent\'s action bar.' },
  { name: 'Moebius', type: 'arcanyst', cost: 4, rarity: 'epic', attack: 3, health: 5, faction: 'neutral', text: 'At the start of your turn, restore this minion to full Health and switch its Attack and Health.' },
  { name: 'Owlbeast Sage', type: 'arcanyst', cost: 4, rarity: 'rare', attack: 4, health: 4, faction: 'neutral', text: 'Whenever you cast a spell, your Arcanyst minions gain +2 Health.' },
  { name: 'Primus Shieldmaster', type: 'minion', cost: 4, rarity: 'core', attack: 3, health: 6, faction: 'neutral', text: 'Provoke' },
  { name: 'Purgatos, the Realmkeeper', type: 'minion', cost: 4, rarity: 'epic', attack: 3, health: 4, faction: 'neutral', text: 'Whenver this minion deals damage, either deal 3 damage to the enemy General OR restore 3 Health to your General.' },
  { name: 'Silhouette Tracer', type: 'minion', cost: 4, rarity: 'common', attack: 2, health: 6, faction: 'neutral', text: 'Opening Gambit: Teleport your General up to 3 spaces.' },
  { name: 'Sphynx', type: 'minion', cost: 4, rarity: 'legendary', attack: 5, health: 4, faction: 'neutral', text: 'Opening Gambit: Put a Riddle in your opponent\'s action bar.' },
  { name: 'Sun Elemental', type: 'minion', cost: 4, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: 'Opening Gambit: Give two random friendly minions +2 Health.' },
  { name: 'Sunsteel Defender', type: 'minion', cost: 4, rarity: 'rare', attack: 4, health: 3, faction: 'neutral', text: 'Forcefield' },
  { name: 'Sword Sister L\'kian', type: 'minion', cost: 4, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: 'Opening Gambit: Add 2 random cards from your Faction to your action bar.' },
  { name: 'Tethermancer', type: 'minion', cost: 4, rarity: 'rare', attack: 1, health: 6, faction: 'neutral', text: 'Provoke Dispel any minion that deals damage to this one.' },
  { name: 'Thorn Needler', type: 'minion', cost: 4, rarity: 'core', attack: 6, health: 4, faction: 'neutral', text: '' },
  { name: 'Unseven', type: 'warmaster', cost: 4, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: 'Dying Wish: Summon a minion with Dying Wish from your action bar.' },
  { name: 'White Widow', type: 'minion', cost: 4, rarity: 'rare', attack: 3, health: 4, faction: 'neutral', text: 'Whenever you replace a card, deal 2 damage to a random enemy minion or General.' },
  { name: 'Young Flamewing', type: 'minion', cost: 4, rarity: 'core', attack: 5, health: 4, faction: 'neutral', text: 'Flying' },
  { name: '', type: 'minion', cost: 4, rarity: '', attack: , health: , faction: 'neutral', text: '' },
]

export default neutral
