const neutral = [
  { name: 'Bloodtear Alchemist', type: 'minion', cost: 1, rarity: 'core', attack: 2, health: 1, faction: 'neutral', text: '<b>Opening Gambit</b>: Deal 1 damage to an enemy minion or General.' },
  { name: 'Dragonlark', type: 'minion', cost: 1, rarity: 'core', attack: 2, health: 1, faction: 'neutral', text: '<b>Flying</b>' },
  { name: 'Dreamgazer', type: 'minion', cost: 1, rarity: 'epic', attack: 1, health: 1, faction: 'neutral', text: 'When you replace this card, summon it nearby. Your General takes 2 damage.' },
  { name: 'Helm of Mechazor', type: 'mech', cost: 1, rarity: 'common', attack: 2, health: 2, faction: 'neutral', text: '<b>Opening Gambit</b>: Progresses MECHAZOR build by +20%.' },
  { name: 'Koi', type: 'battle pet', cost: 1, rarity: 'common', attack: 3, health: 1, faction: 'neutral', text: 'Takes no damage from Generals.' },
  { name: 'Komodo Charger', type: 'minion', cost: 1, rarity: 'core', attack: 1, health: 3, faction: 'neutral', text: '' },
  { name: 'Planar Scout', type: 'minion', cost: 1, rarity: 'core', attack: 2, health: 1, faction: 'neutral', text: '<b>Airdrop</b>' },
  { name: 'Prophet of the White Palm', type: 'minion', cost: 1, rarity: 'rare', attack: 1, health: 1, faction: 'neutral', text: '<b>Opening Gambit</b>: Prevent ALL spell damage until your next turn.' },
  { name: 'Swamp Entangler', type: 'minion', cost: 1, rarity: 'common', attack: 0, health: 3, faction: 'neutral', text: '<b>Provoke</b>' },
  { name: 'Aethermaster', type: 'arcanyst', cost: 2, rarity: 'epic', attack: 1, health: 3, faction: 'neutral', text: 'You may replace an additional card each turn.' },
  { name: 'Amu', type: 'battle pet', cost: 2, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: '' },
  { name: 'Araki Headhunter', type: 'minion', cost: 2, rarity: 'epic', attack: 1, health: 3, faction: 'neutral', text: 'Whenever you summon a minion with Opening Gambit from your action bar, gain +2 Attack.' },
  { name: 'Azure Horn Shaman', type: 'minion', cost: 2, rarity: 'rare', attack: 1, health: 4, faction: 'neutral', text: '<b>Dying Wish</b>: Give +4 Health to friendly minions around it.' },
  { name: 'Bluetip Scorpion', type: 'minion', cost: 2, rarity: 'common', attack: 3, health: 1, faction: 'neutral', text: 'Deals double damage to minions.' },
  { name: 'Ephemeral Shroud', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 2, faction: 'neutral', text: '<b>Opening Gambit</b>: Dispel 1 nearby space.' },
  { name: 'Flameblood Warlock', type: 'minion', cost: 2, rarity: 'rare', attack: 3, health: 1, faction: 'neutral', text: '<b>Opening Gambit</b>: Deal 3 damage to BOTH Generals.' },
  { name: 'Ghost Lynx', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 1, faction: 'neutral', text: '<b>Opening Gambit</b>: Teleport a nearby minion to a random space.' },
  { name: 'Golem Metallurgist', type: 'golem', cost: 2, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: 'The first Golem you summon each turn costs 1 less.' },
  { name: 'Healing Mystic', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Restore 2 Health to a minion or General.' },
  { name: 'Jaxi', type: 'minion', cost: 2, rarity: 'common', attack: 1, health: 1, faction: 'neutral', text: '<b>Dying Wish</b>: Summon a 1/1 Ranged Mini-Jax in a random unoccupied corner.' },
  { name: 'Manaforger', type: 'arcanyst', cost: 2, rarity: 'rare', attack: 1, health: 3, faction: 'neutral', text: 'The first non-Bloodborn spell you cast each turn costs 1 less.' },
  { name: 'Maw', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 2, faction: 'neutral', text: '<b>Opening Gambit</b>: Deal 2 damage to a nearby enemy minion.' },
  { name: 'Piercing Mantis', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 2, faction: 'neutral', text: '<b>Frenzy</b>' },
  { name: 'Primus Fist', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Give a nearby friendly minion +2 Attack this turn.' },
  { name: 'Rock Pulverizer', type: 'minion', cost: 2, rarity: 'core', attack: 1, health: 4, faction: 'neutral', text: '<b>Provoke</b>' },
  { name: 'Rust Crawler', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Destroy a random enemy artifact.' },
  { name: 'Shiro Puppydragon', type: 'minion', cost: 2, rarity: 'common', attack: 1, health: 4, faction: 'neutral', text: 'At the end of your turn, give each nearby friendly minion +1 Attack.' },
  { name: 'Skyrock Golem', type: 'golem', cost: 2, rarity: 'core', attack: 3, health: 2, faction: 'neutral', text: '' },
  { name: 'Sol', type: 'battle pet', cost: 2, rarity: 'rare', attack: 1, health: 1, faction: 'neutral', text: '<b>Opening Gambit</b>: Activate a friendly Battle Pet.' },
  { name: 'Vale Hunter', type: 'minion', cost: 2, rarity: 'core', attack: 1, health: 2, faction: 'neutral', text: '<b>Ranged</b>' },
  { name: 'Wings of Mechazor', type: 'mech', cost: 2, rarity: 'common', attack: 1, health: 4, faction: 'neutral', text: '<b>Airdrop</b><br> <b>Opening Gambit</b>: Progresses MECHAZOR build by +20%.' },
  { name: 'Wood-Wen', type: 'minion', cost: 2, rarity: 'common', attack: 2, health: 2, faction: 'neutral', text: '<b>Provoke</b><br> <b>Opening Gambit</b>: Give a nearby friendly minion Provoke.' },
  { name: 'Z0R', type: 'battle pet', cost: 2, rarity: 'epic', attack: 2, health: 1, faction: 'neutral', text: '<b>Dying Wish</b>: Put a random MECH minion into your action bar.' },
  { name: 'Abjudicator', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 1, faction: 'neutral', text: '<b>Opening Gambit</b>: Lower the cost of all spells in your action bar by 1.' },
  { name: 'Alcuin Loremaster', type: 'arcanyst', cost: 3, rarity: 'epic', attack: 3, health: 1, faction: 'neutral', text: '<b>Opening Gambit</b>: Put a copy of the most recently cast spell into your action bar.' },
  { name: 'Bastion', type: 'structure', cost: 3, rarity: 'epic', attack: 0, health: 5, faction: 'neutral', text: 'At the end of your turn, give other friendly minions +1 Health.' },
  { name: 'Blaze Hound', type: 'minion', cost: 3, rarity: 'common', attack: 4, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Both players drop a card.' },
  { name: 'Blistering Skorn', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Deal 1 damage to ALL minions and Generals (including itself).' },
  { name: 'Bloodshard Golem', type: 'golem', cost: 3, rarity: 'core', attack: 4, health: 3, faction: 'neutral', text: '' },
  { name: 'Cannon of Mechazor', type: 'mech', cost: 3, rarity: 'rare', attack: 2, health: 2, faction: 'neutral', text: '<b>Ranged</b><br> <b>Opening Gambit</b>: Progresses MECHAZOR build by +20%.' },
  { name: 'Chaos Elemental', type: 'minion', cost: 3, rarity: 'epic', attack: 4, health: 4, faction: 'neutral', text: 'Whenever this minion takes damage, it randomly teleports.' },
  { name: 'Crimson Oculus', type: 'minion', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: 'Whenever opponent summons a minion, this minion gains +1/+1.' },
  { name: 'Crossbones', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Destroy an enemy minion with Ranged.' },
  { name: 'Elkowl', type: 'minion', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Gain two random abilities.' },
  { name: 'Golden Mantella', type: 'minion', cost: 3, rarity: 'common', attack: 4, health: 2, faction: 'neutral', text: '<b>Opening Gambit</b>: Put a random Battle Pet into your action bar.' },
  { name: 'Golem Vanquisher', type: 'golem', cost: 3, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: '<b>Provoke</b><br> Your other Golem minions have <b>Provoke</b>.' },
  { name: 'Hydrax', type: 'minion', cost: 3, rarity: 'legendary', attack: 3, health: 3, faction: 'neutral', text: 'Whenever a friendly Battle Pet dies, draw a card.' },
  { name: 'Ion', type: 'battle pet', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: '<b>Ranged</b><br> Deals double damage to Generals.' },
  { name: 'Lady Locke', type: 'minion', cost: 3, rarity: 'legendary', attack: 2, health: 2, faction: 'neutral', text: '<b>Provoke</b><br> <b>Opening Gambit</b>: Other minions you summon this turn gain +1/+1 and <b>Provoke</b>.' },
  { name: 'Mirkblood Devourer', type: 'minion', cost: 3, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: 'Friendly minions summoned nearby this minion gain +1/+1.' },
  { name: 'Mogwai', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 3, faction: 'neutral', text: 'After this moves, draw a card.' },
  { name: 'Prismatic Illusionist', type: 'arcanyst', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'neutral', text: 'Whenever you cast a spell, summon a 2/1 Illusion on a random nearby space.' },
  { name: 'Putrid Dreadflayer', type: 'minion', cost: 3, rarity: 'core', attack: 2, health: 4, faction: 'neutral', text: '<b>Flying</b>' },
  { name: 'Repulsor Beast', type: 'minion', cost: 3, rarity: 'core', attack: 2, health: 2, faction: 'neutral', text: '<b>Opening Gambit</b>: Push a nearby enemy minion to any space.' },
  { name: 'Saberspine Tiger', type: 'minion', cost: 3, rarity: 'core', attack: 3, health: 2, faction: 'neutral', text: '<b>Rush</b>' },
  { name: 'Sand Burrower', type: 'minion', cost: 3, rarity: 'common', attack: 2, health: 4, faction: 'neutral', text: 'When this minion survives damage, it returns to your action bar.' },
  { name: 'Sapphire Seer', type: 'minion', cost: 3, rarity: 'common', attack: 2, health: 2, faction: 'neutral', text: '<b>Forcefield</b>' },
  { name: 'Sarlac the Eternal', type: 'minion', cost: 3, rarity: 'legendary', attack: 1, health: 1, faction: 'neutral', text: '<b>Dying Wish</b>: Re-summon this minion on a random space.' },
  { name: 'Silvertongue Corsair', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: 'Takes no damage from Generals.' },
  { name: 'Skywing', type: 'warmaster', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: '<b>Flying</b><br> Your other minions with <b>Flying</b> cost 1 less.' },
  { name: 'Soboro', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 4, faction: 'neutral', text: 'Whenever this damages a neutral minion, destroy that minion.' },
  { name: 'Sojourner', type: 'minion', cost: 3, rarity: 'rare', attack: 1, health: 5, faction: 'neutral', text: 'Whenever this minion deals damage, draw a card.' },
  { name: 'Songwaver', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Give a nearby friendly minion +1/+1.' },
  { name: 'Spelljammer', type: 'minion', cost: 3, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: 'Each player draws an additional card at the end of their turns.' },
  { name: 'Sun Seer', type: 'arcanyst', cost: 3, rarity: 'common', attack: 2, health: 4, faction: 'neutral', text: 'Whenever this minion deals damage, restore 2 Health to your General.' },
  { name: 'Sword of Mechazor', type: 'mech', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: '<b>Frenzy</b><br> <b>Opening Gambit</b>: Progresses MECHAZOR build by +20%.' },
  { name: 'Sworn Avenger', type: 'minion', cost: 3, rarity: 'epic', attack: 1, health: 3, faction: 'neutral', text: '<b>Ranged</b><br> Whenever your General takes damage, this minion gains +1 Attack.' },
  { name: 'Syvrel the Exile', type: 'minion', cost: 3, rarity: 'epic', attack: 1, health: 4, faction: 'neutral', text: '<b>Ranged</b><br> Minions damaged by Syvrel are pulled in front of him.' },
  { name: 'Venom Toth', type: 'minion', cost: 3, rarity: 'epic', attack: 3, health: 3, faction: 'neutral', text: 'Whenever your opponent summons a minion, deal 1 damage to the enemy General.' },
  { name: 'Void Hunter', type: 'minion', cost: 3, rarity: 'common', attack: 4, health: 2, faction: 'neutral', text: '<b>Dying Wish</b>: Draw a card.' },
  { name: 'Wind Runner', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: 'After this minion moves, give all friendly minions around it +1/+1.' },
  { name: 'Wind Stopper', type: 'minion', cost: 3, rarity: 'common', attack: 1, health: 7, faction: 'neutral', text: 'Ranged attackers must attack this minion first.' },
  { name: 'Wings of Paradise', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: '<b>Flying</b><br> Whenever you replace a card, this minion gains +2 Attack this turn.' },
  { name: 'Yun', type: 'battle pet', cost: 3, rarity: 'common', attack: 5, health: 4, faction: 'neutral', text: '' },
  { name: 'Zukong', type: 'minion', cost: 3, rarity: 'legendary', attack: 3, health: 4, faction: 'neutral', text: 'You control your Battle Pets.' },
  { name: 'Arrow Whistler', type: 'warmaster', cost: 4, rarity: 'common', attack: 2, health: 4, faction: 'neutral', text: '<b>Ranged</b><br> Your other minions with <b>Ranged</b> have +1 Attack.' },
  { name: 'Artifact Hunter', type: 'minion', cost: 4, rarity: 'epic', attack: 3, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Draw a random artifact from your deck.' },
  { name: 'Black Locust', type: 'minion', cost: 4, rarity: 'legendary', attack: 2, health: 2, faction: 'neutral', text: '<b>Flying</b><br> After this minion moves, summon a Black Locust nearby.' },
  { name: 'Captain Hank Hart', type: 'minion', cost: 4, rarity: 'epic', attack: 2, health: 4, faction: 'neutral', text: '<b>Ranged</b><br> Whenever this minion deals damage, restore that much Health to it.' },
  { name: 'Chassis of Mechazor', type: 'mech', cost: 4, rarity: 'epic', attack: 5, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Progresses MECHAZOR build by +20%. Cannot be targeted by ANY spells.' },
  { name: 'Dioltas', type: 'minion', cost: 4, rarity: 'epic', attack: 5, health: 3, faction: 'neutral', text: '<b>Dying Wish</b>: Summon a 0/10 Tombstone minion with Provoke nearby your General.' },
  { name: 'Emerald Rejuvenator', type: 'minion', cost: 4, rarity: 'rare', attack: 4, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Restore 4 Health to BOTH Generals.' },
  { name: 'Fire Spitter', type: 'minion', cost: 4, rarity: 'core', attack: 3, health: 2, faction: 'neutral', text: '<b>Ranged</b>' },
  { name: 'Frostbone Naga', type: 'minion', cost: 4, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Deal 2 damage to ALL minions and Generals around it.' },
  { name: 'Gnasher', type: 'minion', cost: 4, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: '<b>Dying Wish</b>: This minion deals 3 damage to all enemies around it.' },
  { name: 'Hailstone Golem', type: 'golem', cost: 4, rarity: 'core', attack: 4, health: 6, faction: 'neutral', text: '' },
  { name: 'Lightbender', type: 'arcanyst', cost: 4, rarity: 'rare', attack: 3, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Dispel ALL spaces around it.' },
  { name: 'Mindwarper', type: 'arcanyst', cost: 4, rarity: 'rare', attack: 4, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Gain a copy of a random spell from your opponent\'s action bar.' },
  { name: 'Moebius', type: 'arcanyst', cost: 4, rarity: 'epic', attack: 3, health: 5, faction: 'neutral', text: 'At the start of your turn, restore this minion to full Health and switch its Attack and Health.' },
  { name: 'Owlbeast Sage', type: 'arcanyst', cost: 4, rarity: 'rare', attack: 4, health: 4, faction: 'neutral', text: 'Whenever you cast a spell, your Arcanyst minions gain +2 Health.' },
  { name: 'Primus Shieldmaster', type: 'minion', cost: 4, rarity: 'core', attack: 3, health: 6, faction: 'neutral', text: '<b>Provoke</b>' },
  { name: 'Purgatos, the Realmkeeper', type: 'minion', cost: 4, rarity: 'epic', attack: 3, health: 4, faction: 'neutral', text: 'Whenver this minion deals damage, either deal 3 damage to the enemy General OR restore 3 Health to your General.' },
  { name: 'Silhouette Tracer', type: 'minion', cost: 4, rarity: 'common', attack: 2, health: 6, faction: 'neutral', text: '<b>Opening Gambit</b>: Teleport your General up to 3 spaces.' },
  { name: 'Sphynx', type: 'minion', cost: 4, rarity: 'legendary', attack: 5, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Put a Riddle in your opponent\'s action bar.' },
  { name: 'Sun Elemental', type: 'minion', cost: 4, rarity: 'common', attack: 3, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Give two random friendly minions +2 Health.' },
  { name: 'Sunsteel Defender', type: 'minion', cost: 4, rarity: 'rare', attack: 4, health: 3, faction: 'neutral', text: '<b>Forcefield</b>' },
  { name: 'Sword Sister L\'kian', type: 'minion', cost: 4, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Add 2 random cards from your Faction to your action bar.' },
  { name: 'Tethermancer', type: 'minion', cost: 4, rarity: 'rare', attack: 1, health: 6, faction: 'neutral', text: '<b>Provoke</b><br> Dispel any minion that deals damage to this one.' },
  { name: 'Thorn Needler', type: 'minion', cost: 4, rarity: 'core', attack: 6, health: 4, faction: 'neutral', text: '' },
  { name: 'Unseven', type: 'warmaster', cost: 4, rarity: 'legendary', attack: 2, health: 4, faction: 'neutral', text: '<b>Dying Wish</b>: Summon a minion with <b>Dying Wish</b> from your action bar.' },
  { name: 'White Widow', type: 'minion', cost: 4, rarity: 'rare', attack: 3, health: 4, faction: 'neutral', text: 'Whenever you replace a card, deal 2 damage to a random enemy minion or General.' },
  { name: 'Young Flamewing', type: 'minion', cost: 4, rarity: 'core', attack: 5, health: 4, faction: 'neutral', text: '<b>Flying</b>' },
  { name: 'Alter Rexx', type: 'mech', cost: 5, rarity: 'legendary', attack: 4, health: 4, faction: 'neutral', text: 'Whenever you summon MECHAZOR, put a MECHAZOR in your action bar.' },
  { name: 'Ash Mephyt', type: 'minion', cost: 5, rarity: 'common', attack: 2, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Summon two copies of this minion on random spaces.' },
  { name: 'Beastmaster', type: 'minion', cost: 5, rarity: 'rare', attack: 2, health: 5, faction: 'neutral', text: '<b>Frenzy</b>, <b>Celerity</b>' },
  { name: 'Brightmoss Golem', type: 'minion', cost: 5, rarity: 'core', attack: 4, health: 9, faction: 'neutral', text: '' },
  { name: 'Calculator', type: 'minion', cost: 5, rarity: 'epic', attack: 1, health: 1, faction: 'neutral', text: '<b>Opening Gambit</b>: Gain the combined Attack and Health of all Battle Pets in your action bar.' },
  { name: 'Chakkram', type: 'minion', cost: 5, rarity: 'rare', attack: 5, health: 5, faction: 'neutral', text: 'Costs 2 less if your General took damage on your opponent\'s last turn.' },
  { name: 'Dagger Kiri', type: 'minion', cost: 5, rarity: 'common', attack: 2, health: 8, faction: 'neutral', text: '<b>Celerity</b>' },
  { name: 'Dancing Blades', type: 'minion', cost: 5, rarity: 'common', attack: 4, health: 6, faction: 'neutral', text: '<b>Opening Gambit</b>: Deal 3 damage to ANY minion in front of this.' },
  { name: 'Envybaer', type: 'minion', cost: 5, rarity: 'legendary', attack: 3, health: 7, faction: 'neutral', text: 'Whenever this minion damages an enemy, teleport that enemy to a random unoccupied corner.' },
  { name: 'Fireblazer', type: 'minion', cost: 5, rarity: 'common', attack: 5, health: 5, faction: 'neutral', text: '<b>Provoke</b>' },
  { name: 'Firestarter', type: 'arcanyst', cost: 5, rarity: 'rare', attack: 3, health: 5, faction: 'neutral', text: 'Whenever you cast a spell, summon a 1/1 Spellspark with <b>Rush</b> on a random nearby space.' },
  { name: 'Golden Justicar', type: 'minion', cost: 5, rarity: 'epic', attack: 4, health: 6, faction: 'neutral', text: '<b>Provoke</b><br> Your other minions with <b>Provoke</b> can move two additional spaces.' },
  { name: 'Grincher', type: 'minion', cost: 5, rarity: 'rare', attack: 5, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Put a random artifact into your action bar. It costs 2 less.' },
  { name: 'Hollow Grovekeeper', type: 'minion', cost: 5, rarity: 'legendary', attack: 3, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Destroy ANY nearby minion with Provoke or Frenzy. If you do, this minion gains Provoke and Frenzy.' },
  { name: 'Inquisitor Kron', type: 'minion', cost: 5, rarity: 'legendary', attack: 4, health: 6, faction: 'neutral', text: '<b>Provoke</b><br> Whenever you replace a card, summon a 2/2 Prisoner with a random ability nearby.' },
  { name: 'Keeper of the Vale', type: 'minion', cost: 5, rarity: 'legendary', attack: 3, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Summon a random non-token friendly minion destroyed this game nearby.' },
  { name: 'Lux Ignis', type: 'minion', cost: 5, rarity: 'epic', attack: 2, health: 5, faction: 'neutral', text: '<b>Ranged</b><br> At the end of your turn, restore 2 Health to all nearby friendly minions.' },
  { name: 'Necroseer', type: 'minion', cost: 5, rarity: 'core', attack: 5, health: 4, faction: 'neutral', text: '<b>Dying Wish</b>: Draw a card.' },
  { name: 'Rawr', type: 'battle pet', cost: 5, rarity: 'legendary', attack: 3, health: 7, faction: 'neutral', text: 'Whenever this minion takes damage, summon a random Battle Pet nearby.' },
  { name: 'Rogue Warden', type: 'minion', cost: 5, rarity: 'common', attack: 4, health: 3, faction: 'neutral', text: '<b>Ranged</b>' },
  { name: 'Sunset Paragon', type: 'minion', cost: 5, rarity: 'epic', attack: 3, health: 2, faction: 'neutral', text: '<b>Opening Gambit</b>: ALL nearby minions deal damage to themselves equal to their Attack.' },
  { name: 'Sworn Defender', type: 'minion', cost: 5, rarity: 'epic', attack: 4, health: 7, faction: 'neutral', text: 'Whenever your General takes damage, restore this minion to full Health.' },
  { name: 'The High Hand', type: 'minion', cost: 5, rarity: 'common', attack: 2, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Gains +1/+1 for each card in your opponent\'s action bar.' },
  { name: 'Twilight Sorcerer', type: 'minion', cost: 5, rarity: 'epic', attack: 3, health: 6, faction: 'neutral', text: '<b>Opening Gambit</b>: Put a copy of a random spell you cast this game into your action bar.' },
  { name: `Zen'Rui, the Blightspawned`, type: 'minion', cost: 5, rarity: 'legendary', attack: 4, health: 3, faction: 'neutral', text: '<b>Opening Gambit</b>: Take control of a nearby enemy minion with 2 or less Attack.' },
  { name: 'Archon Spellbinder', type: 'arcanyst', cost: 6, rarity: 'legendary', attack: 7, health: 7, faction: 'neutral', text: `Your opponent's non-Bloodborn spells cost 1 more to cast.` },
  { name: 'Bloodletter', type: 'minion', cost: 6, rarity: 'core', attack: 4, health: 6, faction: 'neutral', text: 'Deals double damage to Generals.' },
  { name: 'Bonereaper', type: 'minion', cost: 6, rarity: 'epic', attack: 2, health: 9, faction: 'neutral', text: '<b>Provoke</b><br> At the end of your turn, deal 2 damage to all nearby enemy minions.' },
  { name: 'Deathblighter', type: 'minion', cost: 6, rarity: 'common', attack: 3, health: 4, faction: 'neutral', text: '<b>Opening Gambit</b>: Deal 3 damage to all enemy minions around it.' },
  { name: 'Diamond Golem', type: 'golem', cost: 6, rarity: 'common', attack: 4, health: 11, faction: 'neutral', text: '' },
  { name: 'Eclipse', type: 'arcanyst', cost: 6, rarity: 'legendary', attack: 3, health: 7, faction: 'neutral', text: 'Whenever this minion takes damage, it deals that much damage to the enemy General.' },
  { name: 'First Sword of Akrane', type: 'minion', cost: 6, rarity: 'common', attack: 7, health: 7, faction: 'neutral', text: 'Your other minions have +1 Attack.' },
  { name: 'Grove Lion', type: 'minion', cost: 6, rarity: 'epic', attack: 5, health: 5, faction: 'neutral', text: 'While this minion is on the battlefield, your General has <b>Forcefield</b>.' },
  { name: 'Jax Truesight', type: 'minion', cost: 6, rarity: 'legendary', attack: 1, health: 1, faction: 'neutral', text: '<b>Ranged</b><br> <b>Opening Gambit</b>: Summon a 1/1 Ranged Mini-Jax in each unoccupied corner.' },
  { name: 'Ruby Rifter', type: 'minion', cost: 6, rarity: 'legendary', attack: 4, health: 6, faction: 'neutral', text: 'Whenever your General takes damage, give this minion +2 Attack and draw a card.' },
  { name: 'Serpenti', type: 'minion', cost: 6, rarity: 'common', attack: 7, health: 4, faction: 'neutral', text: '<b>Frenzy</b>' },
  { name: 'Silverbeak', type: 'minion', cost: 6, rarity: 'common', attack: 6, health: 9, faction: 'neutral', text: '' },
  { name: 'Storm Aratha', type: 'minion', cost: 6, rarity: 'common', attack: 6, health: 5, faction: 'neutral', text: '<b>Flying</b>' },
  { name: 'Stormmetal Golem', type: 'golem', cost: 6, rarity: 'core', attack: 8, health: 8, faction: 'neutral', text: '' },
  { name: 'The Scientist', type: 'minion', cost: 6, rarity: 'epic', attack: 6, health: 6, faction: 'neutral', text: 'Whenever you cast a spell that targets a friendly minion, draw a card.' },
  { name: 'Astral Crusader', type: 'minion', cost: 7, rarity: 'legendary', attack: 7, health: 6, faction: 'neutral', text: 'Whenever you replace this card, it costs 1 less and gains +1/+1.' },
  { name: 'Dark Nemesis', type: 'minion', cost: 7, rarity: 'legendary', attack: 4, health: 10, faction: 'neutral', text: 'At the start of your turn, deal 4 damage to the enemy General and this minion gains +4 Attack.' },
  { name: 'Dragonbone Golem', type: 'golem', cost: 7, rarity: 'core', attack: 10, health: 10, faction: 'neutral', text: '' },
  { name: `E'Xun`, type: 'minion', cost: 7, rarity: 'legendary', attack: 5, health: 5, faction: 'neutral', text: '<b>Forcefield</b><br> Whenever this minion attacks or is attacked, draw a card.' },
  { name: 'Grailmaster', type: 'minion', cost: 7, rarity: 'epic', attack: 6, health: 6, faction: 'neutral', text: 'Whenever you summon a minion, this minion gains a random keyword ability.' },
  { name: 'Paddo', type: 'minion', cost: 7, rarity: 'legendary', attack: 12, health: 6, faction: 'neutral', text: '<b>Airdrop</b><br> <b>Opening Gambit</b>: Push ALL nearby minions and Generals to random spaces on the battlefield.' },
  { name: 'Pandora', type: 'minion', cost: 7, rarity: 'legendary', attack: 3, health: 10, faction: 'neutral', text: 'At the end of your turn, summon a 3/3 Spirit Wolf with a random ability on a nearby space.' },
  { name: 'Red Synja', type: 'minion', cost: 7, rarity: 'legendary', attack: 7, health: 7, faction: 'neutral', text: 'Whenever your General takes damage, deal 7 damage to a random nearby enemy minion.' },
  { name: 'Rook', type: 'minion', cost: 7, rarity: 'legendary', attack: 5, health: 5, faction: 'neutral', text: 'At the end of your turn, this minion gains a random Faction ability.' },
  { name: 'War Talon', type: 'minion', cost: 7, rarity: 'common', attack: 4, health: 9, faction: 'neutral', text: '<b>Frenzy</b>, <b>Provoke</b>' },
  { name: 'Whistling Blade', type: 'minion', cost: 7, rarity: 'common', attack: 2, health: 15, faction: 'neutral', text: '<b>Provoke</b>' },
  { name: 'Zurael, the Lifegiver', type: 'minion', cost: 7, rarity: 'legendary', attack: 4, health: 7, faction: 'neutral', text: '<b>Opening Gambit</b>: Summon all non-token friendly minions destroyed on your opponent\'s last turn on random spaces.' },
  { name: 'Khymera', type: 'minion', cost: 8, rarity: 'legendary', attack: 5, health: 12, faction: 'neutral', text: 'Whenever this minion takes damage, summon a random token minion nearby.' },
  { name: 'Blood Taura', type: 'minion', cost: 25, rarity: 'epic', attack: 12, health: 12, faction: 'neutral', text: `<b>Provoke</b><br> This minion's cost is equal to your General's Health.` },
]

export default neutral
