const songhai = [
  { name: 'Inner Focus', type: 'spell', cost: 0, rarity: 'core', faction: 'songhai', text: 'Reactivate an exhausted friendly minion with 3 or less Attack.' },
  { name: 'Juxtaposition', type: 'spell', cost: 0, rarity: 'epic', faction: 'songhai', text: 'Switch positions between ANY two minions.' },
  { name: 'Mana Vortex', type: 'spell', cost: 0, rarity: 'rare', faction: 'songhai', text: 'The next two spells you cast this turn cost 1 less. Draw a card at the end of turn.' },
  { name: 'Ace', type: 'battle pet', cost: 1, rarity: 'common', attack: 1, health: 2, faction: 'songhai', text: 'Ranged' },
  { name: 'Bloodrage Mask', type: 'artifact', cost: 1, rarity: 'core', faction: 'songhai', text: 'Whenever you cast a spell, deal 1 damage to the enemy General.' },
  { name: 'Crescent Spear', type: 'artifact', cost: 1, rarity: 'legendary', faction: 'songhai', text: 'Your General gains +1 Attack. Spells you cast that deal damage deal +1 damage.' },
  { name: 'Ghost Lightning', type: 'spell', cost: 1, rarity: 'core', faction: 'songhai', text: 'Deal 1 damage to all enemy minions.' },
  { name: 'Heartseeker', type: 'minion', cost: 1, rarity: 'common', attack: 1, health: 1, faction: 'songhai', text: 'Ranger' },
  { name: 'Katara', type: 'minion', cost: 1, rarity: 'common', attack: 1, health: 3, faction: 'songhai', text: 'Backstab: (3).' },
  { name: 'Mist Dragon Seal', type: 'spell', cost: 1, rarity: 'common', faction: 'songhai', text: 'Give a friendly minion +1/+1 and teleport it to any space on the battlefield.' },
  { name: 'Mist Walking', type: 'spell', cost: 1, rarity: 'rare', faction: 'songhai', text: 'Teleport your General up to 2 spaces.' },
  { name: 'Saberspine Seal', type: 'spell', cost: 1, rarity: 'core', faction: 'songhai', text: 'Give a minion or General +3 Attack this turn.' },
  { name: 'Shadow Waltz', type: 'spell', cost: 1, rarity: 'common', faction: 'songhai', text: 'Lower the cost of all minions with Backstab in your action bar by 1 and give them +1/+1.' },
  { name: 'Artifact Defiler', type: 'spell', cost: 2, rarity: 'common', faction: 'songhai', text: 'Destroy all artifacts on the enemy General.' },
  { name: 'Chakri Avatar', type: 'arcanyst', cost: 2, rarity: 'core', attack: 1, health: 2, faction: 'songhai', text: 'Whenever you cast a spell, this minion gains +1/+1.' },
  { name: 'Crimson Coil', type: 'spell', cost: 2, rarity: 'common', faction: 'songhai', text: 'Deal 2 damage to a minion. Activate your Battle Pets.' },
  { name: 'Deathstrike Seal', type: 'spell', cost: 2, rarity: 'rare', faction: 'songhai', text: 'Give a friendly minion, "Whenever this damages an enemy minion, destroy that minion."' },
  { name: 'Eight Gates', type: 'spell', cost: 2, rarity: 'legendary', faction: 'songhai', text: 'Spells you cast this turn that deal damage deal +2 damage.' },
  { name: 'Kaido Assassin', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 3, faction: 'songhai', text: 'Backstab: (1).' },
  { name: 'Mask of Shadows', type: 'artifact', cost: 2, rarity: 'legendary', faction: 'songhai', text: 'Your General gains Backstab (4).' },
  { name: 'Mirror Meld', type: 'spell', cost: 2, rarity: 'rare', faction: 'songhai', text: 'Summon a copy of a friendly minion that costs 2 of less nearby.' },
  { name: 'Phoenix Fire', type: 'spell', cost: 2, rarity: 'core', faction: 'songhai', text: 'Deal 3 damage to a minion or General.' },
  { name: 'Tusk Boar', type: 'minion', cost: 2, rarity: 'legendary', attack: 2, health: 3, faction: 'songhai', text: 'Rush Return this minion to your action bar at the beginning of your turn.' },
  { name: 'Xho', type: 'battle pet', cost: 2, rarity: 'rare', attack: 2, health: 3, faction: 'songhai', text: 'Dying Wish: Put a random Songhai spell into your action bar. It costs 1 less.' },
  { name: 'Battle Panddo', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 4, faction: 'songhai', text: 'Whenever this minion takes damage, deal 1 damage to all enemies.' },
  { name: 'Celestial Phantom', type: 'minion', cost: 3, rarity: 'rare', attack: 1, health: 5, faction: 'songhai', text: 'Whenever this damages an enemy minion, destroy that minion.' },
  { name: 'Cyclone Mask', type: 'artifact', cost: 3, rarity: 'epic', faction: 'songhai', text: 'Your General gains Ranged.' },
  { name: 'Gore Horn', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'songhai', text: 'Backstab: (2). After this minion attacks, it gains +1/+1.' },
  { name: 'Jade Monk', type: 'minion', cost: 3, rarity: 'common', attack: 4, health: 3, faction: 'songhai', text: 'Whenever this minion takes damage, deal 1 damage to a random enemy minion.' },
  { name: 'Ki Beholder', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 2, faction: 'songhai', text: 'Ranged Opening Gambit: An enemy minion cannot move next turn.' },
  { name: 'Killing Edge', type: 'spell', cost: 3, rarity: 'core', faction: 'songhai', text: 'Give a friendly minion +4/+2. If that minion has Backstab, draw a card at end of turn.' },
  { name: 'Lantern Fox', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 4, faction: 'songhai', text: 'Whenever this minion takes damage, put a Phoenix Fire in your action bar.' },
  { name: 'Onyx Bear Seal', type: 'spell', cost: 3, rarity: 'epic', faction: 'songhai', text: 'Transform an enemy minion into a 0/2 Panddo that cannot be attacked.' },
  { name: 'Twin Strike', type: 'spell', cost: 3, rarity: 'common', faction: 'songhai', text: 'Deal 2 damage to exactly two random enemy minions. Draw a card at end of turn.' },
  { name: 'Widowmaker', type: 'minion', cost: 3, rarity: 'core', attack: 2, health: 3, faction: 'songhai', text: 'Ranged' },
  { name: 'Ancestrial Divination', type: 'spell', cost: 4, rarity: 'common', faction: 'songhai', text: 'Draw a card for each friendly minion on the battlefield.' },
  { name: 'Four Winds Magi', type: 'arcanyst', cost: 4, rarity: 'rare', attack: 4, health: 4, faction: 'songhai', text: 'Whenever you cast a spell, deal 1 damage to enemy General and restore 1 Health to your General.' },
  { name: 'Keshrai Fanblade', type: 'minion', cost: 4, rarity: 'common', attack: 5, health: 3, faction: 'songhai', text: 'Opening Gambit: Next turn, opponent\'s spells cost 2 more to cast.' },
  { name: 'Pandamonium', type: 'spell', cost: 4, rarity: 'epic', faction: 'songhai', text: 'Transform ALL minions into 0/2 Panddo that cannot be attacked until end of turn.' },
  { name: 'Storm Sister Alkyone', type: 'minion', cost: 4, rarity: 'legendary', attack: 3, health: 5, faction: 'songhai', text: 'Spells you cast that deal damage deal +1 damage.' },
  { name: 'Hamon Bladeseeker', type: 'minion', cost: 5, rarity: 'epic', attack: 8, health: 8, faction: 'songhai', text: 'At the start of your turn, deal 2 damage to your General.' },
  { name: 'Heaven\'s Eclipse', type: 'spell', cost: 5, rarity: 'legendary', faction: 'songhai', text: 'Draw 3 spell cards from your deck.' },
  { name: 'Onyx Jaguar', type: 'minion', cost: 5, rarity: 'epic', attack: 3, health: 3, faction: 'songhai', text: 'Whenever a friendly minion is moved for any reason, give it +1/+1.' },
  { name: 'Scarlet Viper', type: 'minion', cost: 5, rarity: 'common', attack: 2, health: 5, faction: 'songhai', text: 'Flying Backstab: (4)' },
  { name: 'Grandmaster Zendo', type: 'minion', cost: 6, rarity: 'legendary', attack: 4, health: 6, faction: 'songhai', text: 'The enemy General moves and attacks as if they are a Battle Pet.' },
  { name: 'Storm Kage', type: 'minion', cost: 7, rarity: 'legendary', attack: 5, health: 10, faction: 'songhai', text: 'Whenever one of your spells deals damage, put a Kage Lightning in your action bar.' },
  { name: 'Koan of Horns', type: 'spell', cost: 8, rarity: 'legendary', faction: 'songhai', text: 'Transform all minions in your action bar and deck to 0-cost Gore Horns. Draw 3 cards.' },
  { name: 'Spiral Technique', type: 'spell', cost: 8, rarity: 'epic', faction: 'songhai', text: 'Deal 8 damage to a minion or General.' },
]

export default songhai
