const songhai = [
  { id: 20086, name: 'Inner Focus', type: 'spell', cost: 0, rarity: 'basic', faction: 'songhai', text: 'Reactivate an exhausted friendly minion with 3 or less Attack.' },
  { id: 20129, name: 'Juxtaposition', type: 'spell', cost: 0, rarity: 'epic', faction: 'songhai', text: 'Switch positions between ANY two minions.' },
  { id: 20085, name: 'Mana Vortex', type: 'spell', cost: 0, rarity: 'rare', faction: 'songhai', text: 'The next two spells you cast this turn cost 1 less. Draw a card at the end of turn.' },
  { id: 126, name: 'Ace', type: 'minion', race: 'battle pet', cost: 1, rarity: 'common', attack: 1, health: 2, faction: 'songhai', text: '<b>Ranged</b>' },
  { id: 30010, name: 'Bloodrage Mask', type: 'artifact', cost: 1, rarity: 'basic', faction: 'songhai', text: 'Whenever you cast a spell, deal 1 damage to the enemy General.' },
  { id: 30023, name: 'Crescent Spear', type: 'artifact', cost: 1, rarity: 'legendary', faction: 'songhai', text: 'Your General gains +1 Attack. Spells you cast that deal damage deal +1 damage.' },
  { id: 20088, name: 'Ghost Lightning', type: 'spell', cost: 1, rarity: 'basic', faction: 'songhai', text: 'Deal 1 damage to all enemy minions.' },
  { id: 108, name: 'Heartseeker', type: 'minion', cost: 1, rarity: 'common', attack: 1, health: 1, faction: 'songhai', text: '<b>Ranged</b>' },
  { id: 129, name: 'Katara', type: 'minion', cost: 1, rarity: 'common', attack: 1, health: 3, faction: 'songhai', text: '<b>Backstab</b>: (3).' },
  { id: 20168, name: 'Mist Dragon Seal', type: 'spell', cost: 1, rarity: 'common', faction: 'songhai', text: 'Give a friendly minion +1/+1 and teleport it to any space on the battlefield.' },
  { id: 20167, name: 'Mist Walking', type: 'spell', cost: 1, rarity: 'rare', faction: 'songhai', text: 'Teleport your General up to 2 spaces.' },
  { id: 20080, name: 'Saberspine Seal', type: 'spell', cost: 1, rarity: 'basic', faction: 'songhai', text: 'Give a minion or General +3 Attack this turn.' },
  { id: 20192, name: 'Shadow Waltz', type: 'spell', cost: 1, rarity: 'common', faction: 'songhai', text: 'Lower the cost of all minions with <b>Backstab</b> in your action bar by 1 and give them +1/+1.' },
  { id: 20106, name: 'Artifact Defiler', type: 'spell', cost: 2, rarity: 'common', faction: 'songhai', text: 'Destroy all artifacts on the enemy General.' },
  { id: 115, name: 'Chakri Avatar', type: 'minion', race: 'arcanyst', cost: 2, rarity: 'basic', attack: 1, health: 2, faction: 'songhai', text: 'Whenever you cast a spell, this minion gains +1/+1.' },
  { id: 20191, name: 'Crimson Coil', type: 'spell', cost: 2, rarity: 'common', faction: 'songhai', text: 'Deal 2 damage to a minion. Activate your Battle Pets.' },
  { id: 20094, name: 'Deathstrike Seal', type: 'spell', cost: 2, rarity: 'rare', faction: 'songhai', text: 'Give a friendly minion, "Whenever this damages an enemy minion, destroy that minion."' },
  { id: 20143, name: 'Eight Gates', type: 'spell', cost: 2, rarity: 'legendary', faction: 'songhai', text: 'Spells you cast this turn that deal damage deal +2 damage.' },
  { id: 110, name: 'Kaido Assassin', type: 'minion', cost: 2, rarity: 'basic', attack: 2, health: 3, faction: 'songhai', text: '<b>Backstab</b>: (1).' },
  { id: 30007, name: 'Mask of Shadows', type: 'artifact', cost: 2, rarity: 'legendary', faction: 'songhai', text: 'Your General gains <b>Backstab</b> (4).' },
  { id: 20194, name: 'Mirror Meld', type: 'spell', cost: 2, rarity: 'rare', faction: 'songhai', text: 'Summon a copy of a friendly minion that costs 2 of less nearby.' },
  { id: 20081, name: 'Phoenix Fire', type: 'spell', cost: 2, rarity: 'basic', faction: 'songhai', text: 'Deal 3 damage to a minion or General.' },
  { id: 121, name: 'Tusk Boar', type: 'minion', cost: 2, rarity: 'legendary', attack: 2, health: 3, faction: 'songhai', text: '<b>Rush</b><br> Return this minion to your action bar at the beginning of your turn.' },
  { id: 125, name: 'Xho', type: 'minion', race: 'battle pet', cost: 2, rarity: 'rare', attack: 2, health: 3, faction: 'songhai', text: '<b>Dying Wish</b>: Put a random Songhai spell into your action bar. It costs 1 less.' },
  { id: 130, name: 'Battle Panddo', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 4, faction: 'songhai', text: 'Whenever this minion takes damage, deal 1 damage to all enemies.' },
  { id: 117, name: 'Celestial Phantom', type: 'minion', cost: 3, rarity: 'rare', attack: 1, health: 5, faction: 'songhai', text: 'Whenever this damages an enemy minion, destroy that minion.' },
  { id: 30009, name: 'Cyclone Mask', type: 'artifact', cost: 3, rarity: 'epic', faction: 'songhai', text: 'Your General gains <b>Ranged</b>.' },
  { id: 112, name: 'Gore Horn', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'songhai', text: '<b>Backstab</b>: (2). After this minion attacks, it gains +1/+1.' },
  { id: 114, name: 'Jade Monk', type: 'minion', cost: 3, rarity: 'common', attack: 4, health: 3, faction: 'songhai', text: 'Whenever this minion takes damage, deal 1 damage to a random enemy minion.' },
  { id: 128, name: 'Ki Beholder', type: 'minion', cost: 3, rarity: 'rare', attack: 3, health: 2, faction: 'songhai', text: '<b>Ranged</b><br> <b>Opening Gambit</b>: An enemy minion cannot move next turn.' },
  { id: 20102, name: 'Killing Edge', type: 'spell', cost: 3, rarity: 'basic', faction: 'songhai', text: 'Give a friendly minion +4/+2. If that minion has <b>Backstab</b>, draw a card at end of turn.' },
  { id: 122, name: 'Lantern Fox', type: 'minion', cost: 3, rarity: 'epic', attack: 2, health: 4, faction: 'songhai', text: 'Whenever this minion takes damage, put a Phoenix Fire in your action bar.' },
  { id: 20087, name: 'Onyx Bear Seal', type: 'spell', cost: 3, rarity: 'epic', faction: 'songhai', text: 'Transform an enemy minion into a 0/2 Panddo that cannot be attacked.' },
  { id: 20082, name: 'Twin Strike', type: 'spell', cost: 3, rarity: 'common', faction: 'songhai', text: 'Deal 2 damage to exactly two random enemy minions. Draw a card at end of turn.' },
  { id: 109, name: 'Widowmaker', type: 'minion', cost: 3, rarity: 'basic', attack: 2, health: 3, faction: 'songhai', text: '<b>Ranged</b>' },
  { id: 20100, name: 'Ancestral Divination', type: 'spell', cost: 4, rarity: 'common', faction: 'songhai', text: 'Draw a card for each friendly minion on the battlefield.' },
  { id: 116, name: 'Four Winds Magi', type: 'minion', race: 'arcanyst', cost: 4, rarity: 'rare', attack: 4, health: 4, faction: 'songhai', text: 'Whenever you cast a spell, deal 1 damage to enemy General and restore 1 Health to your General.' },
  { id: 120, name: 'Keshrai Fanblade', type: 'minion', cost: 4, rarity: 'common', attack: 5, health: 3, faction: 'songhai', text: '<b>Opening Gambit</b>: Next turn, opponent\'s spells cost 2 more to cast.' },
  { id: 20193, name: 'Pandamonium', type: 'spell', cost: 4, rarity: 'epic', faction: 'songhai', text: 'Transform ALL minions into 0/2 Panddo that cannot be attacked until end of turn.' },
  { id: 124, name: 'Storm Sister Alkyone', type: 'minion', cost: 4, rarity: 'legendary', attack: 3, health: 5, spirit: 0, faction: 'songhai', text: 'Spells you cast that deal damage deal +1 damage.' },
  { id: 119, name: 'Hamon Bladeseeker', type: 'minion', cost: 5, rarity: 'epic', attack: 8, health: 8, faction: 'songhai', text: 'At the start of your turn, deal 2 damage to your General.' },
  { id: 20155, name: `Heaven's Eclipse`, type: 'spell', cost: 5, rarity: 'legendary', faction: 'songhai', text: 'Draw 3 spell cards from your deck.' },
  { id: 127, name: 'Onyx Jaguar', type: 'minion', cost: 5, rarity: 'epic', attack: 3, health: 3, faction: 'songhai', text: 'Whenever a friendly minion is moved for any reason, give it +1/+1.' },
  { id: 111, name: 'Scarlet Viper', type: 'minion', cost: 5, rarity: 'common', attack: 2, health: 5, faction: 'songhai', text: '<b>Flying</b><br> <b>Backstab</b>: (4)' },
  { id: 131, name: 'Grandmaster Zendo', type: 'minion', cost: 6, rarity: 'legendary', attack: 4, health: 6, faction: 'songhai', text: 'The enemy General moves and attacks as if they are a Battle Pet.' },
  { id: 118, name: 'Storm Kage', type: 'minion', cost: 7, rarity: 'legendary', attack: 5, health: 10, faction: 'songhai', text: 'Whenever one of your spells deals damage, put a Kage Lightning in your action bar.' },
  { id: 20217, name: 'Koan of Horns', type: 'spell', cost: 8, rarity: 'legendary', faction: 'songhai', text: 'Transform all minions in your action bar and deck to 0-cost Gore Horns. Draw 3 cards.' },
  { id: 20084, name: 'Spiral Technique', type: 'spell', cost: 8, rarity: 'epic', faction: 'songhai', text: 'Deal 8 damage to a minion or General.' },
]

export default songhai
