const vanar = [
  { name: 'Flash Freeze', type: 'spell', cost: 0, rarity: 'core', faction: 'vanar', text: 'Deal 1 damage to a minion and <b>Stun</b> it.' },
  { name: 'Polarity', type: 'spell', cost: 0, rarity: 'common', faction: 'vanar', text: `Switch ANY minion's Attack and Health.` },
  { name: 'Aspect of the Fox', type: 'spell', cost: 1, rarity: 'core', faction: 'vanar', text: 'Transform ANY minion into a 3/3 Ravager with no abilities.' },
  { name: 'Mesmerize', type: 'spell', cost: 1, rarity: 'rare', faction: 'vanar', text: 'Teleport an enemy minion or General one space.' },
  { name: 'Snow Chaser', type: 'vespyr', cost: 1, rarity: 'rare', attack: 2, health: 1, faction: 'vanar', text: '<b>Infiltrate</b>: When this minion dies, return it to your action bar.' },
  { name: 'Vespyric Call', type: 'spell', cost: 1, rarity: 'epic', faction: 'vanar', text: 'Put a random Vespyr minion into your action bar. It costs 1 less and has +1/+1.' },
  { name: 'Altered Beast', type: 'spell', cost: 2, rarity: 'common', faction: 'vanar', text: 'Transform ANY minion into a random Battle Pet.' },
  { name: 'Bonechill Barrier', type: 'spell', cost: 2, rarity: 'common', faction: 'vanar', text: 'Summon three joined 0/2 Vespyr Walls. Minions that attack these walls are <b>Stunned</b>.' },
  { name: 'Borean Bear', type: 'vespyr', cost: 2, rarity: 'common', attack: 1, health: 3, faction: 'vanar', text: 'Whenever you summon a Vespyr minion, this minion gains +1 Attaack.' },
  { name: 'Boundless Courage', type: 'spell', cost: 2, rarity: 'epic', faction: 'vanar', text: 'Give a friendly minion +2 Attack. It takes no damage this turn.' },
  { name: 'Bur', type: 'battle pet', cost: 2, rarity: 'rare', attack: 3, health: 3, faction: 'vanar', text: 'When this minion survives damage, transform it into a different Battle Pet.' },
  { name: 'Chromatic Cold', type: 'spell', cost: 2, rarity: 'core', faction: 'vanar', text: 'Dispel a space. If there is an enemy minion or General on that space, deal it 2 damage.' },
  { name: 'Coldbiter', type: 'artifact', cost: 2, rarity: 'legendary', faction: 'vanar', text: 'At the end of your turn, your General deals 2 damage to each enemy minion around them.' },
  { name: 'Crystal Cloaker', type: 'vespyr', cost: 2, rarity: 'core', attack: 2, health: 3, faction: 'vanar', text: '<b>Infiltrate</b>: Gains +2 Attack.' },
  { name: 'Crystal Wisp', type: 'minion', cost: 2, rarity: 'common', attack: 1, health: 1, faction: 'vanar', text: '<b>Dying Wish</b>: Permanently gain a mana crystal.' },
  { name: 'Frostfire', type: 'spell', cost: 2, rarity: 'core', faction: 'vanar', text: 'Give a friendly minion +3 Attack. If it is Vespyr, also give it +3 Health.' },
  { name: 'Gravity Well', type: 'spell', cost: 2, rarity: 'legendary', faction: 'vanar', text: 'Summon four joined 0/1 Walls with <b>Provoke</b>.' },
  { name: 'Hailstone Prison', type: 'spell', cost: 2, rarity: 'common', faction: 'vanar', text: 'Return ANY minion to its action bar.' },
  { name: 'Hearth-Sister', type: 'minion', cost: 2, rarity: 'common', attack: 3, health: 2, faction: 'vanar', text: '<b>Opening Gambit</b>: Switch positions with ANY other minion.' },
  { name: 'Icy', type: 'battle pet', cost: 2, rarity: 'common', attack: 2, health: 3, faction: 'vanar', text: '<b>Opening Gambit</b>: Stun a nearby enemy minion or General.' },
  { name: 'Lighting Blitz', type: 'spell', cost: 2, rarity: 'epic', faction: 'vanar', text: 'Give all friendly minions +1/+1 and randomly teleport them to your opponent\'s starting side of the battlefield.' },
  { name: 'Mark of Solitude', type: 'spell', cost: 2, rarity: 'rare', faction: 'vanar', text: 'One minion becomes 5/5. It can no longer attack Generals.' },
  { name: 'Blazing Spines', type: 'spell', cost: 3, rarity: 'rare', faction: 'vanar', text: 'Summon two joined 3/3 Walls that can attack.' },
  { name: 'Cryogenesis', type: 'spell', cost: 3, rarity: 'common', faction: 'vanar', text: 'Deal 4 damage to an enemy minion. Draw a Vespyr minion from your deck.' },
  { name: 'Fenrir Warmaster', type: 'minion', cost: 3, rarity: 'core', attack: 3, health: 2, faction: 'vanar', text: '<b>Dying Wish</b>: Summon a 3/2 Ghost Wolf on this space.' },
  { name: 'Glacial Elemental', type: 'vespyr', cost: 3, rarity: 'rare', attack: 2, health: 3, faction: 'vanar', text: 'Whenever you summon a Vespyr minion, deal 2 damage to a random enemy minion.' },
  { name: 'Iceblade Dryad', type: 'vespyr', cost: 3, rarity: 'epic', attack: 3, health: 3, faction: 'vanar', text: '<b>Opening Gambit</b>: Give a friendly Vespyr minion +1/+1 and <b>Flying</b>.' },
  { name: 'Snow Rippler', type: 'vespyr', cost: 3, rarity: 'common', attack: 3, health: 4, faction: 'vanar', text: '<b>Infiltrate</b>: Whenever this minion damages a General, put a random Battle Pet into your action bar.' },
  { name: 'Snowpiercer', type: 'artifact', cost: 3, rarity: 'core', faction: 'vanar', text: 'Your General gains +3 Attack.' },
  { name: 'Wolfraven', type: 'minion', cost: 3, rarity: 'common', attack: 1, health: 4, faction: 'vanar', text: '<b>Flying</b><br> <b>Infiltrate</b>: Gains +3 Attack.' },
  { name: 'Aspect of the Drake', type: 'spell', cost: 4, rarity: 'epic', faction: 'vanar', text: 'Transform ANY minion into a 4/4 Whyte Drake with <b>Flying</b>. Nearby friendly minions gain <b>Flying</b>.' },
  { name: 'Avalanche', type: 'spell', cost: 4, rarity: 'core', faction: 'vanar', text: 'Deal 4 damage to ALL minions and Generals on your starting side of the battlefield and <b>Stun</b> them.' },
  { name: 'Razorback', type: 'minion', cost: 4, rarity: 'rare', attack: 4, health: 3, faction: 'vanar', text: '<b>Opening Gamit</b>: Give all friendly minions +2 Attack this turn.' },
  { name: 'Voice of the Wind', type: 'minion', cost: 4, rarity: 'legendary', attack: 4, health: 4, faction: 'vanar', text: 'Whenever you summon a minion from your action bar, summon a 2/2 Vespyr Winter Maerid bnearby.' },
  { name: 'Wailing Overdrive', type: 'spell', cost: 4, rarity: 'common', faction: 'vanar', text: `Give a friendly minion on your opponent's starting side of the battlefield +5/+5.` },
  { name: 'White Asp', type: 'artifact', cost: 4, rarity: 'legendary', faction: 'vanar', text: 'Your General gains +3 Attack. Whenever your General destroys a minion, summon a 3/3 Balzing Spine Wall on that space.' },
  { name: 'Wind Sister Maia', type: 'minion', cost: 4, rarity: 'legendary', attack: 4, health: 5, faction: 'vanar', text: 'Whenever you summon a minion with <b>Infiltrate</b>, give it +1/+1.' },
  { name: 'Winterblade', type: 'artifact', cost: 4, rarity: 'epic', faction: 'vanar', text: 'Your General gains +2 Attack. Enemy minions damaged by your General are <b>Stunned</b>.' },
  { name: 'Arctic Displacer', type: 'vespyr', cost: 5, rarity: 'core', attack: 10, health: 4, faction: 'vanar', text: '<b>Airdrop</b>' },
  { name: 'Frostburn', type: 'spell', cost: 5, rarity: 'rare', faction: 'vanar', text: 'Deal 3 damage to all enemy minions.' },
  { name: 'Frosthorn Rhyno', type: 'minion', cost: 5, rarity: 'epic', attack: 6, health: 5, faction: 'vanar', text: '<b>Infiltrate</b>: Gains +1 Attack and <b>Celerity</b>.' },
  { name: 'Frostiva', type: 'minion', cost: 5, rarity: 'legendary', attack: 3, health: 3, faction: 'vanar', text: '<b>Forcefield</b><br> Whenever this minion attacks or is attacked, summon a 3/3 Vespyr Night Howler nearby.' },
  { name: 'Huldra', type: 'minion', cost: 5, rarity: 'rare', attack: 3, health: 4, faction: 'vanar', text: '<b>Opening Gambit</b>: Give a friendly Vespyr minion <b>Celerity</b>.' },
  { name: 'Spirit of the Wild', type: 'spell', cost: 5, rarity: 'epic', faction: 'vanar', text: 'Reactivate friendly minions on your opponent\'s starting side of the battlefield.' },
  { name: 'Aspect of the Mountains', type: 'spell', cost: 6, rarity: 'legendary', faction: 'vanar', text: 'Transform ANY minion into a 5/5 Seismic Elemental. Deal 5 damage to enemy minions around it.' },
  { name: 'Draugar Lord', type: 'vespyr', cost: 6, rarity: 'epic', attack: 4, health: 8, faction: 'vanar', text: '<b>Dying Wish</b>: Summon a 4/8 Ice Drake on this space.' },
  { name: 'Ancient Grove', type: 'vespyr', cost: 7, rarity: 'legendary', attack: 7, health: 7, faction: 'vanar', text: '<b>Provoke</b><br> <b>Opening Gambit</b>: You rminions gain "<b>Dying Wish</b>: Summon a 1/1 Treant with <b>Provoke</b>."' },
  { name: 'Winter\'s Wake', type: 'spell', cost: 8, rarity: 'legendary', faction: 'vanar', text: 'Give all friendly Wall minions +4/+4. Those minions can now move.' },
]

export default vanar
