/* eslint-disable */
const vanar = [{
  "id": 20139,
  "name": "Flash Freeze",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 0,
  "rarity": "basic",
  "faction": "vanar",
  "text": "Deal 1 damage to a minion and <b>Stun</b> it.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20150,
  "name": "Polarity",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 0,
  "rarity": "common",
  "faction": "vanar",
  "text": "Switch ANY minion's Attack and Health.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20144,
  "name": "Aspect of the Ravager",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "basic",
  "faction": "vanar",
  "text": "Transform ANY minion into a 3/3 Ravager with no abilities.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 30031,
  "name": "Iceshatter Gauntlet",
  "set": "ancient bonds",
  "type": "artifact",
  "race": "",
  "cost": 1,
  "rarity": "rare",
  "faction": "vanar",
  "text": "Whenever your General attacks a stunned minion, destroy it instantly.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20261,
  "name": "Mana Deathgrip",
  "set": "ancient bonds",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "common",
  "faction": "vanar",
  "text": "Deal 1 damage to an enemy minion. If it dies this turn, permanently gain 1 mana crystal.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20138,
  "name": "Mesmerize",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "rare",
  "faction": "vanar",
  "text": "Teleport an enemy one space.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 510,
  "name": "Snow Chaser",
  "set": "core",
  "type": "minion",
  "race": "Vespyr",
  "cost": 1,
  "rarity": "rare",
  "faction": "vanar",
  "text": "<b>Infiltrate</b>: When this minion dies, return it to your action bar.",
  "attack": 2,
  "health": 1,
  "spirit": null
}, {
  "id": 20209,
  "name": "Vespyric Call",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 1,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Put a random Vespyr minion into your action bar. It costs 1 less and has +1/+1.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20214,
  "name": "Aspect of Shim'Zar",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "Transform ANY minion into a random Battle Pet.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20149,
  "name": "Bonechill Barrier",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "Summon three joined 0/2 Vespyr Walls.  Minions that attack these walls are <b>Stunned</b>.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 512,
  "name": "Borean Bear",
  "set": "core",
  "type": "minion",
  "race": "Vespyr",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "Whenever you summon a Vespyr minion, this minion gains +1 Attack.",
  "attack": 1,
  "health": 3,
  "spirit": null
}, {
  "id": 20137,
  "name": "Boundless Courage",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Give a friendly minion +2 Attack. It takes no damage this turn.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 531,
  "name": "Bur",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 2,
  "rarity": "rare",
  "faction": "vanar",
  "text": "When this minion survives damage, transform it into a different Battle Pet.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 20134,
  "name": "Chromatic Cold",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "vanar",
  "text": "Dispel a space. If there is an enemy on that space, deal it 2 damage.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 540,
  "name": "Circulus",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 2,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Whenever you cast a spell, add a 2/1 Illusion to your action bar.",
  "attack": 1,
  "health": 1,
  "spirit": 0
}, {
  "id": 30016,
  "name": "Coldbiter",
  "set": "core",
  "type": "artifact",
  "race": "",
  "cost": 2,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "At the end of your turn, your General deals 2 damage to each enemy minion around them.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20228,
  "name": "Concealing Shroud",
  "set": "bloodbound",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "rare",
  "faction": "vanar",
  "text": "Your General takes no damage until your next turn.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 550,
  "name": "Crystal Arbiter",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "Vespyr",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "This minion has +3 Attack on your opponent's turn.",
  "attack": 1,
  "health": 4,
  "spirit": null
}, {
  "id": 505,
  "name": "Crystal Cloaker",
  "set": "core",
  "type": "minion",
  "race": "Vespyr",
  "cost": 2,
  "rarity": "basic",
  "faction": "vanar",
  "text": "<b>Infiltrate</b>: Gains +2 Attack.",
  "attack": 2,
  "health": 3,
  "spirit": 0
}, {
  "id": 506,
  "name": "Crystal Wisp",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Dying Wish</b>: Permanently gain 1 mana crystal.",
  "attack": 1,
  "health": 1,
  "spirit": null
}, {
  "id": 20237,
  "name": "Frigid Corona",
  "set": "bloodbound",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Stun</b> an enemy. Draw a card.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20135,
  "name": "Frostfire",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "basic",
  "faction": "vanar",
  "text": "Give a friendly minion +3 Attack. If it is Vespyr, also give it +3 Health.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20147,
  "name": "Gravity Well",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Summon four joined 0/1 Walls with <b>Provoke</b>.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20160,
  "name": "Hailstone Prison",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "Return ANY minion to its action bar.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 517,
  "name": "Hearth-Sister",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Opening Gambit</b>: Switch positions with ANY other minion.",
  "attack": 3,
  "health": 2,
  "spirit": null
}, {
  "id": 530,
  "name": "Icy",
  "set": "shimzar",
  "type": "minion",
  "race": "Battle Pet",
  "cost": 2,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Opening Gambit</b>: Stun a nearby enemy.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 20211,
  "name": "Lightning Blitz",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Give all friendly minions +1/+1 and randomly teleport them to your opponent's starting side of the battlefield.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20140,
  "name": "Mark of Solitude",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 2,
  "rarity": "rare",
  "faction": "vanar",
  "text": "One minion becomes 5/5. It can no longer attack Generals.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 545,
  "name": "Shivers",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "Vespyr",
  "cost": 2,
  "rarity": "epic",
  "faction": "vanar",
  "text": "<b>Flying</b><br/><b>Infiltrate</b>: When this minion attacks, permanently gain 1 mana crystal.",
  "attack": 2,
  "health": 1,
  "spirit": null
}, {
  "id": 20148,
  "name": "Blazing Spines",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "vanar",
  "text": "Summon two joined 3/3 Walls that can attack.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 548,
  "name": "Drake Dowager",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "vanar",
  "text": "<b>Sentinel</b>: General attacks.<br/><b>Ranged</b><br/>Whenever this attacks, summon a 4/4 Flying Drake nearby.",
  "attack": 1,
  "health": 3,
  "spirit": null
}, {
  "id": 503,
  "name": "Fenrir Warmaster",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "basic",
  "faction": "vanar",
  "text": "<b>Dying Wish</b>: Summon a 3/2 Ghost Wolf on this space.",
  "attack": 3,
  "health": 2,
  "spirit": 0
}, {
  "id": 547,
  "name": "Freeblade",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Sentinel</b>: Minion summoned.<br/>This switches positions with the minion that transformed it.",
  "attack": 3,
  "health": 5,
  "spirit": null
}, {
  "id": 519,
  "name": "Glacial Elemental",
  "set": "core",
  "type": "minion",
  "race": "Vespyr",
  "cost": 3,
  "rarity": "rare",
  "faction": "vanar",
  "text": "Whenever you summon a Vespyr minion, deal 2 damage to a random enemy minion.",
  "attack": 2,
  "health": 3,
  "spirit": null
}, {
  "id": 20266,
  "name": "Glacial Fissure",
  "set": "unearthed prophecy",
  "type": "spell",
  "race": "",
  "cost": 3,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Deal 8 damage to EVERYTHING in the center column.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 533,
  "name": "Iceblade Dryad",
  "set": "shimzar",
  "type": "minion",
  "race": "Vespyr",
  "cost": 3,
  "rarity": "epic",
  "faction": "vanar",
  "text": "<b>Opening Gambit</b>: Give a friendly Vespyr minion +1/+1 and <b>Flying</b>.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 539,
  "name": "Kindred Hunter",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 3,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Bond</b>: Summon a 3/3 Night Howler on a random nearby space.",
  "attack": 3,
  "health": 3,
  "spirit": 0
}, {
  "id": 549,
  "name": "Moonlit Basilysk",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "rare",
  "faction": "vanar",
  "text": "<b>Sentinel</b>: Spell cast.<br/>Whenever your opponent casts a spell, this minion gains +3/+3.",
  "attack": 2,
  "health": 2,
  "spirit": null
}, {
  "id": 536,
  "name": "Myriad",
  "set": "bloodbound",
  "type": "minion",
  "race": "Vespyr",
  "cost": 3,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Blood Surge</b>: Summon a random Wall nearby.",
  "attack": 3,
  "health": 3,
  "spirit": 0
}, {
  "id": 529,
  "name": "Snow Rippler",
  "set": "shimzar",
  "type": "minion",
  "race": "Vespyr",
  "cost": 3,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Infiltrate</b>: Whenever this minion damages a General, put a random Battle Pet into your action bar.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 30015,
  "name": "Snowpiercer",
  "set": "core",
  "type": "artifact",
  "race": "",
  "cost": 3,
  "rarity": "basic",
  "faction": "vanar",
  "text": "Your General gains +3 Attack.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 30035,
  "name": "The Dredger",
  "set": "unearthed prophecy",
  "type": "artifact",
  "race": "",
  "cost": 3,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Whenever your General damages an enemy, randomly teleport them to your starting side of the battlefield.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 511,
  "name": "Wolfraven",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 3,
  "rarity": "common",
  "faction": "vanar",
  "text": "<b>Flying</b><br><b>Infiltrate</b>: Gains +3 Attack.",
  "attack": 1,
  "health": 4,
  "spirit": null
}, {
  "id": 20145,
  "name": "Aspect of the Wyrm",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Transform ANY minion into a 4/4 Whyte Drake with <b>Flying</b>. Nearby friendly minions gain <b>Flying</b>.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20136,
  "name": "Avalanche",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "basic",
  "faction": "vanar",
  "text": "Deal 4 damage to everything on your starting side of the battlefield and <b>Stun</b> them.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20298,
  "name": "Blinding Snowstorm",
  "set": "unearthed prophecy",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "vanar",
  "text": "Deal 1 damage to all enemies. Those enemies can only move 1 space next turn.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20165,
  "name": "Cryogenesis",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "vanar",
  "text": "Deal 4 damage to an enemy minion. Draw a Vespyr minion from your deck.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 513,
  "name": "Razorback",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "vanar",
  "text": "<b>Opening Gambit</b>: Give all friendly minions +2 Attack this turn.",
  "attack": 4,
  "health": 3,
  "spirit": null
}, {
  "id": 537,
  "name": "Sleet Dasher",
  "set": "bloodbound",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "rare",
  "faction": "vanar",
  "text": "Whenever this minion destroys an enemy, reactivate it.",
  "attack": 3,
  "health": 6,
  "spirit": 0
}, {
  "id": 515,
  "name": "Voice of the Wind",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Whenever you summon a minion from your action bar, summon a 2/2 Vespyr Winter Maerid into a nearby space.",
  "attack": 4,
  "health": 4,
  "spirit": null
}, {
  "id": 20208,
  "name": "Wailing Overdrive",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 4,
  "rarity": "common",
  "faction": "vanar",
  "text": "Give a friendly minion on your opponent's starting side of the battlefield +5/+5.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 30021,
  "name": "White Asp",
  "set": "shimzar",
  "type": "artifact",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Your General gains +3 Attack. Whenever your General destroys a minion, summon a 3/3 Blazing Spine Wall on that space.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 528,
  "name": "Wind Sister Maia",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 4,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Whenever you summon a minion with <b>Infiltrate</b>, give it +1/+1.",
  "attack": 4,
  "health": 5,
  "spirit": 0
}, {
  "id": 30019,
  "name": "Winterblade",
  "set": "core",
  "type": "artifact",
  "race": "",
  "cost": 4,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Your General gains +2 Attack. Enemy minions damaged by your General are <b>Stunned</b>.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 526,
  "name": "Arctic Displacer",
  "set": "core",
  "type": "minion",
  "race": "Vespyr",
  "cost": 5,
  "rarity": "basic",
  "faction": "vanar",
  "text": "<b>Airdrop</b>",
  "attack": 10,
  "health": 4,
  "spirit": 0
}, {
  "id": 20229,
  "name": "Enfeeble",
  "set": "bloodbound",
  "type": "spell",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "vanar",
  "text": "All minions become 1/1.",
  "attack": null,
  "health": null,
  "spirit": 0
}, {
  "id": 20207,
  "name": "Frostburn",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 5,
  "rarity": "rare",
  "faction": "vanar",
  "text": "Deal 3 damage to all enemy minions.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 507,
  "name": "Frosthorn Rhyno",
  "set": "core",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "vanar",
  "text": "<b>Infiltrate</b>: Gains +1 Attack and <b>Celerity</b>.",
  "attack": 6,
  "health": 5,
  "spirit": null
}, {
  "id": 534,
  "name": "Frostiva",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "<b>Forcefield</b><br>Whenever this minion attacks or is attacked, summon a 3/3 Vespyr Night Howler nearby.",
  "attack": 3,
  "health": 3,
  "spirit": null
}, {
  "id": 532,
  "name": "Huldra",
  "set": "shimzar",
  "type": "minion",
  "race": "",
  "cost": 5,
  "rarity": "rare",
  "faction": "vanar",
  "text": "<b>Opening Gambit</b>: Give a friendly Vespyr minion <b>Celerity</b>.",
  "attack": 3,
  "health": 4,
  "spirit": null
}, {
  "id": 20276,
  "name": "Luminous Charge",
  "set": "unearthed prophecy",
  "type": "spell",
  "race": "",
  "cost": 5,
  "rarity": "rare",
  "faction": "vanar",
  "text": "Summon five joined 0/1 Walls that deal 2 damage to nearby enemies when destroyed.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20163,
  "name": "Spirit of the Wild",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 5,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Reactivate friendly minions on your opponent's starting side of the battlefield.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20289,
  "name": "Vespyrian Might",
  "set": "unearthed prophecy",
  "type": "spell",
  "race": "",
  "cost": 5,
  "rarity": "common",
  "faction": "vanar",
  "text": "Give a Vespyr minion +2/+2 for each friendly Vespyr.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 20146,
  "name": "Aspect of the Mountains",
  "set": "core",
  "type": "spell",
  "race": "",
  "cost": 6,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Transform ANY minion into a 5/5 Seismic Elemental. Deal 5 damage to enemy minions around it.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 508,
  "name": "Draugar Lord",
  "set": "core",
  "type": "minion",
  "race": "Vespyr",
  "cost": 6,
  "rarity": "epic",
  "faction": "vanar",
  "text": "<b>Dying Wish</b>: Summon a 4/8 Ice Drake on this space.",
  "attack": 4,
  "health": 8,
  "spirit": null
}, {
  "id": 20295,
  "name": "Icebreak Ambush",
  "set": "unearthed prophecy",
  "type": "spell",
  "race": "",
  "cost": 6,
  "rarity": "epic",
  "faction": "vanar",
  "text": "Summon an ambush of <b>Infiltrate</b> minions on your opponent's starting side of the battlefield.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 514,
  "name": "Ancient Grove",
  "set": "core",
  "type": "minion",
  "race": "Vespyr",
  "cost": 7,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "<b>Provoke</b><br><b>Opening Gambit</b>: Your minions gain \"<b>Dying Wish</b>: Summon a 1/1 Treant with <b>Provoke</b>\".",
  "attack": 7,
  "health": 7,
  "spirit": null
}, {
  "id": 20293,
  "name": "Flawless Reflection",
  "set": "unearthed prophecy",
  "type": "spell",
  "race": "",
  "cost": 7,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Choose a minion. Transform ALL nearby minions into copies of it.",
  "attack": null,
  "health": null,
  "spirit": null
}, {
  "id": 541,
  "name": "Ghost Seraphim",
  "set": "ancient bonds",
  "type": "minion",
  "race": "Arcanyst",
  "cost": 7,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "The first spell you cast each turn costs 0.",
  "attack": 8,
  "health": 9,
  "spirit": 0
}, {
  "id": 538,
  "name": "Grandmaster Embla",
  "set": "bloodbound",
  "type": "minion",
  "race": "",
  "cost": 8,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "<b>Opening Gambit</b>: Surround the enemy General with random Walls.",
  "attack": 5,
  "health": 5,
  "spirit": 0
}, {
  "id": 543,
  "name": "Matron Elveiti",
  "set": "unearthed prophecy",
  "type": "minion",
  "race": "",
  "cost": 8,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Minions cannot attack your General.",
  "attack": 7,
  "health": 5,
  "spirit": null
}, {
  "id": 20212,
  "name": "Winter's Wake",
  "set": "shimzar",
  "type": "spell",
  "race": "",
  "cost": 8,
  "rarity": "legendary",
  "faction": "vanar",
  "text": "Give all friendly Wall minions +4/+4. Those minions can now move.",
  "attack": null,
  "health": null,
  "spirit": null
}];

export default vanar
