const vanar = [
  {
    id: 20139,
    name: 'Flash Freeze',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'basic',
    faction: 'vanar',
    text: 'Deal 1 damage to a minion and <b>Stun</b> it.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20150,
    name: 'Polarity',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 0,
    rarity: 'common',
    faction: 'vanar',
    text: "Switch ANY minion's Attack and Health.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20393,
    name: 'Aspect of Ego',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'vanar',
    text: 'Transform ANY minion into a random minion of the same cost.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20329,
    name: 'Essence Sculpt',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'vanar',
    text:
      'Choose a <b>Stunned</b> minion. Put a copy of that card into your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30031,
    name: 'Iceshatter Gauntlet',
    set: 'ancients',
    type: 'artifact',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'vanar',
    text:
      'Whenever your General attacks a <b>Stunned</b> minion, destroy it instantly.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20261,
    name: 'Mana Deathgrip',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'vanar',
    text:
      'Deal 1 damage to an enemy minion. If it dies this turn, permanently gain 1 mana crystal.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20138,
    name: 'Mesmerize',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'rare',
    faction: 'vanar',
    text: 'Teleport an enemy one space.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 510,
    name: 'Snow Chaser',
    set: 'core',
    type: 'minion',
    race: 'Vespyr',
    cost: 1,
    rarity: 'rare',
    faction: 'vanar',
    text:
      '<b>Infiltrate</b>:  When this minion dies, return it to your action bar.',
    attack: 2,
    health: 1,
    spirit: null
  },
  {
    id: 20209,
    name: 'Vespyric Call',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'epic',
    faction: 'vanar',
    text:
      'Put a random Vespyr minion into your action bar. It costs 1 less and has +1/+1.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20375,
    name: 'Wanderlust',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 1,
    rarity: 'common',
    faction: 'vanar',
    text:
      '<b>Intensify</b>: Teleport 1 random enemy minion to a space on your starting side of the battlefield.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20214,
    name: "Aspect of Shim'Zar",
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: 'Transform ANY minion into a random Battle Pet.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20324,
    name: 'Aspect of the Bear',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text:
      'Transform ANY minion into a 4/5 Ursaplomb that will not counterattack.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20144,
    name: 'Aspect of the Ravager',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'vanar',
    text: 'Transform ANY minion into a 3/3 Ravager with no abilities.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20149,
    name: 'Bonechill Barrier',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text:
      'Summon three joined 0/2 Vespyr Walls.  Minions that attack these walls are <b>Stunned</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 512,
    name: 'Borean Bear',
    set: 'core',
    type: 'minion',
    race: 'Vespyr',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: 'Whenever you summon a Vespyr minion, this minion gains +1 Attack.',
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 20137,
    name: 'Boundless Courage',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'vanar',
    text: 'Give a friendly minion +2 Attack. It takes no damage this turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 531,
    name: 'Bur',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 2,
    rarity: 'rare',
    faction: 'vanar',
    text:
      'When this minion survives damage, transform it into a different Battle Pet.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 20134,
    name: 'Chromatic Cold',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'vanar',
    text:
      'Dispel a space. If there is an enemy on that space, deal it 1 damage.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 540,
    name: 'Circulus',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 2,
    rarity: 'epic',
    faction: 'vanar',
    text: 'Whenever you cast a spell, add a 2/1 Illusion to your action bar.',
    attack: 1,
    health: 1,
    spirit: null
  },
  {
    id: 30016,
    name: 'Coldbiter',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      'At the end of your turn, your General deals 2 damage to each enemy minion around them.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20228,
    name: 'Concealing Shroud',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'vanar',
    text: 'Your General takes no damage until your next turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 555,
    name: 'Cryoblade',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: 'Deals double damage to <b>Stunned</b> enemies.',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 550,
    name: 'Crystal Arbiter',
    set: 'unearthed',
    type: 'minion',
    race: 'Vespyr',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: "This minion has +3 Attack on your opponent's turn.",
    attack: 1,
    health: 4,
    spirit: null
  },
  {
    id: 505,
    name: 'Crystal Cloaker',
    set: 'core',
    type: 'minion',
    race: 'Vespyr',
    cost: 2,
    rarity: 'basic',
    faction: 'vanar',
    text: '<b>Infiltrate</b>: Gain +2 Attack.',
    attack: 2,
    health: 3,
    spirit: 0
  },
  {
    id: 506,
    name: 'Crystal Wisp',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Dying Wish</b>: Permanently gain 1 mana crystal.',
    attack: 1,
    health: 1,
    spirit: null
  },
  {
    id: 20237,
    name: 'Frigid Corona',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Stun</b> an enemy. Draw a card.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20135,
    name: 'Frostfire',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'basic',
    faction: 'vanar',
    text:
      'Give a friendly minion +3 Attack. If it is Vespyr, also give it +3 Health.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20147,
    name: 'Gravity Well',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'legendary',
    faction: 'vanar',
    text: 'Summon four joined 0/1 Walls with <b>Provoke</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20160,
    name: 'Hailstone Prison',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: 'Return ANY minion to its action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 517,
    name: 'Hearth-Sister',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Opening Gambit</b>: Switch positions with ANY other minion.',
    attack: 3,
    health: 2,
    spirit: null
  },
  {
    id: 530,
    name: 'Icy',
    set: 'shimzar',
    type: 'minion',
    race: 'Battle Pet',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Opening Gambit</b>: <b>Stun</b> a nearby enemy.',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 20211,
    name: 'Lightning Blitz',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'vanar',
    text:
      "Give all friendly minions +1/+1 and randomly teleport them to your opponent's starting side of the battlefield.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20140,
    name: 'Mark of Solitude',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'rare',
    faction: 'vanar',
    text: 'One minion becomes 5/5. It can no longer attack Generals.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 554,
    name: 'Protosensor',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Build</b>: (1).<br/><b>Airdrop</b>',
    attack: 2,
    health: 2,
    spirit: null
  },
  {
    id: 30056,
    name: 'Resonance Scythe',
    set: 'mythron',
    type: 'artifact',
    race: '',
    cost: 2,
    rarity: 'epic',
    faction: 'vanar',
    text:
      'Your General has +1 Attack.<br/>Reactivate your General whenever they destroy a <b>Stunned</b> enemy.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20337,
    name: 'Shatter',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: 'Destroy a <b>Stunned</b> enemy minion.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 545,
    name: 'Shivers',
    set: 'unearthed',
    type: 'minion',
    race: 'Vespyr',
    cost: 2,
    rarity: 'epic',
    faction: 'vanar',
    text:
      '<b>Flying</b><br/><b>Infiltrate</b>: When this minion attacks, permanently gain 1 mana crystal.',
    attack: 2,
    health: 1,
    spirit: null
  },
  {
    id: 567,
    name: 'Thicket Augur',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 2,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Intensify</b>: Summon 1 Treant with <b>Provoke</b> nearby.',
    attack: 1,
    health: 1,
    spirit: null
  },
  {
    id: 20148,
    name: 'Blazing Spines',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'vanar',
    text: 'Summon two joined 3/3 Walls that can attack.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20371,
    name: 'Cryonic Potential',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vanar',
    text: 'Give an exhausted friendly minion +6/+6.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20347,
    name: 'Crystalline Reinforcement',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'vanar',
    text: 'Double the Attack and Health buffs of friendly minions.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 565,
    name: 'Disciple of Yggdra',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      "When an enemy is <b>Stunned</b>, transform this minion into Yggdra's Voracity.",
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 548,
    name: 'Drake Dowager',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'vanar',
    text:
      '<b>Sentinel</b>: General attacks.<br/><b>Ranged</b><br/>Whenever this attacks, summon a 4/4 Flying Drake nearby.',
    attack: 1,
    health: 3,
    spirit: null
  },
  {
    id: 503,
    name: 'Fenrir Warmaster',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'vanar',
    text: '<b>Dying Wish</b>: Summon a 3/2 Ghost Wolf on this space.',
    attack: 3,
    health: 2,
    spirit: 0
  },
  {
    id: 547,
    name: 'Freeblade',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vanar',
    text:
      '<b>Sentinel</b>: Minion summoned.<br/>This switches positions with the minion that transformed it.',
    attack: 3,
    health: 5,
    spirit: null
  },
  {
    id: 519,
    name: 'Glacial Elemental',
    set: 'core',
    type: 'minion',
    race: 'Vespyr',
    cost: 3,
    rarity: 'rare',
    faction: 'vanar',
    text:
      'Whenever you summon a Vespyr minion, deal 2 damage to a random enemy minion.',
    attack: 2,
    health: 3,
    spirit: null
  },
  {
    id: 20266,
    name: 'Glacial Fissure',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'vanar',
    text: 'Deal 8 damage to EVERYTHING in the center column.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 533,
    name: 'Iceblade Dryad',
    set: 'shimzar',
    type: 'minion',
    race: 'Vespyr',
    cost: 3,
    rarity: 'epic',
    faction: 'vanar',
    text:
      '<b>Opening Gambit</b>: Give a friendly Vespyr minion +1/+1 and <b>Flying</b>.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 539,
    name: 'Kindred Hunter',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 3,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Bond</b>: Summon a 3/3 Night Howler on a random nearby space.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 549,
    name: 'Moonlit Basilysk',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'rare',
    faction: 'vanar',
    text:
      '<b>Sentinel</b>: Spell cast.<br/>Whenever your opponent casts a spell, this minion gains +3/+3.',
    attack: 2,
    health: 2,
    spirit: null
  },
  {
    id: 536,
    name: 'Myriad',
    set: 'ancients',
    type: 'minion',
    race: 'Vespyr',
    cost: 3,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Blood Surge</b>: Summon a random Wall nearby.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 20394,
    name: 'Permafrost',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 3,
    rarity: 'epic',
    faction: 'vanar',
    text:
      '<b>Stun</b> an enemy minion.<br/><b><b>Stun</b>ned</b> enemy minions <b>Stun</b> a nearby enemy.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 529,
    name: 'Snow Rippler',
    set: 'shimzar',
    type: 'minion',
    race: 'Vespyr',
    cost: 3,
    rarity: 'common',
    faction: 'vanar',
    text:
      '<b>Infiltrate</b>: Whenever this minion damages a General, put a random Battle Pet into your action bar.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 30015,
    name: 'Snowpiercer',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'basic',
    faction: 'vanar',
    text: 'Your General gains +3 Attack.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 30035,
    name: 'The Dredger',
    set: 'unearthed',
    type: 'artifact',
    race: '',
    cost: 3,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      'Whenever your General damages an enemy, randomly teleport them to your starting side of the battlefield.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 511,
    name: 'Wolfraven',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 3,
    rarity: 'common',
    faction: 'vanar',
    text: '<b>Flying</b><br/><b>Infiltrate</b>: Gain +3 Attack.',
    attack: 1,
    health: 4,
    spirit: null
  },
  {
    id: 20145,
    name: 'Aspect of the Wyrm',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'vanar',
    text:
      'Transform ANY minion into a 4/4 Whyte Drake with <b>Flying</b>. Nearby friendly minions gain <b>Flying</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20136,
    name: 'Avalanche',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'basic',
    faction: 'vanar',
    text:
      'Deal 4 damage to everything on your starting side of the battlefield and <b>Stun</b> them.',
    attack: null,
    health: null,
    spirit: 0
  },
  {
    id: 20298,
    name: 'Blinding Snowstorm',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'vanar',
    text:
      'Deal 1 damage to all enemies. Those enemies can only move 1 space next turn.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20165,
    name: 'Cryogenesis',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'vanar',
    text:
      'Deal 4 damage to an enemy minion. Draw a Vespyr minion from your deck.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 557,
    name: 'Denadoro',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'vanar',
    text: 'Your minions are always infiltrated.',
    attack: 4,
    health: 5,
    spirit: null
  },
  {
    id: 20391,
    name: 'Endless Hunt',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'vanar',
    text:
      'Summon a 3/3 Vespyr Night Howler.<br/>Put an Endless Hunt into your action bar.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 542,
    name: 'Hydrogarm',
    set: 'immortal',
    type: 'minion',
    race: 'Vespyr',
    cost: 4,
    rarity: 'epic',
    faction: 'vanar',
    text:
      '<b>Blood Surge</b>: Deal 1 damage to enemy minions in this row and <b>Stun</b> them.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 561,
    name: 'Malicious Wisp',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'vanar',
    text:
      '<b>Opening Gambit</b>: Take a mana crystal from your opponent.<br/><b>Dying Wish</b>: Give back the mana crystal.',
    attack: 4,
    health: 3,
    spirit: null
  },
  {
    id: 563,
    name: 'Meltwater Moose',
    set: 'mythron',
    type: 'minion',
    race: 'Vespyr',
    cost: 4,
    rarity: 'common',
    faction: 'vanar',
    text: 'When this minion is summoned, <b>Stun</b> it.',
    attack: 6,
    health: 7,
    spirit: null
  },
  {
    id: 513,
    name: 'Razorback',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'vanar',
    text:
      '<b>Opening Gambit</b>: Give all friendly minions +2 Attack this turn.',
    attack: 4,
    health: 3,
    spirit: null
  },
  {
    id: 537,
    name: 'Sleet Dasher',
    set: 'ancients',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'rare',
    faction: 'vanar',
    text: 'Whenever this minion destroys an enemy, reactivate it.',
    attack: 3,
    health: 6,
    spirit: null
  },
  {
    id: 515,
    name: 'Voice of the Wind',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      'Whenever you summon a minion from your action bar, summon a 2/2 Vespyr Winter Maerid nearby.',
    attack: 4,
    health: 4,
    spirit: null
  },
  {
    id: 20208,
    name: 'Wailing Overdrive',
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'common',
    faction: 'vanar',
    text:
      "Give a friendly minion on your opponent's starting side of the battlefield +5/+5.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30021,
    name: 'White Asp',
    set: 'shimzar',
    type: 'artifact',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      'Your General gains +3 Attack. Whenever your General destroys a minion, summon a 3/3 Blazing Spine Wall on that space.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 528,
    name: 'Wind Sister Maia',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 4,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      'Whenever you summon a minion with <b>Infiltrate</b>, it gains +1/+1.',
    attack: 4,
    health: 5,
    spirit: 0
  },
  {
    id: 30019,
    name: 'Winterblade',
    set: 'core',
    type: 'artifact',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'vanar',
    text:
      'Your General gains +2 Attack. Enemy minions damaged by your General are <b>Stunned</b>.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20330,
    name: 'Wintertide',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 4,
    rarity: 'epic',
    faction: 'vanar',
    text: 'Summon three 2/2 Vespyr Winter Maerids on any column.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 30040,
    name: 'Animus Plate',
    set: 'immortal',
    type: 'artifact',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'vanar',
    text:
      'Your General gains +2 Attack.<br/>Whenever your General attacks or counterattacks, give all friendly Vespyr minions +2/+2.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 526,
    name: 'Arctic Displacer',
    set: 'core',
    type: 'minion',
    race: 'Vespyr',
    cost: 5,
    rarity: 'basic',
    faction: 'vanar',
    text: '<b>Airdrop</b>',
    attack: 10,
    health: 4,
    spirit: 0
  },
  {
    id: 20343,
    name: 'Auroraboros',
    set: 'immortal',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      'Give friendly minions "<b>Dying Wish</b>: Re-summon this minion on this space."',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 560,
    name: 'Cloudcaller',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      '<b>Opening Gambit</b>: Your Bloodbound Spell refreshes and is Lesser Waterball this turn.',
    attack: 4,
    health: 5,
    spirit: null
  },
  {
    id: 20229,
    name: 'Enfeeble',
    set: 'ancients',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'vanar',
    text: 'All minions become 1/1.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 562,
    name: 'Fenrir Berserker',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'vanar',
    text: '<b>Dying Wish</b>: Summon a Fenrir Warmaster on this space.',
    attack: 4,
    health: 3,
    spirit: null
  },
  {
    id: 507,
    name: 'Frosthorn Rhyno',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'vanar',
    text: '<b>Infiltrate</b>: Gain +1 Attack and <b>Celerity</b>.',
    attack: 6,
    health: 5,
    spirit: null
  },
  {
    id: 534,
    name: 'Frostiva',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      '<b>Forcefield</b><br/>Whenever this minion attacks or is attacked, summon a 3/3 Vespyr Night Howler nearby.',
    attack: 3,
    health: 3,
    spirit: null
  },
  {
    id: 532,
    name: 'Huldra',
    set: 'shimzar',
    type: 'minion',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'vanar',
    text:
      '<b>Opening Gambit</b>: Give a friendly Vespyr minion <b>Celerity</b>.',
    attack: 3,
    health: 4,
    spirit: null
  },
  {
    id: 20276,
    name: 'Luminous Charge',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'rare',
    faction: 'vanar',
    text:
      'Summon five joined 0/1 Walls that deal 2 damage to nearby enemies when destroyed.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20163,
    name: 'Spirit of the Wild',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'epic',
    faction: 'vanar',
    text:
      "Reactivate friendly minions on your opponent's starting side of the battlefield.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20289,
    name: 'Vespyrian Might',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 5,
    rarity: 'common',
    faction: 'vanar',
    text: 'Give a Vespyr minion +2/+2 for each friendly Vespyr.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20146,
    name: 'Aspect of the Mountains',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      'Transform ANY minion into a 5/5 Seismic Elemental. Deal 5 damage to enemy minions around it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 556,
    name: 'Draugar Eyolith',
    set: 'immortal',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      '<b>Build</b>: (2).<br/>While this is building or on the battlefield, enemy minions and Generals can only move 1 space.',
    attack: 7,
    health: 14,
    spirit: null
  },
  {
    id: 508,
    name: 'Draugar Lord',
    set: 'core',
    type: 'minion',
    race: 'Vespyr',
    cost: 6,
    rarity: 'epic',
    faction: 'vanar',
    text: '<b>Dying Wish</b>: Summon a 4/8 Ice Drake on this space.',
    attack: 4,
    health: 8,
    spirit: null
  },
  {
    id: 552,
    name: 'Echo Deliverant',
    set: 'immortal',
    type: 'minion',
    race: 'Mech',
    cost: 6,
    rarity: 'rare',
    faction: 'vanar',
    text: 'Whenever you summon another Mech, summon a copy of it nearby.',
    attack: 6,
    health: 4,
    spirit: null
  },
  {
    id: 20207,
    name: 'Frostburn',
    set: 'core',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'rare',
    faction: 'vanar',
    text: 'Deal 3 damage to all enemy minions.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 20295,
    name: 'Icebreak Ambush',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 6,
    rarity: 'epic',
    faction: 'vanar',
    text:
      "Summon an ambush of <b>Infiltrate</b> minions on your opponent's starting side of the battlefield.",
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 564,
    name: 'Oak in the Nemeton',
    set: 'mythron',
    type: 'minion',
    race: '',
    cost: 6,
    rarity: 'mythron',
    faction: 'vanar',
    text:
      '<b>Trial</b>: Have 5 token minions with different names.<br/><b>Destiny</b>: Friendly token minions have +4/+4.',
    attack: 6,
    health: 6,
    spirit: null
  },
  {
    id: 514,
    name: 'Ancient Grove',
    set: 'core',
    type: 'minion',
    race: 'Vespyr',
    cost: 7,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      '<b>Provoke</b><br/><b>Opening Gambit</b>: Your minions gain "<b>Dying Wish</b>: Summon a 1/1 Treant with <b>Provoke</b>".',
    attack: 7,
    health: 7,
    spirit: null
  },
  {
    id: 20293,
    name: 'Flawless Reflection',
    set: 'unearthed',
    type: 'spell',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'vanar',
    text: 'Choose a minion. Transform ALL nearby minions into copies of it.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 541,
    name: 'Ghost Seraphim',
    set: 'ancients',
    type: 'minion',
    race: 'Arcanyst',
    cost: 7,
    rarity: 'legendary',
    faction: 'vanar',
    text: 'The first spell you cast each turn costs 5 less.',
    attack: 8,
    health: 9,
    spirit: null
  },
  {
    id: 20359,
    name: 'Ice Age',
    set: 'mythron',
    type: 'spell',
    race: '',
    cost: 7,
    rarity: 'legendary',
    faction: 'vanar',
    text: 'Summon Blazing Spines along the outside of the battlefield.',
    attack: null,
    health: null,
    spirit: null
  },
  {
    id: 538,
    name: 'Grandmaster Embla',
    set: 'core',
    type: 'minion',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'vanar',
    text:
      '<b>Opening Gambit</b>: Surround the enemy General with random Walls.',
    attack: 5,
    health: 5,
    spirit: null
  },
  {
    id: 543,
    name: 'Matron Elveiti',
    set: 'unearthed',
    type: 'minion',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'vanar',
    text: 'Minions cannot attack your General.',
    attack: 7,
    health: 5,
    spirit: null
  },
  {
    id: 20212,
    name: "Winter's Wake",
    set: 'shimzar',
    type: 'spell',
    race: '',
    cost: 8,
    rarity: 'legendary',
    faction: 'vanar',
    text: 'Give all friendly Wall minions +4/+4. Those minions can now move.',
    attack: null,
    health: null,
    spirit: null
  }
];

export default vanar;
