const vetruvian = [
  { id: 227, name: 'Rae', set: 'shimzar', type: 'minion', race: 'battle pet', cost: 0, rarity: 'common', attack: 1, health: 1, faction: 'vetruvian', text: '<b>Dying Wish</b>: Dispel the nearest enemy minion.' },
  { id: 20073, name: 'Siphon Energy', set: 'core', type: 'spell', cost: 0, rarity: 'common', faction: 'vetruvian', text: 'Dispel an enemy minion nearby your General.' },
  { id: 20132, name: 'Auroras Tears', set: 'core', type: 'spell', cost: 1, rarity: 'epic', faction: 'vetruvian', text: 'This turn, your General gains +2 Attack for every equipped artifact.' },
  { id: 20075, name: 'Blindscorch', set: 'core', type: 'spell', cost: 1, rarity: 'basic', faction: 'vetruvian', text: 'Lower a minion\'s Attack to 0 until your next turn.' },
  { id: 20095, name: `Scion's First Wish`, set: 'core', type: 'spell', cost: 1, rarity: 'basic', faction: 'vetruvian', text: 'Give a friendly minion +1/+1. Draw a card.' },
  { id: 20246, name: 'Stone to Spears', set: 'bloodborn', type: 'spell', cost: 1, rarity: 'rare', faction: 'vetruvian', spirit: 0, text: 'A friendly Obelysk gains +3 Attack and may move and attack this turn if able.' },
  { id: 20151, name: 'Bone Swarm', set: 'core', type: 'spell', cost: 2, rarity: 'common', faction: 'vetruvian', text: 'Deal 2 damage to the enemy General and all enemy minions around them.' },
  { id: 20074, name: 'Cosmic Flesh', set: 'core', type: 'spell', cost: 2, rarity: 'basic', faction: 'vetruvian', text: 'Give a friendly minion +1/+3 and <b>Provoke</b>.' },
  { id: 211, name: 'Dunecaster', set: 'core', type: 'minion', race: 'dervish', cost: 2, rarity: 'common', attack: 2, health: 1, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Give +2/+2 to a friendly Dervish. If it is a Wind Dervish, it no longer disappears.' },
  { id: 214, name: 'Ethereal Obelysk', set: 'core', type: 'minion', race: 'structure', cost: 2, attack: 0, health: 6, rarity: 'basic', faction: 'vetruvian', text: '<b>Summon Dervish</b>' },
  { id: 20152, name: 'Fountain of Youth', set: 'core', type: 'spell', cost: 2, rarity: 'rare', faction: 'vetruvian', text: 'Restore all friendly minions to full Health.' },
  { id: 228, name: 'Pax', set: 'shimzar', type: 'minion', race: 'battle pet', cost: 2, rarity: 'rare', attack: 2, health: 1, faction: 'vetruvian', text: '<b>Dying Wish</b>: Summon two 2/2 Iron Dervishes nearby.' },
  { id: 213, name: 'Pyromancer', set: 'core', type: 'minion', cost: 2, rarity: 'basic', attack: 2, health: 1, faction: 'vetruvian', text: '<b>Blast</b>' },
  { id: 20169, name: `Rasha's Curse`, set: 'core', type: 'spell', cost: 2, rarity: 'epic', faction: 'vetruvian', text: 'Destroy a random artifact on the enemy general. Summon a Wind Dervish with <b>Rush</b> near them.' },
  { id: 20093, name: 'Sand Trap', set: 'core', type: 'spell', cost: 2, rarity: 'common', faction: 'vetruvian', text: 'Choose an enemy minion. It can no longer move.' },
  { id: 20096, name: `Scion's Second Wish`, set: 'core', type: 'spell', cost: 2, rarity: 'basic', faction: 'vetruvian', text: 'Give a friendly minion +2/+2. It takes no damage from Generals.' },
  { id: 30006, name: `Staff Of Y'Kir`, set: 'core', type: 'artifact', cost: 2, rarity: 'basic', faction: 'vetruvian', text: 'Your General gains +2 Attack.' },
  { id: 20196, name: 'Whisper of the Sands', set: 'shimzar', type: 'spell', cost: 2, rarity: 'common', faction: 'vetruvian', text: 'Summon a Wind Dervish nearby each friendly Obelysk. Draw a card.' },
  { id: 229, name: 'Wind Slicer', set: 'shimzar', type: 'minion', cost: 2, rarity: 'rare', attack: 2, health: 3, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Lower the cost of all Structure minions in your action bar by 1.' },
  { id: 20195, name: 'Astral Flood', set: 'shimzar', type: 'spell', cost: 3, rarity: 'common', faction: 'vetruvian', text: 'Put 3 random Battle Pets into your action bar.' },
  { id: 20076, name: 'Astral Phasing', set: 'core', type: 'spell', cost: 3, rarity: 'common', faction: 'vetruvian', text: 'Give a friendly minion +5 Health and <b>Flying</b>.' },
  { id: 20242, name: 'Divine Spark', set: 'bloodborn', type: 'spell', cost: 3, rarity: 'common', faction: 'vetruvian', spirit: 0, text: 'Draw two cards.' },
  { id: 226, name: 'Falcius', set: 'shimzar', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 3, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Your General gains +2 Attack and takes no damage this turn.' },
  { id: 215, name: 'Fireblaze Obelysk', set: 'core', type: 'minion', race: 'structure', cost: 3, rarity: 'rare', attack: 0, health: 6, faction: 'vetruvian', text: '<b>Summon Dervish</b><br> Your Dervishes have +1 Attack.' },
  { id: 218, name: 'Imperial Mechanyst', set: 'core', type: 'minion', cost: 3, rarity: 'rare', attack: 2, health: 5, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Repair all of your artifacts to full durability.' },
  { id: 20153, name: 'Inner Oasis', set: 'core', type: 'spell', cost: 3, rarity: 'rare', faction: 'vetruvian', text: 'Give all friendly minions +3 Health. Draw a card.' },
  { id: 212, name: 'Orb Weaver', set: 'core', type: 'minion', race: 'dervish', cost: 3, rarity: 'common', attack: 2, health: 2, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Summon a copy of this minion on a nearby space.' },
  { id: 221, name: 'Portal Guardian', set: 'core', type: 'minion', cost: 3, rarity: 'epic', attack: 0, health: 6, faction: 'vetruvian', text: '<b>Frenzy</b><br> Whenever you summon a minion, this minion gains +1 Attack.' },
  { id: 20197, name: 'Psychic Conduit', set: 'shimzar', type: 'spell', cost: 3, rarity: 'rare', faction: 'vetruvian', text: 'Take control of an enemy minion with 2 or less Attack until end of turn.' },
  { id: 210, name: 'Sand Howler', set: 'core', type: 'minion', race: 'dervish', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'vetruvian', text: 'Cannot be targeted by enemy spells.' },
  { id: 20097, name: `Scion's Third Wish`, set: 'core', type: 'spell', cost: 3, rarity: 'legendary', faction: 'vetruvian', text: 'Give a friendly Dervish minion +3/+3 and <b>Flying</b>.' },
  { id: 20078, name: 'Time Maelstrom', set: 'core', type: 'spell', cost: 3, rarity: 'legendary', faction: 'vetruvian', text: 'Reactivate your General.' },
  { id: 30008, name: 'Wildfire Ankh', set: 'core', type: 'artifact', cost: 3, rarity: 'epic', faction: 'vetruvian', text: 'Your General gains <b>Blast</b>.' },
  { id: 216, name: 'Windstorm Obelysk', set: 'core', type: 'minion', race: 'structure', cost: 3, rarity: 'common', attack: 0, health: 6, faction: 'vetruvian', text: '<b>Summon Dervish</b><br> Your Dervishes have +1 Health.' },
  { id: 235, name: 'Zephyr', set: 'bloodborn', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 3, faction: 'vetruvian', spirit: 0, text: '<b>Blood Surge:</b> Your General gains Frenzy this turn.' },
  { id: 231, name: 'Allomancer', set: 'shimzar', type: 'minion', cost: 4, rarity: 'epic', attack: 4, health: 3, faction: 'vetruvian', text: '<b>Dying Wish</b>: Summon a random Obelysk on this space.' },
  { id: 20077, name: 'Entropic Decay', set: 'core', type: 'spell', cost: 4, rarity: 'basic', faction: 'vetruvian', text: 'Destroy an enemy minion nearby your General.' },
  { id: 30011, name: 'Hexblade', set: 'core', type: 'artifact', cost: 4, rarity: 'legendary', faction: 'vetruvian', text: 'Your General gains +3 Attack. Whenever your General damages an enemy minion, it\'s Attack becomes 1.' },
  { id: 219, name: 'Mirage Master', set: 'core', type: 'minion', cost: 4, rarity: 'epic', attack: 1, health: 1, faction: 'vetruvian', text: '<b>Opening Gambit</b>: This minion transforms into a copy of an enemy minion.' },
  { id: 224, name: 'Sand Sister Saon', set: 'core', type: 'minion', cost: 4, rarity: 'legendary', attack: 3, health: 4, spirit: 0, faction: 'vetruvian', text: 'Your General has +1 Attack.' },
  { id: 208, name: 'Wind Shrike', set: 'core', type: 'minion', cost: 4, rarity: 'basic', attack: 4, health: 3, faction: 'vetruvian', text: '<b>Flying</b><br> <b>Dying Wish</b>: Draw a card.' },
  { id: 20198, name: 'Corpse Combustion', set: 'shimzar', type: 'spell', cost: 5, rarity: 'epic', faction: 'vetruvian', text: 'Summon all friendly minions with Dying Wish destroyed since your last turn on random spaces.' },
  { id: 236, name: 'Incinera', set: 'bloodborn', type: 'minion', cost: 5, rarity: 'rare', attack: 5, health: 6, faction: 'vetruvian', spirit: 0, text: 'Your General may move 2 additional spaces.' },
  { id: 232, name: 'Nimbus', set: 'shimzar', type: 'minion', cost: 5, rarity: 'legendary', attack: 3, health: 8, faction: 'vetruvian', text: 'Whenever this minion takes damage, summon a Soulburn Obelysk nearby.' },
  { id: 30022, name: 'Spinecleaver', set: 'shimzar', type: 'artifact', cost: 5, rarity: 'legendary', faction: 'vetruvian', text: 'Your General grains +1 Attack. Enemy minions destroyed by your General summon a Bloodfire Totem on that space.' },
  { id: 209, name: 'Starfire Scarab', set: 'core', type: 'minion', cost: 5, rarity: 'common', attack: 4, health: 6, faction: 'vetruvian', text: '<b>Blast</b>' },
  { id: 20105, name: `Stars' Fury`, set: 'core', type: 'spell', cost: 5, rarity: 'epic', faction: 'vetruvian', text: 'Summon a Wind Dervish with <b>Rush</b> in front of each enemy minion and General.' },
  { id: 20244, name: `Autarch's Gifts`, set: 'bloodborn', type: 'spell', cost: 6, rarity: 'epic', faction: 'vetruvian', spirit: 0, text: 'Equip 2 random Vetruvian artifacts.' },
  { id: 220, name: 'Aymara Healer', set: 'core', type: 'minion', cost: 6, rarity: 'legendary', attack: 5, health: 5, faction: 'vetruvian', text: '<b>Provoke</b><br> <b>Dying Wish</b>: Deal 5 damage to the enemy General. Restore 5 Health to your General.' },
  { id: 233, name: 'Pantheran', set: 'shimzar', type: 'minion', cost: 6, rarity: 'epic', attack: 6, health: 6, faction: 'vetruvian', text: 'Costs 0 if you\'ve cast all three Scion\'s Wish spells this game.' },
  { id: 20028, name: 'Dominate Will', set: 'core', type: 'spell', cost: 7, rarity: 'rare', faction: 'vetruvian', text: 'Take control of an enemy minion nearby your General.' },
  { id: 237, name: 'Grandmaster Nosh-Rak', set: 'bloodborn', type: 'minion', cost: 7, rarity: 'legendary', attack: 4, health: 7, faction: 'vetruvian', spirit: 0, text: '<b>Blast</b>, <b>Flying</b><br> The enemy General takes double damage.' },
  { id: 222, name: 'Oserix', set: 'core', type: 'minion', cost: 7, rarity: 'legendary', attack: 8, health: 6, faction: 'vetruvian', text: '<b>Flying</b><br> <b>Dying Wish</b>: Equip 2 random artifacts from your deck.' },
  { id: 20216, name: 'Circle of Desiccation', set: 'shimzar', type: 'spell', cost: 8, rarity: 'legendary', faction: 'vetruvian', text: 'Destroy ALL non-Structure minions.' },
]

export default vetruvian
