const vetruvian = [
  { name: 'Rae', type: 'battle pet', cost: 0, rarity: 'common', attack: 1, health: 1, faction: 'vetruvian', text: '<b>Dying Wish</b>: Dispel the nearest enemy minion.' },
  { name: 'Siphon Energy', type: 'spell', cost: 0, rarity: 'common', faction: 'vetruvian', text: 'Dispel an enemy minion.' },
  { name: 'Auroras Tears', type: 'spell', cost: 1, rarity: 'epic', faction: 'vetruvian', text: 'This turn, your General gains +2 Attack for every equipped artifact.' },
  { name: 'Blindscorch', type: 'spell', cost: 1, rarity: 'core', faction: 'vetruvian', text: 'Lower a minion\'s Attack to 0 until your next turn.' },
  { name: 'Scion\'s First Wish', type: 'spell', cost: 1, rarity: 'core', faction: 'vetruvian', text: 'Give a friendly minion +1/+1. Draw a card.' },
  { name: 'Bone Swarm', type: 'spell', cost: 2, rarity: 'common', faction: 'vetruvian', text: 'Deal 2 damage to the enemy General and all enemy minions around them.' },
  { name: 'Cosmic Flesh', type: 'spell', cost: 2, rarity: 'core', faction: 'vetruvian', text: 'Give a friendly minion +1/+3 and <b>Provoke</b>.' },
  { name: 'Dunecaster', type: 'dervish', cost: 2, rarity: 'common', attack: 2, health: 1, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Give +2/+2 to a friendly Dervish. If it is a Wind Dervish, it no longer disappears.' },
  { name: 'Ethereal Obelysk', type: 'structure', cost: 2, attack: 0, health: 6, rarity: 'core', faction: 'vetruvian', text: '<b>Summon Dervish</b>' },
  { name: 'Fountain of Youth', type: 'spell', cost: 2, rarity: 'rare', faction: 'vetruvian', text: 'Restore all friendly minions to full Health.' },
  { name: 'Pax', type: 'battle pet', cost: 2, rarity: 'rare', attack: 2, health: 1, faction: 'vetruvian', text: '<b>Dying Wish</b>: Summon two 2/2 Iron Dervishes nearby.' },
  { name: 'Pyromancer', type: 'minion', cost: 2, rarity: 'core', attack: 2, health: 1, faction: 'vetruvian', text: '<b>Blast</b>' },
  { name: 'Rasha\'s Curse', type: 'spell', cost: 2, rarity: 'epic', faction: 'vetruvian', text: 'Destroy a random artifact on the enemy general. Summon a Wind Dervish with <b>Rush</b> near them.' },
  { name: 'Sand Trap', type: 'spell', cost: 2, rarity: 'common', faction: 'vetruvian', text: 'Choose an enemy minion. It can no longer move.' },
  { name: 'Scion\'s Second Wish', type: 'spell', cost: 2, rarity: 'core', faction: 'vetruvian', text: 'Give a friendly minion +2/+2. It takes no damage from Generals.' },
  { name: 'Staff of Y\'kir', type: 'artifact', cost: 2, rarity: 'core', faction: 'vetruvian', text: 'Your General gains +2 Attack.' },
  { name: 'Whisper of the Sands', type: 'spell', cost: 2, rarity: 'common', faction: 'vetruvian', text: 'Summon a Wind Dervish nearby each friendly Obelysk. Draw a card.' },
  { name: 'Wind Slicer', type: 'minion', cost: 2, rarity: 'rare', attack: 2, health: 3, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Lower the cost of all Structure minions in your action bar by 1.' },
  { name: 'Astral Flood', type: 'spell', cost: 3, rarity: 'common', faction: 'vetruvian', text: 'Put 3 random Battle Pets into your action bar.' },
  { name: 'Astral Phasing', type: 'spell', cost: 3, rarity: 'common', faction: 'vetruvian', text: 'Give a friendly minion +5 Health and <b>Flying</b>.' },
  { name: 'Falcius', type: 'minion', cost: 3, rarity: 'common', attack: 3, health: 3, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Your General gains +2 Attack and takes no damage this turn.' },
  { name: 'Fireblaze Obelysk', type: 'structure', cost: 3, rarity: 'rare', attack: 0, health: 6, faction: 'vetruvian', text: '<b>Summon Dervish</b><br> Your Dervishes have +1 Attack.' },
  { name: 'Imperial Mechanyst', type: 'minion', cost: 3, rarity: 'rare', attack: 2, health: 5, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Repair all of your artifacts to full durability.' },
  { name: 'Inner Oasis', type: 'spell', cost: 3, rarity: 'rare', faction: 'vetruvian', text: 'Give all friendly minions +3 Health. Draw a card.' },
  { name: 'Orb Weaver', type: 'dervish', cost: 3, rarity: 'common', attack: 2, health: 2, faction: 'vetruvian', text: '<b>Opening Gambit</b>: Summon a copy of this minion on a nearby space.' },
  { name: 'Portal Guardian', type: 'minion', cost: 3, rarity: 'epic', attack: 0, health: 6, faction: 'vetruvian', text: '<b>Frenzy</b><br> Whenever you summon a minion, this minion gains +1 Attack.' },
  { name: 'Psychic Conduit', type: 'spell', cost: 3, rarity: 'rare', faction: 'vetruvian', text: 'Take control of an enemy minion with 2 or less Attack until end of turn.' },
  { name: 'Sand Howler', type: 'dervish', cost: 3, rarity: 'rare', attack: 3, health: 3, faction: 'vetruvian', text: 'Cannot be targeted by enemy spells.' },
  { name: 'Scion\'s Third Wish', type: 'spell', cost: 3, rarity: 'legendary', faction: 'vetruvian', text: 'Give a friendly Dervish minion +3/+3 and <b>Flying</b>.' },
  { name: 'Time Maelstrom', type: 'spell', cost: 3, rarity: 'legendary', faction: 'vetruvian', text: 'Reactivate your General.' },
  { name: 'Wilefire Ankh', type: 'artifact', cost: 3, rarity: 'epic', faction: 'vetruvian', text: 'Your General gains <b>Blast</b>.' },
  { name: 'Windstorm Obelysk', type: 'structure', cost: 3, rarity: 'common', attack: 0, health: 6, faction: 'vetruvian', text: '<b>Summon Dervish</b><br> Your Dervishes have +1 Health.' },
  { name: 'Allomancer', type: 'minion', cost: 4, rarity: 'epic', faction: 'vetruvian', text: '<b>Dying Wish</b>: Summon a random Obelysk on this space.' },
  { name: 'Entropic Decay', type: 'spell', cost: 4, rarity: 'core', faction: 'vetruvian', text: 'Destroy an enemy minion nearby your General.' },
  { name: 'Hexblade', type: 'artifact', cost: 4, rarity: 'legendary', faction: 'vetruvian', text: 'Your General gains +3 Attack. Whenever your General damages an enemy minion, it\'s Attack becomes 1.' },
  { name: 'Mirage Master', type: 'minion', cost: 4, rarity: 'epic', attack: 1, health: 1, faction: 'vetruvian', text: '<b>Opening Gambit</b>: This minion transforms into a copy of an enemy minion.' },
  { name: 'Sand Sister Saon', type: 'minion', cost: 4, rarity: 'legendary', attack: 3, health: 4, faction: 'vetruvian', text: 'Your General has +1 Attack.' },
  { name: 'Wind Shrike', type: 'minion', cost: 4, rarity: 'core', attack: 4, health: 3, faction: 'vetruvian', text: '<b>Flying</b><br> <b>Dying Wish</b>: Draw a card.' },
  { name: 'Corpse Combustion', type: 'spell', cost: 5, rarity: 'epic', faction: 'vetruvian', text: 'Summon all friendly minions with Dying Wish destroyed since your last turn on random spaces.' },
  { name: 'Nimbus', type: 'minion', cost: 5, rarity: 'legendary', attack: 3, health: 8, faction: 'vetruvian', text: 'Whenever this minion takes damage, summon a Soulburn Obelysk nearby.' },
  { name: 'Spinecleaver', type: 'artifact', cost: 5, rarity: 'legendary', faction: 'vetruvian', text: 'Your General grains +1 Attack. Enemy minions destroyed by your General summon a Bloodfire Totem on that space.' },
  { name: 'Starfire Scarab', type: 'minion', cost: 5, rarity: 'common', attack: 4, health: 6, faction: 'vetruvian', text: '<b>Blast</b>' },
  { name: 'Star\'s Fury', type: 'spell', cost: 5, rarity: 'epic', faction: 'vetruvian', text: 'Summon a Wind Dervish with <b>Rush</b> in front of each enemy minion and General.' },
  { name: 'Aymara Healer', type: 'minion', cost: 6, rarity: 'legendary', attack: 5, health: 5, faction: 'vetruvian', text: '<b>Provoke</b><br> <b>Dying Wish</b>: Deal 5 damage to the enemy General. Restore 5 Health to your General.' },
  { name: 'Pantheran', type: 'minion', cost: 6, rarity: 'epic', attack: 6, health: 6, faction: 'vetruvian', text: 'Costs 0 if you\'ve cast all three Scion\'s Wish spells this game.' },
  { name: 'Dominate Will', type: 'spell', cost: 7, rarity: 'rare', faction: 'vetruvian', text: 'Take control of an enemy minion nearby your General.' },
  { name: 'Oserix', type: 'minion', cost: 7, rarity: 'legendary', attack: 8, health: 6, faction: 'vetruvian', text: '<b>Flying</b><br> <b>Dying Wish</b>: Equip 2 random artifacts from your deck.' },
  { name: 'Circle of Desiccation', type: 'spell', cost: 8, rarity: 'legendary', faction: 'vetruvian', text: 'Destroy ALL non-Structure minions.' },
]

export default vetruvian
